#!/bin/sh

# Slice through a header words


# test for CWPROOT
if test "${CWPROOT}" = ""
then
        echo "The environment variable \"CWPROOT\" "
        echo "is not set in the user\'s working shell environment."
        echo "To set this variable in C-shell, use the command: "
        echo "  setenv  CWPROOT  /your/cwp/root/path"
        echo "To set this variable in Bourne or Korn-shell, use the command:"
        echo "  export  CWPROOT=/your/cwp/root/path" ; exit 1

fi

ROOT=${CWPROOT}
BIN=$ROOT/bin

PATH=${PATH}:${BIN}

case $# in
        0) 
                echo " suslice_hdrw key < stdin > stdout" 
        ;;
        *)
               sugethw output=binary key=$1  ; exit 0
        ;;
esac

