#!/bin/csh
#
# -- Installation script
#

#
# -- Set this variable with the real location of JAVA
#

set java_home_dir=/usr/local/jdk1.1.4 

#
# -- Do not moduify anything below this line
#

#
# -- Determines installation directory
#
set instdir=`pwd`
echo
echo INSTALLING ON DIRECTORY: $instdir
echo

#
# -- Create the environment file: $instdir/sugui_init
#
echo setenv JAVA_HOME 	$java_home_dir  > $instdir/sugui_init
echo setenv CLASSPATH	\".\:\$JAVA_HOME/lib/classes.zip\:$instdir/classes\" >> $instdir/sugui_init
echo alias sugui  \"java -DDSUGUIDIR=$instdir sugui\" >> $instdir/sugui_init
echo set path=\(\$JAVA_HOME/bin \$path \) >> $instdir/sugui_init

#
# -- Uncomment the following line to update .cshrc
#
#echo source $instdir/sugui_init >> $HOME/.cshrc
