# pkgIndex.tcl --
#
#	Tksu package index file.  This file is NOT generated by pkg_mkIndex.
#	It arranges for all the scripts comprising tksu to load immediately
#	when the package require command is given.
#
# Copyright (C) 2002 Henry Thorson Consulting.  All rights reserved.
#
# This program is licensed under the terms of the GNU General Public License,
# version 2 (or any later version).  See the file `COPYING' for full details,
# and for a DISCLAIMER OF ALL WARRANTIES.
#
# CVS: $Id: pkgIndex.tcl,v 1.1.1.1 2002/06/07 23:43:30 jeff Exp $

#-------------------------------------------------------------------------------
# tksuPkgIndex -- temporary procedure to invoke `package ifneeded' command.
#
# Args:     dir		Directory where tksu is installed.  This MUST be
#			supplied by the script that sources pkgIndex.tcl.
# Returns:  null
#
# This procedure passes a script to `package ifneeded' consisting of commands
# to immediately source all files in the tksu package.  The `package provide'
# command is appended as well, so that it does not have to be invoked from
# tksu.tcl.
#-------------------------------------------------------------------------------

proc tksuPkgIndex dir {

# Get the version number from VERSION file in the directory.

    if [catch {
	set fid [open [file join $dir VERSION] r]
	set version [string trim [gets $fid]]
	close $fid
    }] {
	return
    }

# All Tcl scripts in the src subdirectory are to be sourced, beginning with
# tksu.tcl.

    set srcDir [file join $dir src]
    set script "source [file join $srcDir tksu.tcl];\n"

    foreach file [exec ls $srcDir] {
	if {[file extension $file] != ".tcl"} continue
	if {$file == "tksu.tcl"} continue
	append script "source [file join $srcDir $file];\n"
    }
    append script "package provide tksu $version"
    package ifneeded tksu $version $script
    return
}

# Invoke the procedure, then remove it.

tksuPkgIndex $dir
rename tksuPkgIndex {}
