#! /bin/sh
#
# tksutar --
#
#	Create tarball tksu-VERSION.tgz from current directory, where VERSION
#	is read from the VERSION file.  The initial (relative) path of all
#	files in the tarball is tksu-VERSION.
#
#	GNU tar is required.
#
# CVS: $id$
#
# The next line restarts using tclsh \
exec tclsh8.0 "$0" "$@"

set version [exec cat VERSION]
set tardir  tksu-$version
set tarball tksu-$version.tgz
exec ln -s . $tardir
puts "Creating $tarball"
exec tar --create \
    --gzip \
    --verbose \
    --file=$tarball \
    --dereference \
    --exclude=CVS \
    --exclude=*.tgz \
    --exclude=$tardir/$tardir \
    $tardir
exec rm $tardir
exit 0
