#!/bin/sh

#set -vx

dt=$1

ns=$2

line=$3

trace=$4

iy0=$5 

ix0=$6

nx=$7

datain=$8

#echo  "dt=${dt} line=${line} trace=${trace}"

#echo "iy0=${iy0} ix0=${ix0} nx=${nx}"

#echo "datain=${datain}"

suaddhead < ${datain} ns=${ns} | sushw key=dt a=${dt} |

sushw key=${line} a=${iy0} c=1 j=${nx} |

sushw key=${trace} a=${ix0} b=1 j=${nx} |

sushw key=cdpt a=1 | sushw key=trid a=1
