#!/bin/csh
#
# -- Installation script
#

#
# -- Determines installation directory
#
set thisdir=`pwd`
set instdir=$thisdir/dsu
set tardir=$thisdir/tar_files
echo
echo Installing on directory: $instdir
echo

#
# -- Create the directories
#
mkdir $instdir

#
# -- Create the environment file: $instdir/dsu_init
#
echo setenv DSUINST	$instdir 	     >  $thisdir/dsu_init
#echo setenv JAVA_HOME 	$instdir/jdk1.1.6    >> $thisdir/dsu_init
echo setenv JAVA_HOME 	/usr/local/jdk1.1.1    >> $thisdir/dsu_init
echo setenv CLASSPATH	\".\:\$JAVA_HOME/lib/classes.zip\:$instdir/gui\" >> $thisdir/dsu_init
echo alias dsugui  \"java -DDSUGUIDIR=$instdir/gui dsugui\" >> $thisdir/dsu_init
echo set path=\(\$JAVA_HOME/bin \$path \) >> $thisdir/dsu_init

#
# -- Untar the tar files
#
cd $instdir
tar -xvf $tardir/dsugui.tar
#gunzip -c $tardir/jdk1.1.6-v2-glibc.tar.gz | tar xvf -

#
# -- Uncomment the following line to update .cshrc
#
#echo source $thisdir/dsu_init >> $HOME/.cshrc
