#!/bin/bash

# This test shows how to use the 5 componenet designature/deconvolution module
# The five components are shot,receiver,offset,azimuth,average spectral component
#
# The azimuth component is usefull for removing the effect of linear geophone arrays
# on arrivals from all directions (as it is happens with some 3D acqusition geometries) 
#
# First several shots are created then the some of the shots are bandpass filtered,
# then they are sorted into receiver gathers and some are bandpass filtered again.
#
# The deconvolution succesfully solves for these spectral alterations and removes the effects
#
# For detailes see:
# P.W. Cary and G.A. Lorentz, Four-component surface consistent
# deconvolution, 1993. Geophysics, 58: 383-392 
#
# These are the three modules
# suscd5_m1 - creates the log spectras
# suscd5_m2 - solves for the individual spectral components
# suapscd5_m - applies the solutions to the gathers ie. removes the choosen affect
# typically shot,receiver,offset,azimuth, and average componenets make sense to be removed
# 
# In the exmaple the shot,receiver,offset,azimuth are removed 



echo
echo
echo " Five component surfaces consistent deconvolution test"
echo
echo


nshot=25
nrec=200



function m_shots()
{
nt=500
dt=0.001
kilounits=0

nxo=$nrec
dxo=10
fxo=-1000

nxs=$nshot
dxs=20
fxs=0.0
v00=3000


dsh="shots_g"
drv="recv_g"
dcdir="scd5_amp"
dsh_d="dec_shots_g"

if [ -d $dcdir ]
then
	rm -fr $dcdir
fi
mkdir $dcdir


susynlv nt=$nt dt=$dt kilounits=$kilounits \
	nxo=$nxo dxo=$dxo fxo=$fxo \
	nxs=$nxs dxs=$dxs fxs=$fxs \
	ref="1:-400,250;1500,250"   \
	ref="0.8:00,500;3000,500"   \
	v00=$v00 fpeak=90.0 \
	verbose=1 ndpfz=10 \
	| suaddnoise sn=20 \
	> tmp.su
}


function f_g()
{
	
	cp $1 tmp.su
	cat tmp.su |
	sufilter f=$2 \
	> $1

}

m_shots
# Fill in the headers

	cat tmp.su |
	suabshw key=offset |
	suchw key1=ep key2=fldr |           # shot position number
	suchw key1=sdepth key2=gx a=101 b=0.1|   # receiver position number starting at 1
	                                    #  at receiver number 1 
	suchw key1=cdp key2=fldr key3=tracf b=10 c=10 d=2 \
	> shots.su


	cat shots.su	|
	suputgthr_sort dir=$dsh	key=ep
	
	rm tmp.su shots.su	
	
# Filter shots 7 14 20 24
# to create surface consistent effects on shots

	f_g $dsh/7.hsu  "1,10,20,160" 	
	f_g $dsh/14.hsu "1,10,20,160" 	
	f_g $dsh/20.hsu "1,8,20,160" 	
	f_g $dsh/24.hsu "20,30,120,160" 	
	 
# Filter shots 20 35 46 78 98, 120, 130, 200 
# to create surface consistent effects on receivers
	sugetgthr dir=$dsh |
	suputgthr_sort key=sdepth dir=$drv
	
	f_g $drv/20.hsu  "1,10,20,160" 	
	f_g $drv/35.hsu "1,10,60,160" 	
	f_g $drv/46.hsu "1,8,20,160" 	
	f_g $drv/46.hsu "10,18,60,140" 	
	f_g $drv/50.hsu "1,7,40,160" 	
	f_g $drv/55.hsu "1,10,30,160" 	
	f_g $drv/78.hsu "5,30,120,160" 	
	f_g $drv/98.hsu "1,8,30,160" 	
	f_g $drv/120.hsu "1,8,70,160" 	
	f_g $drv/130.hsu "1,30,100,160" 	
	f_g $drv/200.hsu "1,20,70,160" 	
	
	sugetgthr dir=$drv |
	suputgthr_sort key=ep dir=$dsh
	
#
#
#
# Designature starts here
#	
#	
	
	sugetgthr dir=$dsh |
	sufilter f=0.5,3.0,190,210    |
	suscd5_m1 ts=0.1 te=0.5 o=0.0 hb=5	# Extract log spectras
	
	# Run module #2 to solve for individual solutions	
	suscd5_m2 nit=7 sm2=15 	    \
	fns=$dcdir'/s.lgs' fng=$dcdir'/g.lgs'         \
	fnh=$dcdir'/h.lgs' fny=$dcdir'/y.lgs'         \
	fnz=$dcdir'/z.lgs' fna=$dcdir'/a.lgs'         \
	> $dcdir'/da.lgs'
	
	suximage < $dcdir'/s.lgs' cmap="rgb1" title="Recovered shot log spectra" key=ep blockinterp=1 &
	suximage < $dcdir'/g.lgs' cmap="rgb1" title="Recovered reciver log spectra" key=sdepth blockinterp=1 &
	
	#  Correct for the recovered effects
	sugetgthr dir=$dsh |
	sufilter f=0.5,3.0,190,210    |
        suapscd5_m fnl=0 fmin=0.0 fmax=190 \
                   fftpad=50.0 \
                   ltpr=3 htpr=7 prw=10e-1 \
                   s=1  g=1  h=1  y=0  z=1   \
                   sp=0 gp=0 hp=0 yp=0 zp=0 \
                   a=0 ap=0 \
		   res=0  smt=2  \
                   hb=5 zb=5     \
		   time=0 oplen=0.080 \
                 fns=$dcdir'/s.lgs' fng=$dcdir'/g.lgs'    \
                 fnh=$dcdir'/h.lgs' fny=$dcdir'/y.lgs'    \
                 fnz=$dcdir'/z.lgs' fna=$dcdir'/a.lgs'    |
	sufilter f=0.5,3.0,160,170    |
	suputgthr_sort key=ep dir=$dsh_d
	
	cat $dsh_d/15.hsu | suspecfx |
	suximage perc==99 blockinterp=1 cmap="rgb1" title="Spectra after designature"&
	
	cat $dsh/15.hsu | suspecfx |
	suximage perc==99 blockinterp=1 cmap="rgb1" title="Spectra of original shot"&
		
	cat $dsh_d/15.hsu |
	suxwigb key=sdepth \
	x1beg=0.20 x1end=0.4 x2beg=30 x2end=60 clip=20 \
	blockinterp=1 title="Zoom in; After designature"&
	
	cat $dsh/15.hsu |
	suxwigb key=sdepth \
	x1beg=0.20 x1end=0.4 x2beg=30 x2end=60 clip=20 \
	blockinterp=1 title="Zoom in; Original shot"&
	
echo 
echo "Done with the test" 
echo
echo

	
	
