/*
 * hdr.h - include file for segy offset array
 * THIS HEADER FILE IS GENERATED AUTOMATICALLY - 
 * see the makefile in this directory
 */

#ifndef HDR_H
#define HDR_H

static struct {
	char *key;	char *type;	int offs;
} hdr[] = {
	   "tracl",		"l",		0,
	   "tracr",		"l",		4,
	    "fldr",		"l",		8,
	   "tracf",		"l",		12,
	      "ep",		"l",		16,
	     "cdp",		"l",		20,
	    "cdpt",		"l",		24,
	    "trid",		"h",		28,
	     "nvs",		"h",		30,
	     "nhs",		"h",		32,
	    "duse",		"h",		34,
	  "offset",		"l",		36,
	   "gelev",		"l",		40,
	   "selev",		"l",		44,
	  "sdepth",		"l",		48,
	    "gdel",		"l",		52,
	    "sdel",		"l",		56,
	   "swdep",		"l",		60,
	   "gwdep",		"l",		64,
	  "scalel",		"h",		68,
	  "scalco",		"h",		70,
	      "sx",		"l",		72,
	      "sy",		"l",		76,
	      "gx",		"l",		80,
	      "gy",		"l",		84,
	  "counit",		"h",		88,
	   "wevel",		"h",		90,
	  "sweves",		"h",		92,
	     "sut",		"h",		94,
	     "gut",		"h",		96,
	   "sstat",		"h",		98,
	   "gstat",		"h",		100,
	   "tstat",		"h",		102,
	    "laga",		"h",		104,
	    "lagb",		"h",		106,
	   "delrt",		"h",		108,
	    "muts",		"h",		110,
	    "mute",		"h",		112,
	      "ns",		"u",		114,
	      "dt",		"u",		116,
	    "gain",		"h",		118,
	     "igc",		"h",		120,
	     "igi",		"h",		122,
	    "corr",		"h",		124,
	     "sfs",		"h",		126,
	     "sfe",		"h",		128,
	    "slen",		"h",		130,
	    "styp",		"h",		132,
	    "stas",		"h",		134,
	    "stae",		"h",		136,
	   "tatyp",		"h",		138,
	   "afilf",		"h",		140,
	   "afils",		"h",		142,
	  "nofilf",		"h",		144,
	  "nofils",		"h",		146,
	     "lcf",		"h",		148,
	     "hcf",		"h",		150,
	     "lcs",		"h",		152,
	     "hcs",		"h",		154,
	    "year",		"h",		156,
	     "day",		"h",		158,
	    "hour",		"h",		160,
	  "minute",		"h",		162,
	     "sec",		"h",		164,
	  "timbas",		"h",		166,
	    "trwf",		"h",		168,
	  "grnors",		"h",		170,
	  "grnofr",		"h",		172,
	  "grnlof",		"h",		174,
	    "gaps",		"h",		176,
	   "otrav",		"h",		178,
	      "d1",		"f",		180,
	      "f1",		"f",		184,
	      "d2",		"f",		188,
	      "f2",		"f",		192,
	  "ungpow",		"f",		196,
	 "unscale",		"f",		200,
	    "mark",		"h",		204,
	    "mutb",		"h",		206,
	      "dz",		"f",		208,
	      "fz",		"f",		212,
	      "n2",		"h",		216,
};
#endif
