# Description file for SU includes
# Note that header.h and hdr.h are CREATED, not retrieved
#
# $Author: jkc $
# $Revision: 1.9 $ ; $Date: 88/05/15 06:37:27 $

include $(CWPROOT)/src/Makefile.config

INCLUDE = 	$I/segy.h	\
		$I/segd.h	\
		$I/hdr.h	\
		$I/header.h	\
		$I/su.h		\
		$I/su_xdr.h	\
		$I/tapesegy.h	\
		$I/tapehdr.h	\
		$I/tapebhdr.h	\
		$I/bhdr.h	\
		$I/bheader.h

INSTALL	: header.h hdr.h $(INCLUDE)
	@-rm -f INSTALL
	@touch $@

header.h	: mkheader
	./mkheader >header.h
mkheader	: mkheader.c prehdr.h
	$(CC) $(CFLAGS) mkheader.c -o mkheader

hdr.h	:mkhdr
	./mkhdr >hdr.h

mkhdr	:mkhdr.c offsets.h prehdr.h
	$(CC) $(CFLAGS) mkhdr.c -o mkhdr

offsets.h	:mkoffs.sh segy.h
	$(CPP) segy.h | ./mkoffs.sh >offsets.h
prehdr.h	:mkprehdr.sh segy.h
	$(CPP) segy.h | ./mkprehdr.sh >prehdr.h

$(INCLUDE):	$(ITARGET)
	@-rm -f $@
	@cp $? $@
	@chmod 664 $@
	@echo $(@F) installed in $I

clean	:
	@-rm -f mkheader mkhdr offsets.h prehdr.h *.o

remake	:
	@$(MAKE) clean
	@-rm -f $(INCLUDE) INSTALL
	@$(MAKE) ROOT=$(ROOT)
