#!/bin/sh
broot1="/mnt/sdata1/seis/LC4"
broot2="/mnt/sdata/Ssx"
#
# NUMBERING
# Inline Crossline
#    000 000      composite CDP number
#

# INPUT CDP GATHERS
cdpdir=$broot2"/cdp_gathers"
#cdpdir=$broot1"/cdp_gathers_rs"
#cdpdir=$broot1"/cdp_gathers_ma"
#cdpdir=$broot"/cdp_gathers_f"


#
# Input semblane list file
smblf="semblance_list.txt"
#

#
# TEMPORARY FILES
stmp="/mnt/sdata/tmp"
ext=".hsu"
# Velan related files
velan=$broot2"/velan"

# SUPER CDP GATHER OUPUT
SCDPdir=$velan"/scdp_gathers"
#SCDPdir=$velan"/scdp_gathers_rf"
#SCDPdir=$velan"/scdp_gathers_rf_rs"

# SEMBLANCE OUPUTS 
sembdir=$velan"/semb"
#sembdir=$velan"/semb_rf"
#sembdir=$velan"/semb_rf_rs"

# Residual Static files
stdir=$broot2'/rs/'
strv='rv-v4afx4d.st-40'
stsh='sh-v4afx4d.st-40'
echo 'APPLYING STATICS'

# VELOCITY SCAN PARAMETERS
# Velocity range for CVS
vels="1000"
vele="7000"
veli="50"
nvel="120"
smute=1.3
pwr=0.9
dtratio=15
tw=0.02
tmin=0.0
tmax=2.0
dt=0.001
# Semblance mute
velms=7000
velme=7000
velts=0.0
velte=0.6
mtpr=15
# offset binsize
of_bin=15
minoff=0
maxoff=1500


# THIS SECTION DESCRIBES HOWTO MAKE THE SUPER GATHERS
# Create super cdp gathers from single cdp gathers
# inline number is the first three digits in the composite cdp
# crossline number is the last three digits in the composite cdp

# INLINE BAND WIDTH, SPECIFICATIONS
#Band with in inline direction on both sides of the inline
inlbw=3

# CROSSLINE BAND WIDTH, SPECIFICATIONS
crlbw=3


function scdp_templ
{
# Create a template gather for the scdp gathers
# The traces are all zero traces
# the offset, d1, f1 fields are set so ximage can plot it correctly
# of_bin minoff maxoff variables has to be specified outside
# tmax dt also
# the gather is tmplt.hsu and stored in the directory where the
# routine is called from
if [ -f tmplt.hsu ]
	then /bin/rm tmplt.hsu
fi

ns=`bc -l <<END
        scale=0
        ($tmax-$tmin)/$dt+1
END`

off=$minoff

while [ $off -le $maxoff ]
do
	sunull nt=$ns dt=$dt ntr=1 |
	sushw key=offset,d2,f2 a=$off,$of_bin,$minoff \
	>> tmplt.hsu
	let "off = off + of_bin"
done 
}

function semb
{
# The SCDPG IS BUILT DO A CVS ON IT
# $1 name of the SCDPG
# $2 scdp number
if [ -f $1 ] 
	then 	sushw < $1 key=cdp a=$2 b=0 c=0 |
		suvelan nv=$nvel dv=$veli fv=$vels smute=$smute \
		dtratio=$dtratio pwr=$pwr tw=$tw |
		sushw key=offset a=$vels b=$veli |
		sumute key=offset xmute=$vels,$velms,$velme \
		        tmute=0.1,$velts,$velte ntaper=$mtpr     \
		> $sembdir"/"$2".semb.su" 
fi
}

# Remove temporary files
if [ -f $stmp"/tmp1.hsu" ]
    then rm $stmp"/tmp1.hsu"
fi 

if [ -f $stmp"/tmp.hsu" ]
    then rm $stmp"/tmp.hsu"
fi 

# Create the background template gather
scdp_templ

# Construct the cdp number of the centre of the inline and cross line bands
inls=0

# loop over inlines
for scdp in `cat $smblf`
do 
       echo $scdp
      # Get the range of cdps belonging to this SCDPG
      # Inline range
cdps=`bc -l <<END2
	scale=0
	$scdp-$inlbw*1000-$crlbw
END2`	
cdpe=`bc -l <<END5
	scale=0
	$scdp+$inlbw*1000+$crlbw
END5`	
      echo $cdpis $cdpie $cdprs $cdpre
      
      SCDPGF=$SCDPdir"/"$scdp".hsu" 
      
      echo $cdps $cdpe
      
      let "cdp = cdps"

      ilc=1
      ilce=0
      let "ilce = 2*inlbw+1"
      while [ $ilc -le $ilce ]
      do
       	     clc=1
      	     clce=0
      	     let "clce = 2*crlbw+1"
             while [ $clc -le $clce ]
              do
#        	      echo -n $cdp" "
		      
        	      # Get cdp gather from the directory and add to 
        	      # $SCDPG
        	      if [ -f $cdpdir"/"$cdp".hsu" ]
        		      then cat $cdpdir"/"$cdp".hsu" >> $stmp"/tmp1.hsu"
        	      fi 
        	      let "cdp +=1"
        	      let "clc +=1"
              done
              let "cdp =cdps+1000*ilc"
              let "ilc +=1"
      done	      
      echo " "
      suwind tmax=$tmax tmin=$tmin < $stmp"/tmp1.hsu" |
#     suwind key=otrav min=30 max=90 |
      # Apply residual statics
     suapstat_f st=$stdir$stsh rt=$stdir$strv maxshft=0.080|
      sufilter f=15,20,50,59 amp=0,1,1,1				|
      # Offset binnig
      suchw key1=offset key2=offset d=$of_bin a=0.5 |
      suchw  key1=offset key2=offset b=$of_bin > $stmp"/tmp.hsu"
      cat tmplt.hsu $stmp"/tmp.hsu" |
      suwind key=offset min=$minoff max=$maxoff > $stmp"/tmp1.hsu"   
      susort <  $stmp"/tmp1.hsu" offset |
      # Some processing can go here
      sugain agc=1 wagc=0.200	      |
      subfilt fstoplo=10 fpasslo=17 \
	      fpasshi=80 fstophi=100 zerophase=1     |
#     sufilter f=15,20,50,60 |
      sustack key=offset      |
      sugain pbal=1	    > $SCDPGF
      rm  $stmp"/tmp.hsu" $stmp"/tmp1.hsu"
      semb $SCDPGF $scdp
done
