#!/bin/sh

. vdir

tmin=0.0
tmax=2.0
dt=0.02
trdt=20000
vtmin=2500
vtmax=5200
ns=`bc -l <<END
	scale=0
	($tmax-$tmin)/$dt+1
END`

inln=119
crln=123

#veldir="/bigdata/seis/3D/Ssx/velan/picks_rf_rs/"
veldir=$vdir"/picks/"

velout=$vdir"/raw_v_functions.su"
if [ -f $velout ]
	then rm $velout
fi

iln=1
cln=1

for f in `find $veldir -size 0`
do
	rm $f
done

while [ $iln -le $inln ]
do
	while [ $cln -le $crln ]
	do
		let "cdp=iln*1000+cln"
		file="par.$cdp"
	        if [ -s $veldir$file ]
	  	       then    	suvpar2tr `cat $veldir$file` \
	 		       	tmin=$tmin tmax=$tmax \
			       	vtmin=$vtmin vtmax=$vtmax \
			       	cdp=$cdp dt=$dt             |
			       	suchw key1=fldr a=$iln  b=0 |
				suchw key1=tracf a=$cln b=0 >> $velout
				echo $cdp" *"
		       else
		       		sunull ntr=1 dt=$dt nt=$ns |
				suchw key1=cdp a=$cdp   b=0 |
				suchw key1=fldr a=$iln  b=0 |
				suchw key1=tracf a=$cln b=0 |
				suchw key1=trid a=32    b=0 |
				suchw key1=d1   a=$dt   b=0 >> $velout
#				echo $cdp
		fi
		let "cln+=1"
	done
	let "iln+=1"
	let "cln=1"
done
