#! /bin/sh
# Script to smooth velocity file
. vdir

file=$vdir"/int_v_functions_nn.su"
fileout=$vdir"/sm_int_v_functions_nn.su"
hdrfile='tmp1'
grid='tmp2'
gridout='tmp3'

n1=101
n3=119
n2=123

r1=0
r2=200
r3=200
d2=20
d3=25
#r2=25
#r3=25
vminc=1500
vmaxc=5000
#minimum wavelengths of raw velocity:
#lambda1 = 2.6949,
#lambda2 = 24.9152,
#lambda3 = 17.8284,
#lambda = 2.67661,


slowness=1

	sustrip < $file head=$hdrfile > $grid

	smooth3d < $grid n1=$n1 n2=$n2 n3=$n3 \
		d2=$d2 d3=$d3 d1=$d1          \
 		r1=$r1 r2=$r2 r3=$r3 slowness=$slowness \
		vminc=$vminc vmaxc=$vmaxc \
 		time=1 verbose=1 iter=$iter> $gridout
	
	supaste < $gridout ns=$n1 head=$hdrfile verbose=1 > $fileout

	rm $hdrfile $grid $gridout
