#!/bin/sh

. vdir
vel=$vdir'/raw_v_functions_nn.su'
vel=$vdir'/int_v_functions_nn.su'
vell=$vdir'/sm_int_v_functions_nn.su'

	suslice < $vell ts=$1 | ximage d1=1 d2=1 n1=123 n2=119 \
		f1num=2 f2num=2 d2num=5 d1num=5 legend=1 \
		grid1=dot grid2=dot \
		wbox=700 hbox=500 \
		windowtitle=' Slice across smoothed Nearest Neighbour volume @ '$1'(s)' &

	suslice < $vel ts=$1 | ximage d1=1 d2=1 n1=123 n2=119 \
		f1num=2 f2num=2 d2num=5 d1num=5 legend=1 \
		grid1=dot grid2=dot \
		wbox=700 hbox=500 \
		windowtitle=' Slice across Nearest Neighbour velocity volume @ '$1'(s)' 
