	SUBROUTINE DUMMIES
	ENTRY DSKMS8
	  CALL CANCEL(100,'DO NOT CALL ME')
	  RETURN
        ENTRY DSKMI8
	  CALL CANCEL(100,'DO NOT CALL ME')
	  RETURN
        ENTRY DSKMO8
	  CALL CANCEL(100,'DO NOT CALL ME')
	  RETURN
        ENTRY DSKMN8
	  CALL CANCEL(100,'DO NOT CALL ME')
	  RETURN
	END
