#! /bin/ksh
# Velocity analyses for the cmp gathers
set -x

SCRATCH=/scratch/jkc/Nmodata

# Determine velocity sampling.
nv=100 dv=50.0 fv=4000.0 v0=5000.0
integer cdpmin=1500 cdpmax=3000 dcdp=500 fold=64 cdp

# Do the velocity analyses.
cdp=cdpmin
while ((cdp<=cdpmax))
do
	suwind <$SCRATCH/traces.su key=cdp min=$cdp max=$cdp count=$fold |
	suvelan nv=$nv dv=$dv fv=$fv |
	suximage1 bclip=0.5 wclip=0.0 f2=$fv d2=$dv \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Velocity Scan for CMP $cdp" \
		grid1=solid grid2=solid cmap=default mpicks=mpicks.$cdp &
	cdp=cdp+dcdp
done

pause create parameter file after all picks are made---WAIT!

# edit the picks
cdp=cdpmin
while ((cdp<=cdpmax))
do
	vel2nmo <mpicks.$cdp >par.$cdp
	cdp=cdp+dcdp
done

>stkvel.par

print -n "cdp=" >>stkvel.par
cdp=cdpmin
while ((cdp<cdpmax))
do
	print -n "$cdp," >>stkvel.par
	cdp=cdp+dcdp
done
print "$cdpmax" >>stkvel.par

cdp=cdpmin
while ((cdp<=cdpmax))
do
	cat par.$cdp >>stkvel.par
	cdp=cdp+dcdp
done
