#! /bin/ksh
# Velocity analyses for the cmp gathers
# Authors: Dave, Jack
# NOTE: Comment lines preceeding user input start with  #!#
#set -x

#!# Set parameters
velpanel=/scratch/jkc/western/cdpby100
vpicks=stkvel.p1
integer cdpmin=201
integer cdpmax=800
integer dcdp=2000
#integer dcdp=200
#integer dcdp=100
integer min max count
integer fold=30

#!# Set velocity sampling and band pass filters
nv=51 dv=30 fv=1500
f1=3 f2=6 f3=30 f4=36


### Get header info
nout=$(sugethw ns <$velpanel | sed 1q | sed 's/.*ns=//')
dt=$(sugethw dt <$velpanel | sed 1q | sed 's/.*dt=//')
dxout=$(bc -l <<-END
	$dt / 1000000
END)


print "Compare picking v, 1/v, 1/v^2"

### Do the velocity analyses.
integer cdp=cdpmin
while ((cdp <= cdpmax))
do
	print "Starting velocity analysis for cdp $cdp"

	normpow=0 slowness=0
	suwind <$velpanel key=cdp min=$cdp max=$cdp count=$fold |
	sugain tpow=2 |
	suband f1=$f1 f2=$f2 f3=$f3 f4=$f4 |
	suvelan3 nv=$nv dv=$dv fv=$fv \
		normpow=$normpow slowness=$slowness |
	suximage bclip=0.2 wclip=0.0 f2=$fv d2=$dv \
		xbox=50 ybox=75 wbox=400 hbox=430 \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Velocity: normpow=$normpow slowness=$slowness" \
		grid1=solid grid2=solid cmap=default &

	normpow=0 slowness=1
	suwind <$velpanel key=cdp min=$cdp max=$cdp count=$fold |
	sugain tpow=2 |
	suband f1=$f1 f2=$f2 f3=$f3 f4=$f4 |
	suvelan3 nv=$nv vmax=$vmax fv=$fv \
			normpow=$normpow slowness=$slowness |
	suximage bclip=0.2 wclip=0.0 f2=$fv d2=$dv \
		xbox=475 ybox=75 wbox=400 hbox=430 \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Slowness: normpow=$normpow slowness=$slowness" \
		grid1=solid grid2=solid cmap=default &

	normpow=0 slowness=2
	suwind <$velpanel key=cdp min=$cdp max=$cdp count=$fold |
	sugain tpow=2 |
	suband f1=$f1 f2=$f2 f3=$f3 f4=$f4 |
	suvelan3 nv=$nv vmax=$vmax fv=$fv \
			normpow=$normpow slowness=$slowness |
	suximage bclip=0.2 wclip=0.0 f2=$vmax d2=-$dv \
		xbox=50 ybox=550 wbox=400 hbox=430 \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Sloths: normpow=$normpow slowness=$slowness" \
		grid1=solid grid2=solid cmap=default &

#		xbox=450 ybox=550 wbox=377 hbox=430 \

	pause do next velans

	cdp=cdp+dcdp
done
