#! /bin/ksh
# Velocity analyses for the cmp gathers
# Authors: Dave, Jack
# NOTE: Comment lines preceeding user input start with  #!#
#set -x

#!# Set parameters
velpanel=/scratch/jkc/western/cdpby100
vpicks=stkvel.p1
integer cdpmin=201
integer cdpmax=800
integer dcdp=2000
#integer dcdp=200
#integer dcdp=100
integer min max count
integer fold=30

#!# Set velocity sampling and band pass filters
nv=51 dv=30 fv=1500
f1=3 f2=6 f3=30 f4=36


### Get header info
nout=$(sugethw ns <$velpanel | sed 1q | sed 's/.*ns=//')
dt=$(sugethw dt <$velpanel | sed 1q | sed 's/.*dt=//')
dxout=$(bc -l <<-END
	$dt / 1000000
END)


### Do the velocity analyses.
integer cdp=cdpmin
while ((cdp <= cdpmax))
do
	print "Starting velocity analysis for cdp $cdp"

	suwind <$velpanel key=cdp min=$cdp max=$cdp count=$fold |
	sugain tpow=2 |
	suband f1=$f1 f2=$f2 f3=$f3 f4=$f4 |
	suvelan nv=$nv dv=$dv fv=$fv |
	suximage bclip=0.2 wclip=0.0 f2=$fv d2=$dv \
		xbox=45 ybox=75 wbox=600 hbox=800 \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Orig Velan for CMP $cdp" \
		grid1=solid grid2=solid cmap=default &

	normpow=1 slowness=0
	suwind <$velpanel key=cdp min=$cdp max=$cdp count=$fold |
	sugain tpow=2 |
	suband f1=$f1 f2=$f2 f3=$f3 f4=$f4 |
	suvelan3 nv=$nv dv=$dv fv=$fv \
		normpow=$normpow slowness=$slowness |
	suximage bclip=0.2 wclip=0.0 f2=$fv d2=$dv \
		xbox=860 ybox=75 wbox=600 hbox=800 \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Serge: normpow=$normpow slowness=$slowness" \
		grid1=solid grid2=solid cmap=default &

	cdp=cdp+dcdp
done
