#!/bin/sh

nshot=51
nrec=51
c=2000
dt=0.001
nt=1000
x0=500
y0=500
z0=250
gxmin=0
gymin=0
gzmin=0
dgx=20
dgy=0
dgz=0
dlgx=0
dlgy=20
dlgz=0
zoff=1



	sudif3d nshot=$nshot nrec=$nrec c=$c dt=$dt nt=$nt \
	        x0=$x0 y0=$y0 z0=$z0 \
		gxmin=$gxmin gymin=$gymin gzmin=$gzmin \
		dgx=$dgx dgy=$dgy dgz=$dgz \
		dlgx=$dlgx dlgy=$dlgy dlgz=$dlgz \
		zoff=$zoff 					|
	sufilter f=0,5,70,120 > stack.su


	makevel nx=$nshot ny=$nrec nz=500 \
	        v000=2000                    |
	suaddhead ns=500 > vel.su


	cat stack.su |
#	suzero   itmax=1.0 |
#	sumsp ns=250 a=1.0 |
	sufilter f=0,5,70,120 \
	> stack_diff.su
