#!/bin/sh

s=stack_diff.su
v=vel.su


#	mpirun n0-13 su3dmigpspi_mpi \
#	su3dmigpspi_pvm \
	mpirun n0-12 su3dmigpspi_mpi \
		      tmpd="/export/data" \
	              NPROC=12                    \
	              n2=51 n3=51 d2=20 d3=20 \
	              dz=2.0 nz=250 dzv=2.0  \
		      fs=$s fv=$v verbose=1 > "mig_layer_10%_e-mpi.su"
