#
# makefile for the su/lvec directory
#
#L     =	./libvec.a
LDIR	= /usr/local/lib/
D = /usr/local/obj/
L = $(LDIR)libvec.a

CFLAGS = -g
FFLAGS = -g

.SUFFIXES: .c .f .a
#.c.o:
#	$(CC) -c $(CFLAGS) $<
#	ar rv $@ $*.o
#	/bin/rm -f $*.o
#.f.o:
#	$(FC) -c $(FFLAGS) $<
#	ar rv $@ $*.o
#	/bin/rm -f $*.o
#.f.o:	;f77 $(FFLAGS) -c $*.f;
#.r.f:	;ratfor $*.r > $*.f

O =	$L(libvec.o)							\
	$L(cefft.o) $L(cvfft.o) $L(refft.o) $L(rvfft.o) \
	$L(dotpow.o) $L(doclip.o) $L(doepow.o) $L(dogpow.o) \
	$L(doqbal.o) $L(dopbal.o) $L(doscale.o) $L(dotrap.o) \
	$L(quant.o) $L(balclip.o) $L(copyabs.o) $L(bfill.o)\
        $L(ibmflt.o)

F = $Doperhan.o $Dconvv.o $Drowcc.o $Dcroscor.o $Dblend.o     \
	$Dtoepl.o $Dagcf.o $Dwinhan.o $Dfftprep.o $Drfftm.o \
    $Dnextfft.o $Dcfftm.o \
	$Dfilrec.o $Dprecheb.o $Dpolcheb.o $Drecform.o \
	$Dsemblan.o $Dburg.o

$L lvec : $O $F
	ar rv $L $F
	ranlib $L

$Dagcf.o	:agcf.f
	$(FC) -c $(FFLAGS) agcf.f
	mv agcf.o $D
$Dblend.o	:blend.f
	$(FC) -c $(FFLAGS) blend.f
	mv blend.o $D
$Dburg.o	:burg.f
	$(FC) -c $(FFLAGS) burg.f
	mv burg.o $D
$Dcfftm.o	:cfftm.f
	$(FC) -c $(FFLAGS) cfftm.f
	mv cfftm.o $D
$Dconvv.o	:convv.f
	$(FC) -c $(FFLAGS) convv.f
	mv convv.o $D
$Dcroscor.o	:croscor.f
	$(FC) -c $(FFLAGS) croscor.f
	mv croscor.o $D
$Dfilrec.o	:filrec.f
	$(FC) -c $(FFLAGS) filrec.f
	mv filrec.o $D
$Dfftprep.o	:fftprep.f
	$(FC) -c $(FFLAGS) fftprep.f
	mv fftprep.o $D
$Dnextfft.o	:nextfft.f
	$(FC) -c $(FFLAGS) nextfft.f
	mv nextfft.o $D
$Doperhan.o	:operhan.f
	$(FC) -c $(FFLAGS) operhan.f
	mv operhan.o $D
$Dpolcheb.o	:polcheb.f
	$(FC) -c $(FFLAGS) polcheb.f
	mv polcheb.o $D
$Dprecheb.o	:precheb.f
	$(FC) -c $(FFLAGS) precheb.f
	mv precheb.o $D
$Drecform.o	:recform.f
	$(FC) -c $(FFLAGS) recform.f
	mv recform.o $D
$Drfftm.o	:rfftm.f
	$(FC) -c $(FFLAGS) rfftm.f
	mv rfftm.o $D
$Drowcc.o	:rowcc.f
	$(FC) -c $(FFLAGS) rowcc.f
	mv rowcc.o $D
$Dtoepl.o	:toepl.f
	$(FC) -c $(FFLAGS) toepl.f
	mv toepl.o $D
$Dwinhan.o	:winhan.f
	$(FC) -c $(FFLAGS) winhan.f
	mv winhan.o $D
$Dsemblan.o	:semblan.f
	$(FC) -c $(FFLAGS) semblan.f
	mv semblan.o $D

list	:
	ar tv $L

remake	:
	rm -f $L
	make $L

#operhan.o	:operhan.f
#	f77 -c $(FFLAGS) operhan.f
#rowcc.o	:rowcc.f
#	f77 -c $(FFLAGS) rowcc.f
#convv.o	:convv.f
#	f77 -c $(FFLAGS) convv.f

clean	:
	-/bin/rm $L
	-/bin/rm -f *.o
	-/bin/rm -f *.a
