.TH 3DCHART 9SU SU
.SH NAME
.B 3dchart \-
x-midpoint vs. y-midpoint plot with hard wired plot options
.SH SYNOPSIS
.na
.nf
3dchart <stdin | tube
\&...| 3dchart | tube
.SH DESCRIPTION
.I 3dchart
is a Bourne shell program providing an interface to su3dchart(1).
It supplies a plot command that is usually acceptable:
pipe the data through the cplot command, curve, with the
symbol parameter set to "cdot".
.P
Self documentation is
given only with the - argument to admit the standard
SU usage of data from a pipe or data from stdin.
.P
In addition to the standard SU usage of data on stdin,
.I 3dchart
will accept a filename argument.
.SH CAVEATS
Maybe the pipe into tube(9SH) should also have been hardwired in.
.SH SEE ALSO
su3dchart(1) tube(9SU) chart(9SU)
.SH AUTHOR
Shuki
.SH SOURCE
su/shell/3dchart
.SH REVISION LEVEL
1.12
