.TH CHART 9SU SU
.SH NAME
.B chart \-
stacking chart with hard wired plot options
.SH SYNOPSIS
.na
.nf
chart <stdin | tube
\&...| chart | tube
.SH DESCRIPTION
.I Chart
is a Bourne shell program providing an interface to 
suchart(1) in the usual case when that command 
is being used to make a stacking chart.
It supplies a plot command that is usually acceptable:
pipe the data through the cplot command, curve, with the
symbol parameter set to "cdot", xlabel set to "SHOT",
and ylabel set to "RECEIVER."
.P
Self documentation is
given only with the - argument to admit the standard
SU usage of data from a pipe or data from stdin.
.P
In addition to the standard SU usage of data on stdin,
.I chart
will accept a filename argument.
.SH CAVEATS
Maybe the pipe into tube(9SH) should also have been hardwired in.
.SH SEE ALSO
suchart(1) tube(9SU) 3dchart(9SU)
.SH AUTHOR
Shuki, Jack.
.SH SOURCE
su/shell/chart
.SH REVISION LEVEL
1.10
