.TH LOOKPAR 9SU SU
.SH NAME
.B lookpar \-
show getpar lines in SU code with defines evaluated
.SH SYNOPSIS
.nf
lookpar suprog.c ...
.SH DESCRIPTION
.I Lookpar
is a Bourne shell program that
shows the getpar lines in an SU application code with defines evaluated
by the C macro preprocessor.
Thus, the SU application programmer can use symbolic defines
at the top of a program to set defaults for easy maintenance,
and yet is able to
scan the program for the defaults with the values evaluated numerically.
.SH EXAMPLE
.na
.nf
	cd /src/su/src
	lookpar segyread.c
.fi
.ad
.P
Assuming that the source code is in the indicated directory, this produces:
.na
.nf
	tape = "/dev/r1600mt0";	sgetpar("tape",  &tape);
	hfile = "header";	sgetpar("hfile", &hfile);
	bfile = "bhed";		sgetpar("bfile", &bfile);
	trmin = 1;		igetpar("trmin", &trmin);
	trmax =   2147483647	;	igetpar("trmax", &trmax);
	over = 0;		igetpar("over", &over);
.fi
.ad
The symbolic constants, "RMTDEVICE" and "INT_MAX", have been
evaluated respectively as "/dev/r1600mt0" and "2147483647."
The remaining getpar lines have been printed literally.
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/lookpar
.SH REVISION LEVEL
1.5
