.TH MAXDIFF 9SU SU
.SH NAME
.B maxdiff \-
get maximum absolute difference in two sets of SEG-Y data sets
.SH SYNOPSIS
.nf
maxdiff file1 file2
.SH DESCRIPTION
.I Maxdiff
is a Bourne shell program that provides
an SU testing and debugging tool.
Typically it is used to compare the SU data from
a "new" and "old" version of an suprogram.
If
.I maxdiff
produces an answer less than about 7.0e-5, one has some evidence
that the changes have not harmed the program.
.P
Thus,
.I maxdiff
is a generalization of the system program cmp(1) which can be
used to verify that
.I no
changes have occurred in the data.  However, when the
changes have affected the floating point operation
order, often rounding will cause small changes in the output
data, rendering cmp useless for comparison purposes.
.I Maxdiff
is implemented as a pipe between sudiff(1) and sumax(1).
.P
Self documentation is given unless the argument count is exactly two.
In particular it is given on command alone or command plus - argument.
.SH SEE ALSO
cmp(1) sudiff(1) sumax(1))
.SH AUTHOR
Jack
.SH SOURCE
su/shell/maxdiff
.SH REVISION LEVEL
1.6
