.TH QQTWIG 9SU SU
.SH NAME
.B qqtwig \-
quick windowed sutwig plot
.SH SYNOPSIS
.nf
qqtwig [count= min=] <stdin
.SH DESCRIPTION
.I Qqtwig
is a Bourne shell program that calls sutwig and pipes the
resulting wiggle trace byte codes through tube(9SU) so that
the wiggle traces are directly put on the graphics terminal screen.
Fill and labeling are turned off.
.P
Trace windowing options are provided to select the starting trace and the
total number of number of traces to be wiggle plotted.  These parameters
are accepted in standard getpar format, see the examples below.
.SH PARAMETERS
.TP 8
.I count
The number of traces to plot; the default is four traces.
.TP
.I min
The first trace to plot; the default is 1 (the first trace in the data set).
.SH EXAMPLES
.na
.nf
	qqtwig <DATA
	qqtwig count=10 <DATA
	qqtwig <DATA min=10 count=15
.fi
.ad
.P
These commands respectively wiggle plot the first four traces, the first
ten traces, and the tenth through 24th trace.
.SH SEE ALSO
sutwig(1) suwig(1) qtwig(9SU) qwig(9SU)  qqwig(9SU)
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/qqtwig
.SH REVISION LEVEL
1.1
