.TH QQWIG 9SU SU
.SH NAME
.B qqwig \-
very quick no-frills wiggle trace program for slow terminals
.SH SYNOPSIS
.nf
qqwig [count= min=] <stdin
.SH DESCRIPTION
.I Qwig
is a Bourne shell program that calls suwig and pipes the
resulting wiggle trace byte codes through tube(9SU) so that
the wiggle traces are directly put on the graphics terminal screen.
The sizes used by
.I qqwig
are half the defaults of suwig(1), that is, the horizontal axis
is 2.25 inches and the vertical axis is 3 inches.
Trace windowing options are provided to select the starting trace and the
total number of number of traces to be wiggle plotted.  These parameters
are accepted in standard getpar format, see the examples below.
.SH PARAMETERS
.TP 8
.I count
The number of traces to plot; the default is four traces.
.TP
.I min
The first trace to plot; the default is 1 (the first trace in the data set).
.SH EXAMPLES
.na
.nf
	qqwig <DATA
	qqwig count=10 <DATA
	qqwig <DATA min=10 count=15
.fi
.ad
.P
These commands respectively wiggle plot the first four traces, the first
ten traces, and the tenth through 24th trace.
.SH SEE ALSO
suwig(1) qwig(9SU) qtwig(9SU)  qqtwig(9SU)
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/qqwig
.SH REVISION LEVEL
1.8
