.TH QTWIG 9SU SU
.SH NAME
.B qtwig \-
quick sutwig plot
.SH SYNOPSIS
.nf
qtwig <stdin
.SH DESCRIPTION
.I Qtwig
is a Bourne shell program that calls sutwig and pipes the
resulting wiggle trace byte codes through tube(9SU) so that
the wiggle traces are directly put on the graphics terminal screen.
Fill and labeling are turned off and no options are provided.
.SH EXAMPLE
.na
.nf
        qtwig <DATA
.fi
.ad
.SH SEE ALSO
sutwig(1) suwig(1) qqtwig(9SU) qwig(9SU)  qqwig(9SU)
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/qtwig
.SH REVISION LEVEL
1.1
