.TH QWIG 9SU SU
.SH NAME
.B qwig \-
quick no-frills wiggle trace program for slow terminals
.SH SYNOPSIS
.nf
qwig <stdin
.SH DESCRIPTION
.I Qwig
is a Bourne shell program that calls suwig and pipes the
resulting wiggle trace byte codes through tube(9SU) so that
the wiggle traces are directly put on the graphics terminal screen.
The sizes used by
.I qwig
are half the defaults of suwig(1), that is, the horizontal axis
is 2.25 inches and the vertical axis is 3 inches.
No options are provided.
.SH EXAMPLE
.na
.nf
        qwig <DATA
.fi
.ad
.SH SEE ALSO
suwig(1) qqwig(9SU) qtwig(9SU)  qqtwig(9SU)
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/qwig
.SH REVISION LEVEL
1.7
