.TH RECIP 9SU SU
.SH NAME
.B recip \-
sum opposing offsets in cdp sorted data
.SH SYNOPSIS
.na
.nf
recip <stdin >stdout
.SH DESCRIPTION
.I Recip
is a Bourne shell program
providing an interface to surecip(1) to carry
out the pre-processing required by this SU program.  The result
is data in which positive and negative offsets with a common
midpoint have been summed.
.I Recip
is implemented using the SU programs suabshw(1) and
susort(1).
.SH SEE ALSO
surecip(1) suabshw(1) susort(1)
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/recip
.SH REVISION LEVEL
1.7
