.ds U \s-2\f(sRUNIX\fP\s0
.ds SY \s-2\f(sRSEG-Y\fP\s0
.TH SUSHELL 9SU SU
.SH NAME
.B sushell \-
Introduction to the shell programs for the
.I SU
(seismic unix) processing line
.SH DESCRIPTION
The shell programs used to implement command sequences and/or
often used options.  See the
.I
suintro(1)
manual page for an introduction to the application
programs themselves.
Below is a list of the shell programs with one line descriptions,
see the individual manual pages for complete descriptions.
.SH SHELLS (5/31/88)
.sp .5v
.TP 12
.I 3dchart
plot x-midpoints versus y-midpoints
.TP
.I chart
plot a stacking chart
.TP
.I lookpar
examine getpar defaults after pass through cpp
.TP
.I maxdiff
get maximum absolute difference in two data sets
.TP
.I qqtwig
quick windowed sutwig plot
.TP
.I qqwig
quick windowed suwig plot
.TP
.I qtwig
quick sutwig plot
.TP
.I qwig
quick suwig plot
.TP
.I recip
interface to surecip
.TP
.I sufind
get information about SU application programs
.TP
.I tube
device independent pen program
.TP
.I unglitch
remove outliers by calling sugain
.TP
.I updatedoc
update sufind data base
.SH BUGS
Send reports to:
.ne 6
.sp
.nf
Jack K. Cohen
Center for Wave Phenomena
Colorado School of Mines
Golden, CO 80401
.fi
.SH FILES
At the Center for Wave Phenomena,
the directory for source code is /src and our directory for
compiled code is /usr.  These prefixes are omitted below
since they may not apply to other sites.
.sp .5v
.TP 24
.I su/src/shell/*
Bourne shell source
.TP
.I su/src/man/*
manual page source
.SH AUTHORS
Shuki, Jack, Chris
.SH REVISION DATE
05/31/88
