.TH TUBE 9SU SU
.SH NAME
.B tube \-
device independent pen
.SH SYNOPSIS
.na
.nf
cplot_program <stdin | tube
\&...| cplot_program | tube
.SH DESCRIPTION
.I Tube
is a Bourne shell program that tries to determine the proper pen
program for the user's terminal.
The advantages of using
.I tube
instead of directly calling the pen program are (1) a user who 
uses several graphics terminals has a consistent user interface
instead of having to remember to say "fpen" on a Falco, "tpen" on
a Tektronix, etc. and (2) programmers can just update 
.I tube
instead of
updating a nest of if-then-else statements in many codes.
Examples of programs using
.I tube
in this way are suedit(1) and the shells qwig(9SU), qqwig(9SU), qtwig(9SU),
and qqtwig(9SU).
.SH EXAMPLE
.na
.nf
	sutwig <DATA | tube
.fi
.ad
.P
This command wiggle plots the su datafile, DATA, on any supported graphics
device.
.SH CAVEATS
.I Tube
will work on a given device only if (1) a pen program
program has been written for that device, (2) the tube program
has been updated appropriately and (3) in cases where the termcap
entry is used for more than one graphics device,
a duplicate entry has been made in /etc/termcap
(eg., a Falco emulating a vt100 requires a "falco"
termcap paragraph that is a copy of the vt100 paragraph except for
replacing the terminal names by "falco").
.SH SEE ALSO
suwig(1) sutwig(1) qwig(9SU) qqwig(9SU) qtwig(9SU) qqtwig(9SU)
.SH AUTHOR
Shuki, Jack.
.SH SOURCE
su/shell/tube
.SH REVISION LEVEL
1.2
