.TH UNGLITCH 9SU SU
.SH NAME
.B unglitch \-
remove outliers in an SEG-Y data set
.SH SYNOPSIS
.nf
unglitch <stdin >stdout
.SH DESCRIPTION
.I unglitch
is a Bourne shell program providing an interface to sugain(1) to remove
outliers.  More specifically, unglitch does a quantile clip
at the .99 quantile (99th percentile).  It may be applied
repeatedly if more clipping is required.
.SH EXAMPLE
.nf
	unglitch <DATA | unglitch >OUTDATA
.fi
.sp
The data has been clipped twice and stored in OUTDATA.
.SH SEE ALSO
sugain(1) gainpkge(3SU)
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/unglitch
.SH REVISION LEVEL
1.3
