.TH UPDATEDOC 9SU SU
.SH NAME
.B updatedoc \-
put self-docs in su/doc & stripped versions in su/doc/Stripped
.SH SYNOPSIS
.nf
updatedoc
.SH DESCRIPTION
.I Updatedoc
is a Bourne shell program that
puts the self documentation strings from every program in
su/src into su/doc and also puts stripped versions into su/doc/Stripped.
The stripped versions form the data base used by sufind(9SU).
.P
This program is meant to be run automatically using a crontab(1) file.
.SH SEE ALSO
crontab(1) sufind(9SU)
.SH AUTHOR
Jack.
.SH SOURCE
su/shell/updatedoc
.SH REVISION LEVEL
1.4
