#! /bin/sh
# Let 1 sample be .005 km
# windowing is a real adventure: the tmin in resamp has to be synched with f1 in sushw

cc traces.c -o traces -lm

traces |
suaddhead ns=512 |
sushw key=dt a=4000 |
suband |
sushw key=dt a=0 |
sushw key=trid a=30 |
sushw key=d1 a=0.005  |
supswigb label1="Depth (km)"  label2="Trace" title="beta" |
images

traces |
suaddhead ns=512 |
sushw key=dt a=4000 |
suband |
suresamp tmin=0.8 nt=312 |
sushw key=dt a=0 |
sushw key=trid a=30 |
sushw key=d1 a=0.005  |
sushw key=f1 a=1.0  |
supswigb label1="Depth (km)"  label2="Trace" title="beta with reflectors omitted" |
images

rm traces

