#!/bin/csh -ve
make junk
#chart <junk
#suchw < junk key2=sx key3=offset c=1 key1=gx | chart
#plot <junk
#sutpow tpow=2 <junk | plot

<junk	susort offset sx | \
	sutpow tpow=2 | \
	suchw key1=gx key2=sx key3=offset c=1 | \
	suchw key2=sx key3=gx c=1 d=2 | \
	sutee jdata | \
	sunmo v=1500 | \
	sutee jdata.nmo | \
	sudmo \
>jdata.dmo

susort cdp <jdata     | sustack >jstack
susort cdp <jdata.nmo | sustack >jstack.nmo
susort cdp <jdata.dmo | sustack >jstack.dmo

exit

sucat jstack jstack.nmo jstack.dmo | plot


sutpow tpow=2 <junk | suchw key2=sx key3=offset c=1 key1=gx | suchw key2=sx key3=gx c=1 d=2 >junk2
chart <junk2
plot <junk2
suwind <junk2 max=400 | chart
susub junk2 junk2 | suplot | hpen300
susort cdp <junk2 | sunmo v=1500 | tee junk.nmo | sustack | tee jstack.nmo | plot
#plot <junk.nmo
susort offset sx < junk2 | plot
susort offset sx < junk.nmo | plot
susort offset cdp < junk.nmo | sudmo > junk.dmo 
suhis <junk.dmo
susort <junk.dmo | sustack | tee jstack.dmo | plot
#suplot < jstack.nmo > j 
#suplot < jstack.dmo >> j x0=4 
#hpen300 j 
sucat jstack.nmo jstack.dmo | subal | suplot qclip=95 | hpen300 
exit

