#!/bin/sh -ve
make junk
pause see junk
chart <junk
plot <junk

susort<junk|sunmo vel=1500|sustack|sutpow tpow=2|sutee jstack.brute|supef tol=48>jpsd

pause see jstack.brute
plot <jstack.brute

pause see jpsd
plot <jpsd

<junk \
	susort offset sx | \
	sutpow tpow=2 | \
	supef tol=48 | \
	suchw key1=gx key2=sx key3=offset c=1 | \
	suchw key2=sx key3=gx c=1 d=2 | \
	sutee jdata | \
	sunmo vel=1500 | \
	sutee jdata.nmo | \
	sudmo \
>jdata.dmo

susort cdp <jdata     | sustack >jstack
susort cdp <jdata.nmo | sustack >jstack.nmo
susort cdp <jdata.dmo | sustack >jstack.dmo

echo "Plots?"
read answer
echo $answer
#if($answer != "y" ) then exit; fi

plot <jstack
plot <jstack.nmo
plot <jstack.dmo

exit
