#!/bin/csh -ve
make junk

<junk	susort offset sx | \
	sutpow tpow=2 | \
	sutee jdata | \
	sunmo v=1500 | \
	sutee jdata.nmo | \
	sudmo \
>jdata.dmo

susort cdp <jdata     | sustack >jstack
susort cdp <jdata.nmo | sustack >jstack.nmo
susort cdp <jdata.dmo | sustack >jstack.dmo

plot<jstack
plot<jstack.nmo
plot<jstack.dmo
sucat jstack jstack.nmo jstack.dmo | plot
