#!/bin/sh -v
make junk
chart <junk
suwind < junk skip=10 count=20 >j
pause
<j chart
suwind < junk max=600  >j
pause
<j chart
suwind key=offset <junk min=700 max=700  >j
pause
<j chart
suwind key=offset <junk min=700 max=-700 >j
pause
<j chart
