#! /bin/ksh
# Velocity analyses for the cmp gathers
set -x

SCRATCH=/scratch/jkc/Nmodata

# Determine velocity sampling.
nv=100 dv=50.0 fv=4000.0

# Do the velocity analyses.
##for cdp in 1500 2000 2500 3000
for cdp in 1800
do
	suwind <$SCRATCH/traces.su key=cdp min=$cdp max=$cdp count=64 |
	suvelan nv=$nv dv=$dv fv=$fv |
#	suximage bclip=0.5 wclip=0.0 f2=$fv d2=$dv \
	suxwigb bclip=0.5 wclip=0.0 f2=$fv d2=$dv \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Velocity Scan for CMP $cdp" \
		grid1=solid grid2=solid cmap=gray mpicks=mpicks.$cdp
done

# edit the picks
##for cdp in 1500 2000 2500 3000
##do
##	vel2nmo <mpicks.$cdp v0=5000 >par.$cdp
##done
##>sengbush.stkvel
##print "cdp=1500,2000,2500,3000" >>sengbush.stkvel
##for cdp in 1500 2000 2500 3000
##do
##	cat par.$cdp >>sengbush.stkvel
##done

# for vplot
##sustkvel par=sengbush.intvel outpar=sengbush.stkvel

