#! /bin/sh
# Make a synthetic and exercise segyread, segywrite

set -x

suplane >data
segyhdrs ns=64 <data
segywrite <data tape="written_data"
segyread >read_data tape="written_data"
supswigb <read_data | open
