#! /bin/sh

suplane dip1=4 ct1=16 len1=32 dip2=4 ct2=32 len2=32 dip3=4 ct3=48 len3=32 >junk

sutvband <junk tf=0.0,0.252 f=0,8,100,110 f=0,8,100,110  >junk2eqe
sutvband <junk tf=0.0,0.252 f=0,8,100,110 f=0,4,32,36  >junk2e
sutvband <junk tf=0.08,0.24 f=0,8,100,110 f=0,8,100,110  >junk2eq
sutvband <junk tf=0.08,0.24 f=0,8,100,110 f=0,4,32,36  >junk2

sudiff junk2eqe junk2e >junk2diffe
sudiff junk2eq junk2 >junk2diff

supswigb <junk2eqe title="sutvband: 2 equal filters (endpts)" | images
supswigb <junk2e   title="sutvband: 2 unequal filters (endpts)" | images
supswigb <junk2diffe title="difference (endpts)" | images
supswigb <junk2eq title="sutvband: 2 equal filters (interior)" | images
supswigb <junk2   title="sutvband: 2 unequal filters (interior)" | images
supswigb <junk2diff title="difference (interior)" | images
