#! /bin/sh

suplane dip1=4 ct1=16 len1=32 dip2=4 ct2=32 len2=32 dip3=4 ct3=48 len3=32 >junk

sutvband <junk tf=.05,0.125,0.20 f=0,8,48,64 f=0,8,48,64 f=0,8,48,64 >junk3eq
sutvband <junk tf=.05,0.125,0.20 f=0,8,100,110 f=0,8,48,64 f=0,2,16,20 >junk3

sudiff junk3eq junk3 >junk3diff

supswigb <junk3eq title="sutvband: 3 equal filters" | images
supswigb <junk3      title="sutvband: 3 unequal filters" | images
supswigb <junk3diff title="difference" | images
