#! /bin/sh

suplane dip1=4 ct1=16 len1=32 dip2=4 ct2=32 len2=32 dip3=4 ct3=48 len3=32 >junk

./suband <junk f1=0 f2=8 f3=48 f4=64 >junkb

sutvband <junk tf=.05,0.2 f=0,8,48,64 f=0,8,48,64  >junk2

sudiff junkb junk2 >junkb2
sumax <junkb
sumax <junkb2

supswigb <junkb title="suband" | images
supswigb <junk2 title="sutvband: 2  equal filters" | images
supswigb <junkb2 title="difference" | images
