#! /bin/sh

suplane dip1=4 ct1=16 len1=32 dip2=4 ct2=32 len2=32 dip3=4 ct3=48 len3=32 >junk

./suband <junk f1=0 f2=8 f3=48 f4=64 >junkb

sutvband <junk tf=0.0,0.11,0.252 f=0,8,48,64 f=0,8,48,64 f=0,8,48,64  >junke

sudiff junkb junke >junkbe
sumax <junkb
sumax <junkbe

supswigb <junkb title="suband" | images
supswigb <junke title="sutvband: endpts given" | images
supswigb <junkbe title="difference" | images

