#! /bin/sh

suplane dip1=4 ct1=16 len1=32 dip2=4 ct2=32 len2=32 dip3=4 ct3=48 len3=32 >junk

suband <junk f1=0 f2=8 f3=48 f4=64 >junkb
suband.bak <junk f1=0 f2=8 f3=48 f4=64 >junkbin

sudiff junkb junkbin >junkb1
sumax <junkb
sumax <junkb1

supswigb <junkb title="new suband" | images
supswigb <junkbin title="old suband" | images
supswigb <junkb1 title="difference" | images
