#
# makefile for su/doc directory
#

M = /usr/man/manl/

S = apass.1l dotpow.1l err.1l getbh.1l getpar.1l gettr.1l hisclose.1l \
       hislog.1l hispr.1l input.1l output.1l putbh.1l puttr.1l selfdoc.1l \
       sufilt.1l sutpow.1l sugpow.1l dogpow.1l supef.1l

install:
	cp $S $M
	chmod 644 $M$S

clean	:
	@echo "clean what?"
