#! /bin/sh

TARLISTA="README* LEGAL_STATEMENT cwp.su.all.30.5A.tar.Z"
TARLISTB="cwp.su.all.30.5B.tar.Z"
TARLISTC="documentation.30.letter.tar.Z"


while [ 1 = 1 ]
do
	pause after putting disk in drive

	echo "Making Disk B:"
	echo

	tar -cvf /dev/fd0 $TARLISTA
	pause after replacing the disk that is in the drive with a new one

	echo "Making Disk B:"
	echo

	tar -cvf /dev/fd0 $TARLISTB
	pause after replacing the disk that is in the drive with a new one
done
