#! /bin/ksh

>mute.dat
suplane offset=200 >>mute.dat
suplane offset=400 >>mute.dat
suplane offset=600 >>mute.dat
suplane offset=800 >>mute.dat

sumute <mute.dat \
	below=1 \
	xmute=100,400,700,1000 \
	tmute=0.0,.05,0.1,0.15	>top

sumute <mute.dat \
	xmute=100,400,700,1000 \
	tmute=0.1,.12,.16,0.21	>bottom

susum top bottom |
suximage title="Mute" &
