D = ./
L = $Dlibsu.a

FLAGS = -g

OBJ =	msgpkge.o iopkge.o parpkge.o valpkge.o hdrpkge.o \
	option.o \
	isatape.o isapipe.o \
	selfdoc.o \
	gname.o \
	doagc.o doclip.o doepow.o dogpow.o doqbal.o dopbal.o doscale.o dotpow.o dotrap.o powerof.o quant.o \
	getclip.o balclip.o copyabs.o \
	bfill.o \
	index.o bcopy.o bzero.o

.SUFFIXES: .c .r .f .o
.c.o:	;cc  -c $(FLAGS) $*.c; chmod 666 $*.o
.f.o:	;f77 -c $(FLAGS) $*.f; chmod 666 $*.o
.r.o:	;f77 -c $(FLAGS) $*.r; chmod 666 $*.o

$L	:$(OBJ)
	ar r $L $(OBJ)
#ranlib $(L)

remake	:
	rm -f $(OBJ) $L
	make $L

list	:
	ar tv $L

$Dsutrseq.o	: sutrseq.o
	cp sutrseq.o $D
	chmod 664 $Dsutrseq.o

clean	:
	-rm -f *.o

