#
# Config Makefile for compiling Distributed Seismic Unix applications
#

include $(CWPROOT)/src/Makefile.config
DSUROOT =  $(CWPROOT)/src/dsu

#
# Dsu modifications to: $(CWPROOT)/src/Makefile.config
#

B = $(PVM_ROOT)/bin/$(PVM_ARCH)
D = $(DSUROOT)/lib/libdsu.a $L/libcwp.a $L/libpar.a $L/libsu.a
DSUMAIN = $(CWPROOT)/src/su/main
CFLAGS= -I$(DSUROOT)/include -I$I $(OPTC) $(ENDIANFLAG) -I$(PVM_ROOT)/include
LDSU = -L$(DSUROOT)/lib -ldsu -L$(PVM_ROOT)/lib/$(PVM_ARCH) -lpvm3
LFLAGS= $(PRELFLAGS) $(LDSU) -L$L -lsu -lpar -lcwp $(ARCHLIB) -lm $(POSTLFLAGS)

# Use this CTARGET for regular make
#
CTARGET = $(DSUMAIN)/$$(@F).c

# Use this CTARGET for GNU make
#
CTARGET = $B/%: $(DSUMAIN)/%.c

#
# End Dsu modifications
