##################################################################
##
#
# KEYWORDS:  $RCSfile: Makefile,v $
#            $Revision: 1.2 $
#            $Date: 2001/09/13 20:23:56 $
#            $Author: ahmilb $
#
#------------------------------------------------------------------
#
# HISTORY:
#
#
#
###################################################################

include ../../Makefile_template_part1

PROG = bhplibcube.a
RCSfiles.c = hdr_lib.c usphdr_lib.c bhpiocube_lib.c interp_lib.c bhpio_lib.c fold_lib.c
OBJS.c = obj/$(PLATFORMID)/hdr_lib.o obj/$(PLATFORMID)/usphdr_lib.o obj/$(PLATFORMID)/bhpiocube_lib.o \
obj/$(PLATFORMID)/interp_lib.o obj/$(PLATFORMID)/bhpio_lib.o obj/$(PLATFORMID)/fold_lib.o
PACK = ../../bin/$(PLATFORMID)/bhplibcube.a

include ../../Makefile_template_lib
