#! /bin/csh -f 
set noglob

set DIR=$CWPROOT/src/su/graphics/psplot

foreach f ($argv)
	set a = $f:r
	echo processing file: $DIR/$f -- Par file: $a.su.graphics.psplot 
	./argfiles < $DIR/$f > $a.su.graphics.psplot
end
