#! /bin/csh -f 
set noglob

set DIR=$CWPROOT/src/su/graphics/xplot

foreach f ($argv)
	set a = $f:r
	echo processing file: $DIR/$f -- Par file: $a.su.graphics.xplot 
	./argfiles < $DIR/$f > $a.su.graphics.xplot
end
