#!/bin/bash

#
# Residual static test
#
# Synthetic shots are created , then random time shifts are added
# to the traces on a surface consistent manner.
# The alogrithm solves for these and applies them.
# No prior knowledge about the acquisition geomtery is required.
# Works on 3D data also.
# 
# Shot id should be stored in headerword ep
# Receiver id should be stored in headerword sdepth
# CDP number should be stored in headerword cdp
#
# It also demonstartes the need to have a good long wavelength 
# statics in place from refraction statics. The residual static can only
# correct for short wavelength variation
#
# Solutions after each iteration are stored in a seperate file
#
#The algorithm used here is based on
#	Ronen, Claerbout, 1985. Surface-consistent residual static
#	estimation by stack-power maximization. 
#	Geophysics, 50, 12: 2759-2767.
#   The above is modified to shuffle the shotpoint and receiver point access
#   sequence randomly for each iteration. This is beleived to result in a more
#   stable algorithm.

echo
echo "Residual static test"
echo
echo







nshot=25
nrec=200


function m_shots()
{
nt=500
dt=0.001
kilounits=0

nxo=$nrec
dxo=10
fxo=-1000

nxs=$nshot
dxs=20
fxs=0.0
v00=3000

function rand() 
{
	n=$1
	d=$2
	RANDOM=$$$(date +%s)
	i=0
	while [ $i -lt $n ]
	do
		r=$[( $RANDOM %$d )  ]
		let "r = r - ($d/2)"
		echo $r
	let "i+=1"
	done
	
}

susynlv nt=$nt dt=$dt kilounits=$kilounits \
	nxo=$nxo dxo=$dxo fxo=$fxo \
	nxs=$nxs dxs=$dxs fxs=$fxs \
	ref="1:-400,250;1500,250"   \
	ref="0.8:00,500;3000,500"   \
	v00=$v00 fpeak=90.0 \
	verbose=1 ndpfz=10 \
	| suaddnoise sn=10 \
	> tmp.su
}

m_shots
# Fill in the headers

	cat tmp.su |
	suabshw key=offset |
	suchw key1=ep key2=fldr |           # shot position number
	suchw key1=sdepth key2=gx a=101 b=0.1|   # receiver position number starting at 1
	                                    #  at receiver number 1 
	suchw key1=cdp key2=fldr key3=tracf b=10 c=10 d=2 \
	> shots.su

	sugethw < shots.su output=geom key=ep |
	uniq \
	> tmp1.txt

#
# Add random time shifts at receivers and shot points
#
#


	
rand $nshot 20 > tmp2.txt
paste tmp1.txt tmp2.txt > shot_static.txt
	
	sugethw < shots.su output=geom key=sdepth |
	sort -n |
	uniq \
	> tmp1.txt

nrp=`wc -l < tmp1.txt` #receiver positions
rand $nrp 10 > tmp2.txt
paste tmp1.txt tmp2.txt > receiver_static.txt

	sulhdr < shots.su \
		cf=shot_static.txt key=ep,otrav |
	sulhdr  cf=receiver_static.txt key=sdepth,gaps |
	sushift key=otrav				|
	sushift key=gaps \
		> shots_static.su
	
	# Do NMO on gathers
	sunmo vnmo=3000 < shots_static.su |
	suwind tmin=0.1 tmax=0.35         \
	> shots_static_nmo_w.su


#
# Compute cross correlation based static solution 
#
#

	# Show uncorrected stack
	susort <  shots_static_nmo_w.su cdp |
	sustack |
	suximage perc=99 title="Stack without correction" &

 	suresstat_tr_f fn=shots_static_nmo_w.su ffa=1 \
	maxshft=0.010 it=20 maxeshft=0.050


	# Apply statics; show section with static effects removed
	susort < shots_static_nmo_w.su cdp |
	suapstat_f \
	st="sh.st-19" rt="rv.st-19" |
	sustack |
	suximage perc=99 title=" Recovered static applied before stacking" 
	

echo
echo " Done with the test"
echo
echo
	

	

