.TH SEGYWRITE 1 SU
.SH NAME
.B segywrite \-
Write an SEG-Y tape
.SH SYNOPSIS
.nf
segywrite <stdin [tape=RMTDEVICE]
.fi
.SH DESCRIPTION
.I Segywrite
creates a SEG-Y format tape given an su data set, a 3200 byte ascii
file of 40 equal 80 character lines, and a 400 byte binary file.
The latter two header files may be created with segyhrs(1).
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I tape 
the raw tape device to use, the default is the string RMTDEVICE defined in
the include file portdefs.h.
.TP
.I hfile
the name of the file that holds the ascii header.  The default name is "header."
.TP
.I bfile
the name of the file that holds the binary header.  The default name is "bhed."
.TP
.I trmin
the first trace to write, the default is the first trace in the data file.
.TP
.I trmax
the last trace to write, the default is the the last trace in the data
file (or INT_MAX, the largest admissible int as defined in the include
file, limits.h).
.SH EXAMPLE
.nf
segyhdrs ns=1024
segywrite <sudata
.fi
.SH DIAGNOSTICS
Passes along system call failure messages.
.SH SEE ALSO
segyhdrs(1) segyread(1) conv_float(3su)
.SH AUTHORS
Einar, Jack, Brian, Chris
.SH SOURCE
su/src/segywrite.c
.SH REVISION LEVEL
1.28
