.TH SEGYHDRS 1 SU
.SH NAME
.B segyhdrs \-
Creates ascii and binary header files for use by segywrite in creating an
SEG-Y tape
.SH SYNOPSIS
.nf
segyhdrs ns=
.fi
.SH DESCRIPTION
.I Segyhdrs
creates a 3200 byte ascii file that segywrite(1) converts to the SEG-Y
ebcdic file for the tape header and also creates a 400 byte binary file
for the SEG-Y binary tape header.  The ascii header merely contains
the Center for Wave Phenomena address (other sites should adapt the code
appropriately).  The only fields set in the binary header are the hns
field giving the number of samples on each trace on the tape and the
format field specifying that the tape is in IBM format as per the SEG-Y
standard.  See the include file segy.h for further information about the
binary header.
.SH REQUIRED PARAMETER
.TP 8
.I ns
the number of samples on each trace.
.SH OPTIONAL PARAMETERS
.TP 8
.I hfile
the name of the file to hold the ascii header.  The default name is "header."
.TP
.I bfile
the name of the file to hold the binary header.  The default name is "bhed."
.SH EXAMPLE
.nf
segyhdrs ns=1024
.fi
.SH DIAGNOSTICS
Passes along system call failure messages.
.SH SEE ALSO
segywrite(1) suaddhead(1)
.SH AUTHOR
Jack
.SH SOURCE
su/src/segyhdrs.c
.SH REVISION LEVEL
1.3
