.TH SU3DCHART 1 SU
.SH NAME
.B su3dchart \-
Prepare 3D data for x-midpoint vs. y-midpoint plot
.SH SYNOPSIS
.nf
su3dchart <stdin >stdout
.SH DESCRIPTION
.I Su3dchart
prepares 3D data for x-midpoint vs. y-midpoint plot.
The environment usually contains a shell script, 3dchart, that produces
device independent byte codes for the pen programs.  Thus,
.nf
	3dchart <3d_data | tube
.fi
will usually produce the plot.
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I none
.SH EXAMPLE
.nf
	su3dchart <3d_data | curve symbol=cdot | tube
.fi
is equivalent to the shell command discussed above.
.SH DIAGNOSTICS
System error message if the write fails.
.SH SEE ALSO
3dchart(1) chart(1) suchart(1)
.SH AUTHOR
Shuki
.SH SOURCE
/src/su/su3dchart.c
.SH REVISION LEVEL
1.9
