.TH SUABSHW 1 SU
.SH NAME
.B suabshw \-
Replace a header key word by its absolute value
.SH SYNOPSIS
.nf
suabshw <stdin >stdout key=offset
.SH DESCRIPTION
.I Suabshw
replaces the selected header key by its absolute value.  The default
header word is the offset field.
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I key
A header key word from the segy.h include file.
.SH DIAGNOSTICS
The only error messages that should be seen are
complaints from named subroutines.  The following are defensive
coding messages that indicate coding errors rather than user errors.
.TP 8
.I "can't absval char header word"
Parsed key header word as being of string type (there were none such as of
03/01/88).
.TP 8
.I "unknown type (type)"
External subroutine hdtype returned an unknown data type for the keyword.
.SH SEE ALSO
surec(1) suchw(1)
.SH AUTHOR
Jack
.SH SOURCE
su/src/suabshw.c
.SH REVISION LEVEL
1.20
