.TH SUAGC 1 SU
.SH NAME
.B suagc \-
Automatic gain contral using a Gaussian window
.SH SYNOPSIS
.nf
suagc <stdin >stdout wagc=20
.SH DESCRIPTION
.I Suagc
provides tapered automatic gain control.
For each input data point, a weighted sum of squares of
the data is computed in a symmetric window around the point and
the input value is divided by the square root of that value.
This enhances events which are large relative to the window.
The weights used are Gaussian with peak at the current input data point.
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I wagc
The length of the agc window in samples.
.SH DIAGNOSTICS
Complains if wagc is specified non-positive and also relays messages
from system call errors.
.SH SEE ALSO
sugain(1) doagc(3su)
.SH AUTHOR
Brian
.SH SOURCE
su/src/suagc.c
.SH REVISION LEVEL
1.9
