.TH SUCHART 1 SU
.SH NAME
.B suchart \-
Make stacking chart
.SH SYNOPSIS
.nf
suchart <stdin >stdout key1=sx key2=gx
.SH DESCRIPTION
.I Suchart
prepares data for plotting one header word against another.  For the
default choice of header words the plot is a conventional stacking
chart.  The output is pairs of binary floats.
The environment usually contains a shell script, chart, that produces
device independent byte codes for the pen programs.  Thus,
.nf
	chart <data | tube
.fi
will usually produce the plot.
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I none
.SH EXAMPLES
The command line
.nf
  suchart <data | curve symbol=cdot xlabel=SHOT ylabel=RECEIVER | tube
.fi
is the equivalent of the shell example given above.
.SH DIAGNOSTICS
System error message if the write fails.
.SH SEE ALSO
3dchart(1) su3dchart(1) chart(1)
.SH AUTHOR
Einar, Jack
.SH SOURCE
/src/su/suchart.c
.SH REVISION LEVEL
1.19
