.TH SUDIFF 1 SU
.SH NAME
.B sudiff \-
Compute the difference of two data sets.
.SH SYNOPSIS
.nf
sudiff data1 data2 >stdout
.SH DESCRIPTION
.I Sudiff
computes the difference of the two data sets given by its arguments;
the second data set is subtracted from the first.  Note that the sudiff
syntax differs from the SU standard in that stdin is not used
to pass a data file.  Indeed, since two data sets are required, an exceptional
syntax is forced.
.PP
The shell program, "maxdiff", computes the maximum absolute value
of the difference of two data sets.
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I none
.SH DIAGNOSTICS
Complains and quits if any trace pairs have different lengths.
Warns if trace files have differing numbers of traces.
.SH SEE ALSO
susum(1)
.SH AUTHOR
Shuki, Jack
.SH SOURCE
su/src/sudiff.c, su/shell/maxdiff
.SH REVISION LEVEL
1.7
