.TH SUEDIT 1 SU
.SH NAME
.B suedit \-
Examine segy traces files and edit headers
.SH SYNOPSIS
.nf
suedit <diskfile   (open read only)
suedit diskfile    (open for header modification, if writable)
.SH DESCRIPTION
.I Suedit
allows interactive examination of trace data and trace headers.
If the file name is passed as an argument instead of by the usual
redirection of standard input, then the file is opened with write
permission and modification of header key word values is possible.
.SH MENU
.TP 8
.I number
read in that trace and print nonzero header words
.TP 8
.I <CR>
go to trace one step away (step is initially -1)
.TP 8
.I +
read in next trace (step is set to +1)
.TP 8
.I -
read in previous trace (step is set to -1)
.TP 8
.I dN
advance N traces (step is set to N)
.TP 8
.I %
print some percentiles of the trace data
.TP 8
.I r
print some ranks (rank[j] = jth smallest datum)
.TP 8
.I "p [n1 [n2]]"
tab plot sample n1 to n2 on current trace
.TP 8
.I "g [tr1 tr2]"
wiggle plot (graph) the trace [traces tr1 to tr2]
.TP 8
.I f
wiggle plot the Fourier transform amplitude of the trace
.TP 8
.I "! key=val"
change a value in a field (e.g. ! tracr=101)
.TP 8
.I ?
print help file
.TP 8
.I q
quit
.SH DIAGNOSTICS
.I Suedit
passes along error messages from system call failures.
.TP 8
.I "only one filename argument is allowed"
More than one command line argument was given.
.TP 8
.I "mysterious data type: ..."
This is a defensive programming message indicating a coding error rather than
a user error.
.SH SEE ALSO
suchw(1) sushw(1)
.SH AUTHOR
Einar, Shuki, Stew, Jack
.SH SOURCE
/src/su/suedit.c
.SH REVISION LEVEL
1.28
