.TH SUENV 1 SU
.SH NAME
.B suenv \-
form complex envelope or phase time trace
.SH SYNOPSIS
.nf
suenv <stdin >stdout mode=amp
.SH DESCRIPTION
.I Suenv
computes the complex envelope or phase time trace.
The envelope trace is defined as the
magnitude of the complex trace consisting of real part equal to the
original trace, imaginary part equal to the Hilbert transform of the
trace.  Similarly the phase trace is the
phase of the complex trace.  The algorithm used is given by 
.sp
.nf
out(t) = cabs ([ INVERSE_FFT {2 * step(omega)*FFT(in(t))} ])
.SH PARAMETERS
.TP 8
.I mode
An output flag to specify whether envelope or phase traces are
desired.  The value, amp, is the default and specifies envelope
traces.  The value, phase, selects phase traces.
.SH DIAGNOSTICS
.TP 8
.I "Padded nt=... -- too big"
After padding, the data trace was too long (as defined by SY_NDAT in
segy.h).
.PP
Also complains and quits if input data is marked as other than seismic
data in the trid field or if an unknown mode.
Also relays messages from system call errors.
.SH SEE ALSO
suhilb(1)
.SH AUTHOR
Jack
.SH SOURCE
su/src/suenv.c
.SH REVISION LEVEL
1.4
