.TH SUHILB 1 SU
.SH NAME
.B suhilb \-
Hilbert transform computed by FFT
.SH SYNOPSIS
.nf
suhilb <stdin >stdout
.SH DESCRIPTION
.I Suhilb
computes the trace by trace Hilbert transform using the algorithm:
.sp
.nf
out(t) = Im [ INVERSE_FFT {sgn(frequency)*FFT(in(t))} ]
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I none
.SH DIAGNOSTICS
.TP 8
.I "Padded nt=... -- too big"
After padding, the data trace was too long (as defined by SY_NDAT in
segy.h).
.PP
Also complains and quits if input data is marked as other than seismic
data in the trid field and relays messages from system call errors.
.SH SEE ALSO
sufft(1)
.SH AUTHOR
Jack
.SH SOURCE
su/src/suhilb.c
.SH REVISION LEVEL
1.4
