.TH SUIFFT 1 SU
.SH NAME
.B suifft \-
Inverse Fast Fourier transform frequency to time
.SH SYNOPSIS
.nf
suifft <stdin >stdout sign=-1
.SH DESCRIPTION
.I Sufft
performs an fft assuming that the input is "packed" frequency traces as
produced by sufft(1).
The output traces are normalized by 1/N where N is the fft size.
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I sign
The sign parameter specifies the sign in the exponent of the transform.
By default it is -1 (opposite to the default of sufft),
it may be specified as 1.
.SH DIAGNOSTICS
Complains and quits if input data is marked as not being packed traces
in the trid field.  Also relays messages from system call
errors.
.TP 8
.I "Padded nt=... -- too big"
After increasing the number of samples to a size the mixed radix
transform can handle efficiently, the trace length exceeded the maximum
allowable value, SY_NDAT, as defined in segy.h.
.TP 8
.I "sign = ... must be 1 or -1"
An illegal sign value was typed on the command line.
.SH CAVEAT
The code is complicated by use of a complex fft.  To compensate, it
packs two transforms together.  It would be better to develop and use a
comparable mixed radix real transform.
.SH SEE ALSO
suamp(1) sufft(1) sufft2d(1)
.SH AUTHOR
Jack
.SH SOURCE
su/src/suifft.c
.SH REVISION LEVEL
1.8
