.TH SUMAX 1 SU
.SH NAME
.B sumax \-
get trace by trace and global maximum magnitude and their indices
.SH SYNOPSIS
.nf
sumax <stdin >stdout [optional parameters]
.SH DESCRIPTION
Under the binary output option (see below), the maximum magnitude on each
trace is written.  Under the ascii option, the global maximum magnitude
is printed and with the verbose flag on, the trace by trace maximum
magnitudes are also printed as are the location indices of both the
global and trace maxima.
.SH REQUIRED PARAMETERS
.TP 8
.I none
.SH OPTIONAL PARAMETERS
.TP 8
.I output
Legal values of the output parameter are: \fIascii\fP (the default if
standard output is a tty or pipe), and \fIbinary\fP (the default if
standard output is a disk or tape file).  The parameter, \fIoutput\fP
can be used to over ride the defaults.
.TP
.I verbose
This option is recognized only if the output is set as ascii.
The default is 0 (off), if 1 is selected, then the
location indices and trace by trace maximum
amplitudes are printed in addition to the global maximum amplitude.
.SH DIAGNOSTICS
Complains and quits if standard output is a directory or other anomolous
type; likewise if illegal strings are provided for the parameters.
Also relays messages from system call errors.
.SH SEE ALSO
surange(1)
.SH AUTHOR
Shuki, Jack
.SH SOURCE
su/src/sumax.c
.SH REVISION LEVEL
1.20
