.TH SUMUTE 1 SU
.SH NAME
.B sumute \-
mute large offsets up shallow
.SH SYNOPSIS
.nf
sumute <stdin >stdout v= alpha=1 nmute=0
.SH DESCRIPTION
Mutes the shallow far offset data.
.I Sumute
relies on the trace header fields, dt and offset being set.
.SH REQUIRED PARAMETER
.TP 8
.I v
the velocity.
.SH OPTIONAL PARAMETERS
.TP 8
.I alpha
gives the offset-time ratios to mute according to the relation:
.sp
.nf
offset/v < alpha * time.
.fi
.sp
Alpha is positive and has default value 1.
.TP
.I nmute
gives an alternate way to specify the mute and, if
specified, overrides the alpha value.  It directly
gives the number of points to mute.
.SH DIAGNOSTICS
Complains and quits if v is not specified or any of v or alpha
are specified non-positive or nmute as negative.
Also relays messages from system call errors.
.SH SEE ALSO
suus(1) suwind(1)
.SH AUTHOR
Shuki, Jack
.SH SOURCE
su/src/sumute.c
.SH REVISION LEVEL
1.13
