.TH SURANGE 1 SU
.SH NAME
.B surange \-
print ranges of all nonzero SEG-Y header fields
.SH SYNOPSIS
.nf
#include "../include/cwp.h"
#include "../include/segy.h"
#include "../include/hdr.h"
#include <signal.h>

surange <segydata
.SH DESCRIPTION
.I Surange
scans all SEG-Y header fields defined in segy.h
for nonzero values.  At the end of the scan it prints out min
and max values for these fields.  On a keyboard interrupt, the
partial results accumulated up to that time will be displayed.
.SH SEE ALSO
suedit(1) sugethw(1)
.SH AUTHOR
Stew, Jack
.SH REVISION LEVEL
1.25
