.TH SUSHW 1 SU
.SH NAME
.B sushw \-
set header word using trace number, mod and div
.SH SYNOPSIS
.nf
sushw <stdin >stdout key=cdp a=0 b=0 c=0 d=0 j=1
.SH DESCRIPTION
.I Sushw
computes the value of the header word key1 using the formulas:
.nf
	i = itr + d
.sp
	val(key) = a + b * (i % j) + c * (i / j)
.fi
.sp
Here itr is the zero-based trace number
(i.e., the first trace has itr=0, not 1).
.SH PARAMETERS
.TP 8
.I key
The header key word to set (default "cdp").
.TP
.I "a, b, c, d, j"
Arithmetic coefficients defined by the formulas in the above DESCRIPTION.
.SH EXAMPLE
.nf
sushw key1=tracr key2=tracr a=1000 <infile >outfile
sushw <indata key=dt a=4000 |
sushw key=sx a=6400 c=-100 j=32 |
sushw key=offset a=200 b=200 j=32 >outdata
.fi
.sp
In this example, we set every dt field to 4ms.  Then we set the
first 32 shotpoint fields to 6400, the second 32 shotpoint fields
to 6300 and so forth.  Next we set each group of 32 offset fields to 
200, 400, ..., 6400.
.SH DIAGNOSTICS
The following defensive error messages indicate coding errors:
.TP 8
.I "can't change char header word"
An internal subroutine classified the header data type as a char* (there
were none such as of 03/12/88).
.TP 8
.I "unknown type ..."
The data type returned by the internal subroutine was not a valid type.
.SH SEE ALSO
suchw(1), suaddhead(1)
.SH AUTHOR
Einar, Jack
.SH SOURCE
su/src/sushw.c
.SH REVISION LEVEL
1.24
