.ds SY \s-2\f(sRSEG-Y\fP\s0
.TH SUUNPACK2 1 SU
.SH NAME
.B suunpack2 \-
unpack SEGY trace data from shorts to floats
.SH SYNOPSIS
.nf
suunpack2 <packed_file >unpacked_file
.SH DESCRIPTION
This is the (approximate) inverse to supack2(1).
Local \*(SY fields are used to store the power
parameter needed to restore the dynamic range (ungpow) and to
undo the scaling associated with limiting the data to
the levels attainable with a char (unscale).
.SH DEFINES
.TP 8
SHORTPACK
SEGY trid field value to indicate short data (102)
.SH EXAMPLE
.nf
suunpack2 <packed_data | sunmo | sudecon | supack2 >packed_data
.fi
.sp
Here we avoid making a large disk file by using a file
previously packed with supack2.
.SH SEE ALSO
supack2(1) suunpack1(1) supack1(1) segyread(1) gettr(3) puttr(3)
.SH AUTHOR
Jack
.SH REVISION LEVEL
1.20
