.ds SY \s-2\f(sRSEG-Y\fP\s0
.TH SUUNPACK1 1 SU
.SH NAME
.B suunpack1 \-
unpack SEGY trace data from chars to floats
.SH SYNOPSIS
.nf
suunpack1 <packed_file >unpacked_file
.SH DESCRIPTION
This is the (approximate) inverse to supack1(1).
Local \*(SY fields are used to store the power
parameter needed to restore the dynamic range (ungpow) and to
undo the scaling associated with limiting the data to
the levels attainable with a char (unscale).
.SH DEFINES
.TP 8
CHARPACK
SEGY trid field value to indicate char data (101)
.SH EXAMPLE
.nf
suunpack1 <packed_data | sunmo | sudecon | supack1 >packed_data
.fi
.sp
Here we avoid making a large disk file by using a file
previously packed with supack1.
.SH SEE ALSO
supack1(1) suunpack2(1) supack2(1) segyread(1) gettr(3) puttr(3)
.SH AUTHOR
Jack
.SH REVISION LEVEL
1.15
