.TH SUUS 1 SU
.SH NAME
.B suus \-
under sample traces
.SH SYNOPSIS
.nf
#include "../include/cwp.h"
#include "../include/segy.h"
#include "../include/hdr.h"

suus <stdin >stdout j=2 s=0
.SH DESCRIPTION
.I Suus
produces a file with a sub sampling of the time samples in the input
file.
.SH PARAMETERS
.TP 8
.I j 
Select every jth time sample; the default is 2.
.TP
.I s
First sample to select; the default is 0.
.SH EXAMPLE
.nf
	suus <INFILE >OUTFILE
.fi
.sp
Every other time sample is selected and placed in "OUTFILE."
.SH DIAGNOSTICS
Self explanatory except
.sp
.I "s=..., should be < ..."
.sp
which is an objection to an attempt to subsample with a value
greater than the number of samples on the trace (probably due to
a typo).
.SH SEE ALSO
suwind(1)
.SH AUTHOR
Shuki, Jack
.SH REVISION LEVEL
1.17
