#!/bin/sh

File='Makefile'
extra="a2i avph segm smooth1 taperead/sfio/main"

names=`ls -d su*`
all=$names" "$extra



cat > $File << END
MAKE=make
include Makefile.conf
all:
END

echo '	cd ./sulib; $(MAKE)' >> $File

for pr in $all
do

	if [ -f $pr'/Makefile' ]
	then
		echo '	cd ./'$pr'; $(MAKE)' >> $File
	fi
done

cat >> $File << END1


clean:
END1

for pr in $all
do

	echo '	cd ./'$pr'; rm -f *.o' >> $File 
done


