SHELL = /bin/sh
.SUFFIXES:
.SUFFIXES: .c .o


CWPDIR = $(CWPROOT)
L=$(CWPDIR)/lib
ML=$(HOME)/prog/lib
UL=/usr/lib64

MPI_compile=$(shell mpicc -showme:compile)
MPI_lib=$(shell mpicc -showme:link)

EXEDIR =$(HOME)/prog/bin/



CFLAGS = -c -O3 -m64
CC = gcc 
D = $L/libcwp.a $L/libpar.a $L/libsu.a
LIBS =  -L$(UL) -L$(ML) -L$(L) -lsulib -lsu -lpar -lcwp -lpthread -lm $(MPI_lib)
INC = -I$(CWPDIR)/include -I../include $(MPI_compile)

MCHMODLINE = chmod 775 $@

