MAKE=make
include Makefile.conf
all:
	cd ./sulib; $(MAKE)
	cd ./su2d2dsf; $(MAKE)
	cd ./su2voxet; $(MAKE)
	cd ./su3d2par; $(MAKE)
	cd ./su3dbin; $(MAKE)
	cd ./su3dint; $(MAKE)
	cd ./su3dkmig; $(MAKE)
	cd ./su3dmigpspi_mpi; $(MAKE)
	cd ./su3dstkfmix; $(MAKE)
	cd ./subins; $(MAKE)
	cd ./succf; $(MAKE)
	cd ./sucepstrum; $(MAKE)
	cd ./sucoordtr; $(MAKE)
	cd ./sucspg_prep; $(MAKE)
	cd ./sudebias; $(MAKE)
	cd ./sudiff3d; $(MAKE)
	cd ./sudummy; $(MAKE)
	cd ./sufagc; $(MAKE)
	cd ./sufbfpick; $(MAKE)
	cd ./sufbpick; $(MAKE)
	cd ./sufltn; $(MAKE)
	cd ./sufnmo; $(MAKE)
	cd ./sufwatrim; $(MAKE)
	cd ./sufwmix; $(MAKE)
	cd ./sugetgthr; $(MAKE)
	cd ./sugprfb; $(MAKE)
	cd ./sugprscl; $(MAKE)
	cd ./sukill_trid; $(MAKE)
	cd ./suknmo; $(MAKE)
	cd ./suknmo3d; $(MAKE)
	cd ./suldhdr; $(MAKE)
	cd ./sulfaf; $(MAKE)
	cd ./sulib; $(MAKE)
	cd ./sumcspg; $(MAKE)
	cd ./suminph; $(MAKE)
	cd ./suminphdec; $(MAKE)
	cd ./sumsp; $(MAKE)
	cd ./sunanf; $(MAKE)
	cd ./suND; $(MAKE)
	cd ./suoffazi; $(MAKE)
	cd ./supatsr; $(MAKE)
	cd ./suphs; $(MAKE)
	cd ./supid; $(MAKE)
	cd ./suprg; $(MAKE)
	cd ./suputgthr; $(MAKE)
	cd ./suresstat2; $(MAKE)
	cd ./suscd5m; $(MAKE)
	cd ./sushstk; $(MAKE)
	cd ./sushwm; $(MAKE)
	cd ./suslice; $(MAKE)
	cd ./suslice_hdrw; $(MAKE)
	cd ./suslstk; $(MAKE)
	cd ./susnmo3d; $(MAKE)
	cd ./susnnorm; $(MAKE)
	cd ./suspwhg; $(MAKE)
	cd ./susvd; $(MAKE)
	cd ./sutkfilt; $(MAKE)
	cd ./sutrcount; $(MAKE)
	cd ./sutredd; $(MAKE)
	cd ./sutrimst; $(MAKE)
	cd ./sutscale; $(MAKE)
	cd ./suvpar2tr; $(MAKE)
	cd ./suvstak; $(MAKE)
	cd ./suwavelet; $(MAKE)
	cd ./a2i; $(MAKE)
	cd ./smooth1; $(MAKE)
	cd ./taperead/sfio/main; $(MAKE)


clean:
	cd ./su2d2dsf; rm -f *.o
	cd ./su2voxet; rm -f *.o
	cd ./su3d2par; rm -f *.o
	cd ./su3dbin; rm -f *.o
	cd ./su3dint; rm -f *.o
	cd ./su3dkmig; rm -f *.o
	cd ./su3dmigpspi_mpi; rm -f *.o
	cd ./su3dstkfmix; rm -f *.o
	cd ./subins; rm -f *.o
	cd ./succf; rm -f *.o
	cd ./sucepstrum; rm -f *.o
	cd ./sucoordtr; rm -f *.o
	cd ./sucspg_prep; rm -f *.o
	cd ./sudebias; rm -f *.o
	cd ./sudiff3d; rm -f *.o
	cd ./sudummy; rm -f *.o
	cd ./sufagc; rm -f *.o
	cd ./sufbfpick; rm -f *.o
	cd ./sufbpick; rm -f *.o
	cd ./sufltn; rm -f *.o
	cd ./sufnmo; rm -f *.o
	cd ./sufwatrim; rm -f *.o
	cd ./sufwmix; rm -f *.o
	cd ./sugetgthr; rm -f *.o
	cd ./sugprfb; rm -f *.o
	cd ./sugprscl; rm -f *.o
	cd ./sukill_trid; rm -f *.o
	cd ./suknmo3d; rm -f *.o
	cd ./suldhdr; rm -f *.o
	cd ./sulfaf; rm -f *.o
	cd ./sulib; rm -f *.o
	cd ./sumcspg; rm -f *.o
	cd ./suminph; rm -f *.o
	cd ./suminphdec; rm -f *.o
	cd ./sumsp; rm -f *.o
	cd ./sunanf; rm -f *.o
	cd ./suND; rm -f *.o
	cd ./suoffazi; rm -f *.o
	cd ./supatsr; rm -f *.o
	cd ./suphs; rm -f *.o
	cd ./supid; rm -f *.o
	cd ./suprg; rm -f *.o
	cd ./suputgthr; rm -f *.o
	cd ./suresstat2; rm -f *.o
	cd ./suscd5m; rm -f *.o
	cd ./sushstk; rm -f *.o
	cd ./sushwm; rm -f *.o
	cd ./suslice; rm -f *.o
	cd ./suslice_hdrw; rm -f *.o
	cd ./suslstk; rm -f *.o
	cd ./susnmo3d; rm -f *.o
	cd ./susnnorm; rm -f *.o
	cd ./suspwhg; rm -f *.o
	cd ./susvd; rm -f *.o
	cd ./sutkfilt; rm -f *.o
	cd ./sutrcount; rm -f *.o
	cd ./sutredd; rm -f *.o
	cd ./sutrimst; rm -f *.o
	cd ./sutscale; rm -f *.o
	cd ./suvpar2tr; rm -f *.o
	cd ./suvstak; rm -f *.o
	cd ./suwavelet; rm -f *.o
	cd ./a2i; rm -f *.o
	cd ./avph; rm -f *.o
	cd ./segm; rm -f *.o
	cd ./smooth1; rm -f *.o
	cd ./taperead/sfio/main; rm -f *.o
