#!/bin/sh

# To convert ascii file headers to binary data

indir='../../geom/ascii_headers/'
outdir='../../geom/bin_headers/'

# Number of columns 11
# F sp rc spx spy spz rcx rcy rcz offset azimuth(0-180)
nc=11

for file in `ls $indir`
do
        echo $file
        a2b < $indir$file n1=$nc > $outdir$file
done

