#! /bin/sh
# Load header values from binary files to the su datafiles
# Using SU routine sushw
inhdir="/data/bin_headers/"
insdir="/bigdata/s_gathers_tmp/"
outdir="/bigdata/s_gathers_tmp/"

for file in `ls $insdir*'.su' `
do
        echo $inhdir`basename $file .su `
        echo $file
        echo $outdir`basename $file su `'fhsu'
        sushw < $file \
        key=fldr,ep,sdepth,sx,sy,selev,swdep,gwdep,gelev,offset,otrav \
        infile=$inhdir`basename $file .su ` |
        sushw key=scalel,scalco,counit a=-1,-1,-1 \
        > $outdir`basename $file su `'fhsu'
#	rm $file
done

# offset is converted from dm to m
# Header assignments
# field record #        ->      fldr
# shot point #          ->      ep
# receiver point #      ->      sdepth
# receiver x coord      ->      swdep
# receiver y coord      ->      gwdep
# receiver Z elev       ->      gelev
# shot x coord          ->      sx
# shot y coord          ->      sy
# shot z elev           ->      selev
# offset                ->      offset
# azimuth		->      otrav
# multiplier for gelev selev sdepth gdel sdel swdep gwdep is in scalel
# scalel                ->      -1
# multiplier for sx, sy, gx, gy in scaleco
# scaleco               ->      -1
# counit                ->      1
