#!/bin/sh
# 
sd2='/mnt/data2/seis/Ssx3d'
sg=$sd2'/shot_gathers'
tmp=$sd2'/tmp'
dcdir='./scd'
 
 
	sugetgthr dir=$sg   vt=1 ns=2100		 \
		  verbose=0				 |
       sudummy  				       |
       suwind key=trid reject=3 		       |
       suwind key=sdepth reject=`cat reject_rcv.txt`   \
       verbose=0				       |
       supr_g c="sugain apbal=1 panel=1" key=fldr      |
 #     Despike
       sumedian1 fl=3 w=1,1,1			       |
 #     Limit Offsets			       |
       suwind key=offset min=50 max=1500 tmax=2.0      |
 #     Cdp and gx gy assigned        
	 su3dbin ny=123 nx=119 dirx=-1 diry=-1  	\
		 dbx=25 dby=20 xc=314510 yc=5072748	\
		 deg=-12.86				|
 # Gain recovery
       sugain tpow=2.0  			       	|
 #	 Surface consisten decon
	 suscd5_m1  verbose=0 \
		fmin=0 fmax=150 fftpad=50.0	       	\
		smt=4.0 			       	\
		  ts=0.1,1.08				\
		  te=2.0,2.0				\
		  o=0.0,1500				\
		  hb=5 zb=5			     	\
		  vmin=400 vmax=1570		      	\
		  atmin=0.3 atmax=1.3		       
       
	suscd5_m2 nit=7 sm2=15 	    \
	fns=$dcdir'/s.lgs' fng=$dcdir'/g.lgs'         	\
	fnh=$dcdir'/h.lgs' fny=$dcdir'/y.lgs'         	\
	fnz=$dcdir'/z.lgs' fna=$dcdir'/a.lgs'         	\
	> $dcdir'/da.lgs'
