#!/bin/sh

sd='/mnt/sdata/Ssx'
sg=$sd'/shot_gathers'
outg=$sd'/proc_gathers'
tmp=$sd'/tmp'
dcdir='./scd'
vtm=$sd2'/tomovel/tomo_vel_sm.su'


       sugetgthr dir=$sg   vt=1 ns=2100                 \
                 verbose=0                              |
	sudummy						|
	suwind key=trid reject=3			|
	suwind key=sdepth reject=`cat reject_rcv.txt`   \
	verbose=0					|
	supr_g c="sugain apbal=1 panel=1" key=fldr	|
#      Despike
        sumedian1 fl=3 w=1,1,1                          |
#	sufilter f=3,8 amps=0,1			        |
 	suwind key=offset min=50 max=1500 tmax=2.0		|
#       Cdp and gx gy assigned        
        su3dbin ny=123 nx=119 dirx=-1 diry=-1           \
                dbx=25 dby=20 xc=314510 yc=5072748      \
                deg=-12.86                              |
#	Put receiver line number from tracl to duse
	suchw key2=sdepth key1=duse d=1000              |
#	Fix coordinate elevation scaler		
	sushw key=scalel a=-2		                |
# 	Divergence correction
	  sugain tpow=2.0 				|
#       Surface consisten decon
        suapscd5_m fnl=0 fmin=0 fmax=150 \
                   fftpad=50.0 \
                   ltpr=3 htpr=7 prw=0.1 \
                   s=1  g=1  h=1  y=0  z=1   \
                   sp=1 gp=1 hp=0 yp=0 zp=0 \
                   a=1 ap=1 \
		   res=0  smt=6  \
                   hb=5 zb=5       \
		   time=1 oplen=0.080 \
                 fns=$dcdir'/s.lgs' fng=$dcdir'/g.lgs'    \
                 fnh=$dcdir'/h.lgs' fny=$dcdir'/y.lgs'    \
                 fnz=$dcdir'/z.lgs' fna=$dcdir'/a.lgs'    |
	# Spectral whitening
	suspwhtwg_f key=ep fmin=0 fmax=150 fwind=10 ftape=5  \
		sm1=0 sm2=0				 \
		rescl=1                                  \
		logrescl=0	prw=1			 \
		verbose=0  				 \
		wagc=0.400 envf=0			 |
        subfilt fstoplo=3 fpasslo=7                    \
                fpasshi=90 fstophi=130 zerophase=1      |
	suputgthr_sort  key=ep dir=$outg  

