#!/bin/sh

# Processing Residual static
#
#
sd2='/mnt/data2/seis/Ssx3d'
sg=$sd2'/shot_gathers'
outg=$sd2'/proc_gathers'
cdpg=$sd2'/cdp_gathers'
tmp=$sd2'/tmp'
dcdir='./scd'
rs=$sd2'/rs'

if [ -z $1 ]
then
	echo 'Creating new window file'
	echo 'Got 10 seconds to interrupt'
	sleep 10

	sugetgthr dir=$cdpg vt=1 ns=2001 |
	# Nmo
	suwind key=offset min=100 max=900 |
	suresamp nt=1001 dt=0.002	 |
	sumute tmute=0.1,0.72 xmute=0.0,1000   ntaper=0 |
	sufnmo  f=$sd2'/velan/sm_int_v_functions_nn.fnmo' \
		fac=1.0 sscale=0 smute=1.2 lmute=0 |
	# Window out what we need for the statics
        subfilt fstoplo=10 fpasslo=25                    \
                fpasshi=70 fstophi=90 zerophase=1      |
	suwind tmin=0.50 tmax=1.45                     |
	sugain pbal=1				       |
	suwind key=trid reject=2,3	\
	> $rs'/stat_wind.su'
fi

# Residual static correction
	suresstat_tr_f fn=$rs'/stat_wind.su' \
	maxshft=0.016 maxeshft=0.10 cns=0 ffa=1 tx=.120 it=7 sm=0 smw=0 bc=0 
