#!/bin/sh


seis='/mnt/sdata/Ssx'
cg=$seis'/cdp_gathers'
sg=$seis'/proc_gathers'
stk=$seis'/stak/stk_trm.su'
dcdir='./scd'
# Residual Static files
stdir=$seis'/rs/'
strv='rv-v4afx4d.st-40'
stsh='sh-v4afx4d.st-40'


	sugetgthr dir=$cg   vt=1  ns=2001    |
	suapstat_f st=$stdir$stsh rt=$stdir$strv maxshft=0.080|
	sufnmo f=$seis'/velan/sm_int_v_functions_nn.su' \
		fac=1.0 sscale=1 smute=1.2 |
	sumute tmute=0.0,0.2,0.33,0.5,00.9 \
	       xmute=0.0,250,500.,680,1500 \
	       ntaper=5                                        |
# Trim statics within the cdp gather
	supr_g key=cdp \
		c='sutrimst tmin=0.4 tmax=1.6 maxshft=0.010'   |
#stack
	suvstak_smp_rgf nx=119 ny=123 cc=0 \
                xc=314510 yc=5072748 dbx=25 dby=20 \
                deg=-12.86 dirx=-1 diry=-1 \
		sm=0 \
		osmp=3  nnz=1 fvtname=$seis"/velan/averms_vel.txt" \
		fmin=5 fmax=90 fwind=5 fac=4.0 ts=0 \
		verbose=1                           \
		tmpdir='/mnt/sdata/tmp' \
		> $stk
		
