#!/bin/sh
       
data='/mnt/sdata/Ssx/'	
stack=$data'/stak/stk_trm.su'
stack_mp=$data'/stak/stk_mp.stk'
velf=$data'/velan/sm_int_v_functions_nn.su'
velf_mp=$data'/velan/sm_int_v_functions_nn_mig.su'
kmig=$data'/mig/ssx_d30_v100_i4_nr.kmig'


# Prepare the files for migration
# Sort them to the same order
	susort < $velf cdp > $velf_mp
	susort < $stack cdp ep |
	sudummy                |

	# Frequency domain FXY noise reduction 
	su3dstkfmix n2=119 n3=123 d3=2 d2=2 |
	subfilt fstoplo=3.0 fspasslo=12.0 \
		fpasshi=80 fstophi=110   |
	sunormalize t0=0.4 t1=1.6 |
	sudummy zero=1            > $stack_mp	
	
	su3dkmig fs=$stack_mp fv=$velf_mp \
                 n2=123 n3=119 d2=20 d3=25 apr=75 \
                 facs=1.0 face=1.00 sphr=1 verbose=1 itp=0 dm=20 \
		 > $kmig
	
	rm $stack_mp
	rm $velf_mp
