#!/bin/sh

infile='/mnt/idata/Ssx/proc_shots.su'
outfile='/mnt/sdata/Ssx/FX4D_mix.su'
npipe='tmp_pipe'

hf='ep_sx_ep_sy_rp_rx_rp_ry_seq.txt'
cf='ep_ep_rp_rp_seq.txt'

# Create tables for 4D selection

if [ -p $npipe ]
then
	rm $npipe
fi
        mkfifo $npipe
        sushw < 1.su \
                key=ntr a=0 b=1 |
        tee $npipe              |
        sugethw key=ep,ep,sdepth,sdepth,ntr \
                 output=geom  \
        > $cf &

        sugethw  <$npipe              \
                 key=ep,sx,ep,sy,sdepth,swdep,sdepth,gwdep,ntr \
                output=geom  \
        > $hf

        rm $npipe

# Start filtering
	
	suND nd=4 \
	     df=$infile hf=$hf cf=$cf \
	     pr=1500,1500,1500,1500  \
	     key=sx,sy,swdep,gwdep  |
#	sufwatrim keyg=gaps p=15      \
#	        key=sx,sy,swdep,gwdep \
#		dx=10,10,10,10        \
#	> $outfile
	sufwmix keyg=gaps key=sx,sy,swdep,gwde \
	        key=sx,sy,swdep,gwdep \
		dx=10,10,10,10        \
		vmin=8000 vf=1	      \
	> $outfile
#	suradon2 key=gaps vmin=1000 dp=0.00001 igopt=3 |
#	suwind key=mark min=1 max=1 \
