/*
help object
called for command line selfdoc or
portions for menu help
*/
#include <stdio.h>

char    *help = "\n\
cmovie - display cubic array of data in XWindows-Motif\n\
\n\
USAGE: cmovie in=datafile [ data pars ] [ display pars ]\n\
\n\
DATA ARGUMENTS:\n\
in=datafile                             vgrid format\n\
                                        bytes or float with header\n\
in=datafile n1= n2= n3= segy=1          segy/SU format\n\
                                        float traces with headers\n\
in=datafile n1= n2= n3=                 bytes format (SEPlib)\n\
                                        byte array without header\n\
in=datafile n1= n2= n3= esize=4         float format\n\
                                        float array without header\n\
\n\
DATA PARAMETERS:\n\
par=\"\"                        name of parameter file\n\
in=\"stdin\"            name of input file\n\
n1= n2= n3= n4=1 n5=1   length of three dimensions, n1 is fastest, e.g. time\n\
o1=0, o2=0 ...          first sample value in each dimension\n\
d1=1 d2=1 ...           sample increment in each dimension\n\
z1=1 z2=1 ...           relative spacing for true size, z3=3 means wide lines\n\
label1=\"n1\" ...               label for each dimension\n\
title=in                dataset title\n\
script=\"\"             script file with label for every panel (n3 dimension)\n\
segy=0                  data format is segy or not\n\
vgrid=                  specify vgrid choice\n\
esize=1                 data samples are =1 for bytes or =4 for floats\n\
hbytes=0,3600           header bytes to skip; 3600 for segy=1\n\
pclip=255               positive clip value; high= and clip= are synonyms\n\
nclip=1                 negative clip value; low= and clip= are synonyms\n\
value=\"sample\"        name for values on colorbar\n\
\n\
DISPLAY PARAMETERS:\n\
width=600 height=600    pixel dimension (> 64) or fraction of screen (<= 1.0)\n\
pick=\"\"               pick line data file\n\
npick=300000            maximum number of picks (may be made arbitrarily large)\n\
pickrange=1             number of adjacent lines overwhich pick is visible \n\
picksize=2              size of pick symbol (2 is minimum)\n\
style=\"cube\"          view is front, side, top, plan, array, picks, cube, fence, or transparent\n\
orient=\"front\"                orient is front, side, top\n\
origin=\"minimum\"              frames set to middle or minimum\n\
transp=0                if 1, transpose down and across\n\
shape=\"fit\"           shape fits screen, true, or pixel\n\
movie=\"off\"           run movie in up, down, left, right, in, or out direction\n\
color=\"gray\"          color is gray, straw, flag, tiger, blue, or rainbow\n\
contrast=\"50\"         contrast is between 0 and 100\n\
font=                   alternative XWindows font; default bold-courier-20\n\
\n\
FILE FORMATS:\n\
seplib, bytes input data set: (user supplied)\n\
        2-D of 3-D array of unsigned byte integers 0-255.\n\
        Use segy2movie to convert segy.\n\
        Use Byte to convert seplib floating point.\n\
seplib, float input data set: (user supplied)\n\
        2-D of 3-D array of float numbers\n\
segy, su input data set: (user supplied)\n\
        Two dataset headers.\n\
        n2 x n3 segy traces.\n\
        Each trace 240 bytes + n1 IEEE floating point samples.\n\
        Use suread to convert tape dataset.\n\
vgrid, (read or written by cmovie).\n\
        cubic array of data.\n\
        100 byte tail describing dimensions.\n\
script file: (user supplied)\n\
        Text file.\n\
        Each line of text annotates an n3 direction frame.\n\
pick file: (generated by program or user supplied)\n\
        First line is dataset name.\n\
        Second line is dataset dimensions.\n\
        Third line are axes labels.\n\
        Followed by pick-lines:\n\
                First line is ID and frame.\n\
                Following lines are pick points:\n\
                        three coordinates and data value.\n\
par file: (user supplied or generated by Save State menu)\n\
        List of parameters in name=value form. Free format.\n\
        Last of duplicates used.\n\
\n\
WINDOWS:\n\
(1) Menubar on top.\n\
(2) Message window below menubar.\n\
(3) Control panel below message window.\n\
(4) Color spectrum below control panel.\n\
    Line shows relative data sample distribution.\n\
    Bar shows last pick value or range of values.\n\
    Mouse click-drag-up specifies a value range.\n\
(5) Resizable image window.  Responds to following mouse clicks:\n\
\n\
MOUSE USAGE:\n\
LEFT: zoom; MIDDLE: navigate; RIGHT: pick.\n\
LEFT click-drag-up: zoom window.\n\
LEFT click-drag-up + 'h' key: zoom horizontal only.\n\
LEFT click-drag-up + 'v' key: zoom vertical only.\n\
LEFT click-drag-up in ARRAY window: those panels.\n\
MIDDLE click: select cross frames.\n\
MIDDLE click-drag-up: select an animation range.\n\
RIGHT click: pick a point on the image.\n\
RIGHT click + 'a' key: add a point to end of pick line.\n\
RIGHT click + 'm' key: move nearest point in pick line.\n\
RIGHT click + 'd' key: delete nearest point in pick line.\n\
RIGHT click-drag-up + 's' key: select seed point and sub-volume pick bounds.\n\
COLORBAR ANY click-drag-up: replace sub-volume range with this new range.\n\
\n\
INTERACTIVE CONTROLS:\n\
MAIN FUNCTIONS: Interface to system\n\
        \"Main\"        \"Redraw\" -- refresh damaged screen\n\
        \"Main\"        \"Write vgrid file (floats)\" -- save data files as floats in seplib/vgrid format\n\
        \"Main\"        \"Write vgrid file (bytes)\" -- save data files as bytes in seplib/vgrid format\n\
        \"Main\"        \"Write parameter restart file\" -- create a parameter restart file\n\
        \"Main\"        \"Debug\" -- dump various arrays for programmer debugging\n\
        \"Main\"        \"Quit\"\n\
STYLE FUNCTIONS: Select a style and set attributes\n\
        \"Style\"       \"Front (2D)\" -- Front face of data cube\n\
        \"Style\"       \"Side (2D)\" -- Side face of data cube\n\
        \"Style\"       \"Top (2D)\" -- Top face of data cube\n\
        \"Style\"       \"Plan (2D)\" -- All three cube faces\n\
        \"Style\"       \"Array (3D) ...\" -- Array of front faces- up to a hundred\n\
        \"Style\"       \"Pick (3D) ...\" -- Array of picked faces\n\
        \"Style\"       \"Cube (3D)\" -- Cube view\n\
        \"Style\"       \"Fence (3D) ...\" -- Show intersecting faces\n\
        \"Style\"       \"Transparent (3D) ...\" -- Transparent volume\n\
        \"Array Panel\" \"Direction\" <four axes> -- Select through direction\n\
        \"Array Panel\" \"Down\" -- Panels in down direction\n\
        \"Array Panel\" \"Across\" -- Panels in across direction\n\
        \"Array Panel\" \"Start\" -- First panel\n\
        \"Array Panel\" \"Delta\" -- Panel increment\n\
        \"Array Panel\" \"End\" -- Last panel; sets delta\n\
        \"Array Panel\" \"Draw\" -- Draw with new parameters\n\
        \"Array Panel\" \"Close\" -- Close control panel\n\
        \"Array Panel\" \"LEFT MOUSE SELECTS PANEL RANGE\n\
        \"Fence Panel\" \"Toggle Front\" -- Toggle front plane on\n\
        \"Fence Panel\" \"Toggle Side\" -- Toggle side plane on\n\
        \"Fence Panel\" \"Toggle Top\" -- Toggle top plane on\n\
        \"Fence Panel\" \"Transparency\" -- Set transparency threshhold\n\
        \"Fence Panel\" \"Draw\" -- Draw with new parameters\n\
        \"Fence Panel\" \"Close\" -- Close control panel\n\
        \"Transparency Panel\"  \"Min\" -- Set minimum transparency value\n\
        \"Transparency Panel\"  \"Max\" -- Set maximum transparency value\n\
        \"Transparency Panel\"  \"Transp\" -- Set transparency value\n\
        \"Transparency Panel\"  \"Draw altogether\" -- Update screen once\n\
        \"Transparency Panel\"  \"Draw tenth blocks\" -- Update screen ten times\n\
        \"Transparency Panel\"  \"Draw each plane\" -- Update screen continuously\n\
        \"Transparency Panel\"  \"Draw\" -- Draw with new parameters\n\
        \"Transparency Panel\"  \"Close\" -- Close control panel\n\
ORIENT FUNCTIONS: change way axes point; 2-D are in-plane\n\
        \"Orient\"      \"Side<->Top (2-D)\" -- Rotate axes\n\
        \"Orient\"      \"Front<->Side (3-D)\" -- Rotate axes\n\
        \"Orient\"      \"Top<->Front (3-D)\" -- Rotate axes\n\
        \"Orient\"      \"Front<->Extra (4-D)\" -- Rotate axes\n\
        \"Orient\"      \"Side<->Extra (4-D)\" -- Rotate axes\n\
        \"Orient\"      \"Top<->Extra (4-D)\" -- Rotate axes\n\
        \"Orient\"      \"<-Down-> (2-D)\" -- Reversal\n\
        \"Orient\"      \"<-Across-> (2-D)\" -- Reversal\n\
        \"Orient\"      \"<-Deep-> (3-D)\" -- Reversal\n\
        \"Orient\"      \"Frames to Origin\" -- Cross frames to start of origin of each axis\n\
        \"Orient\"      \"Frames in Middle\" -- Cross frames in middle of each frame\n\
        \"Orient\"      \"Labels Set ..\" -- Control panel to adjust labeling\n\
        \"Orient\"      \"Reset Initial\"\n\
SIZE FUNCTIONS: set size and shape policy\n\
        \"Size\"        \"Fit Screen\" -- Front fills 2/3s screen; sides 1/3\n\
        \"Size\"        \"True Proportions\"\n\
        \"Size\"        \"Sample per Pixel\"\n\
        \"Size\"        \"Interpolate\" -- Improves large magnifications\n\
        \"Size\"        \"Size Set ..\" -- Launch size setting control panel\n\
        \"Size Set\"    \"Minimum\" -- Minimum sample/value along axis\n\
        \"Size Set\"    \"Maximum\" -- Maximum sample/value along axis\n\
        \"Size Set\"    \"Frame\" -- Frame sample/value along axis\n\
        \"Size Set\"    \"Pixels\" -- Pixels along axis\n\
        \"Size Set\"    \"Draw\" -- Draw these size settings\n\
        \"Size Set\"    \"Current\" -- Restore current size settings\n\
        \"Size Set\"    \"Initial\" -- Fill in initial settings\n\
        \"Size Set\"    \"Close\" -- Close size settings panel\n\
        \"Size\"        \"Reset Initial\"\n\
        \"Size\"        \"LEFT MOUSE BOX ZOOMS\" -- interactive magnification\n\
        \"Size\"        \"+ 'h' KEY ONLY HORZ\" -- constrain to horizontal\n\
        \"Size\"        \"+ 'v' KEY ONLY VERT\" -- constrain to vertical\n\
MOVIE FUNCTIONS: go to part of the cube; run movies\n\
        \"Movie\"       \"Reset Bounds\" -- Movie loop traverses full cross face\n\
        \"Movie\"       \"High Speed\" -- Frames are stored in displat terminal\n\
        \"Movie\" BUTTON \"GO\" -- Start movie\n\
        \"Movie\" BUTTON \"NO\" -- Stop movie\n\
        \"Movie\" BUTTON \" z \" -- Run/step in direction\n\
        \"Movie\" BUTTON \" Z \" -- Run/step out direction\n\
        \"Movie\" BUTTON \" < \" -- Run/step left direction\n\
        \"Movie\" BUTTON \" > \" -- Run/step right direction\n\
        \"Movie\" BUTTON \" ^ \" -- Run/step up direction\n\
        \"Movie\" BUTTON \" v \" -- Run/step down direction\n\
        \"Movie\" SLIDER \" Speed \" -- Delay between frames\n\
        \"Movie\"       \"MIDDLE MOUSE CLICK Reset cross framesFRAMES\" -- X\n\
        \"Movie\"       \"MIDDLE MOUSE DRAG MOVIE BOUNDS\" -- Set movie range\n\
COLOR FUNCTIONS: set color, contrast, and transparency\n\
        \"Color\"       \"Gray\" -- Grayscale\n\
        \"Color\"       \"Straw\" -- Blue and yellow\n\
        \"Color\"       \"Flag\" -- Red, white and blue\n\
        \"Color\"       \"Tiger\" -- Red, white and black\n\
        \"Color\"       \"Blue\" -- Blue and white\n\
        \"Color\"       \"Rainbow\" -- Multi-colored\n\
        \"Color\"       \"Graybow\" -- Gray plus multi-colored\n\
        \"Color\"       \"Overlay\" <color-list> -- Overlay lines and text\n\
        \"Color\"       \"Mark\" <color-list> -- Pick color\n\
        \"Color\"       \"Background\" <color-list> -- Screen background color\n\
        \"Color\"       \"Flip Polarity\" -- of data-> color\n\
        \"Color\"       \"Reset Contrast\" -- No skew or zero point contrast\n\
        \"Color\" SLIDER \"CONTRAST\" -- Shift color table skew\n\
        \"Color\" SLIDER \"CONTRAST0\" -- Shift color table zero point\n\
        \"Color\" SLIDER \"TRANSPARENCY\" -- Change transparency value\n\
        \"Color\" BUTTON \"Reset\" -- Reset initial contrast\n\
PICK FUNCTIONS: set picking behavior\n\
        \"Pick\"        \"Clear Current Line\" -- Erase pick line or sub-volume\n\
        \"Pick\"        \"Write pick file\" -- Write to pick= now\n\
        \"Pick\"        \"Read pick file\" -- Read from pick= now\n\
        \"Pick\"        \"RIGHT MOUSE MAKES PICK\" -- right mouse button manipulates picks\n\
        \"Pick\"        \"+ 'a' KEY ADDS POINT TO END OF LINE\"\n\
        \"Pick\"        \"+ 'i' KEY INSERTS POINT BETWEEN NEAREST POINTS\"\n\
        \"Pick\"        \"+ 'm' KEY MOVES NEAREST POINT\"\n\
        \"Pick\"        \"+ 'd' KEY DELETES NEAREST POINT\"\n\
        \"Pick\"        \"+ 's' KEY + DRAGGING PICKS SUB-VOLUME\"\n\
EDIT FUNCTIONS: edit grid sub-volume\n\
        \"Edit\"        \"Clear Sub-volume pick\" -- Clear current subvolume\n\
        \"Edit\"        \"Smooth Sub-volume\" -- Smooth sub-volume to boundary value\n\
        \"Edit\"        \"Undo Smooth\" -- Restore sub-volume\n\
        \"Edit\"        \"Grade Sub-volume\" -- Grade sub-volume to boundary plane values\n\
        \"Edit\"        \"Undo grade\"\n\
        \"Edit\"        \"Sub-volume Neighborhood\" <6, 18, 26> -- Cube connectivity of sub-volume\n\
        \"Edit\"        \"COLOR BAR MOUSE SETS SMOOTH RANGE\"\n\
SECTION FUNCTION: plot various sections through the data\n\
        \"Section\"     \"On screen wiggle plot ...\"   \"Front, side or top plane\"\n\
        \"Section\"     \"On screen contour plot ...\"  \"Front, side or top plane\"\n\
        \"Section\"     \"On screen graph profile ...\" \"Down, across, or deep profile\"\n\
        \"Section\"     \"Print wiggle plot ...\"       \"Front, side or top plane\"\n\
        \"Section\"     \"Print contour plot ...\"      \"Front, side or top plane\"\n\
        \"Section\"     \"Print graph profile ...\"     \"Down, across, or deep profile\"\n\
        \"Section\"     \"Save section in file ...\"    \"Front, side or top plane\"\n\
        \"Section\"     \"Save profile in file ...\"    \"Save down, across, or deep profile\"\n\
        \"Section\"     \"PLANES AND PROFILES ARE SELECTED AT CROSS-HAIRS\"\n\
STATUS FUNCTIONS: print parameters and state variables\n\
        \"Status\"      \"Dataset\" -- Dataset parameters\n\
        \"Status\"      \"Data Values\" -- Data value parameters\n\
        \"Status\"      \"Data Axis0\" -- Value/color axis\n\
        \"Status\"      \"Data Axis1\" -- Fast axis, usually time\n\
        \"Status\"      \"Data Axis2\" -- Second data axis, usually CDP\n\
        \"Status\"      \"Data Axis3\" -- Slow axis, usually section\n\
        \"Status\"      \"Data Axis4\" -- Slow axis, usually offset\n\
        \"Status\"      \"Data Axis5\" -- Slow axis, unused\n\
        \"Status\"      \"Style\" -- View parameters\n\
        \"Status\"      \"Down Axis\" -- View down axis parameters\n\
        \"Status\"      \"Across Axis\" -- View across axis parameters\n\
        \"Status\"      \"Deep Axis\" -- View deep axis parameters\n\
        \"Status\"      \"Extra Axis\" -- View extra axis parameters\n\
        \"Status\"      \"Color Axis\" -- Colorbar axis parameters\n\
        \"Status\"      \"Color\" -- Color and contrast parameters\n\
        \"Status\"      \"Render\" -- Rendering parameters\n\
        \"Status\"      \"Draw\" -- Draw screen parameters\n\
        \"Status\"      \"Mouse Buttons\" -- Mouse button functions\n\
        \"Status\"      \"Movie\" -- Movie parameters\n\
        \"Status\"      \"Pick\" -- Pick parameters\n\
        \"Status\"      \"Pick List\" -- Current pick line parameters\n\
        \"Status\"      \"sub-volume\" -- Current mark sub-volume\n\
        \"Status\"      \"Frame List\" -- List of screen frames\n\
HELP FUNCTIONS: print self documentation from various places\n\
        \"Help\"        \"Command Line Args\"\n\
        \"Help\"        \"File Formats\"\n\
        \"Help\"        \"Windows\"\n\
        \"Help\"        \"Mouse Usage\"\n\
        \"Help\"        \"Main Functions\"\n\
        \"Help\"        \"Style Functions\"\n\
        \"Help\"        \"Orient Functions\"\n\
        \"Help\"        \"Size Functions\"\n\
        \"Help\"        \"Movie Functions\"\n\
        \"Help\"        \"Color Functions\"\n\
        \"Help\"        \"Picking Functions\"\n\
        \"Help\"        \"Status Functions\"\n\
END\n";


/* print text on screen */
void HelpPrint(char *start, char *finish)
{
    char    *startp = 0, *finishp = 0;
    extern char *help, *strstr(const char *, const char *);

    startp = strstr(help, start);
    finishp = strstr(help, finish);
    if (startp == 0 || finishp == 0 ){
        return;
    }
    for( ; startp < finishp; startp++ ){
        (void)fputc(*startp, stderr);
    }
    (void)fputc('\n', stderr);
    (void)fflush(stderr);
}

/* pipe text through more */
void HelpMore(char *start, char *finish)
{
    FILE    *pfile, *popen(const char *, const char *);
    char    *startp = 0, *finishp = 0;
    extern char *help, *strstr(const char *, const char *);

    startp = strstr(help, start);
    finishp = strstr(help, finish);
    if (startp == 0 || finishp == 0 ){
        return;
    }
    pfile = popen("more", "w");
    for( ; startp < finishp; startp++ ){
        (void)fputc(*startp, pfile);
    }
    (void)fputc('\n', pfile);
    (void)fflush(pfile);
    (void)pclose(pfile);
}
