#! /bin/sh
# TapeRead

csu segyread.c
csu segywrite.c

suplane >junk.su
segyhdrs <junk.su
segywrite <junk.su tape=junk.tape

segyread buff=0 tape=junk.tape hfile=h.out bfile=b.out >junk.out
supswigp <junk.out | open

surange <junk.su
surange <junk.out