.TH AIRY 3CWP CWP
.UC 4
.SH NAME
airya, airyb, airyap, airybp \- compute approximations to the Airy functions
Ai(x), Bi(x), and their respective derivatives Ai'(x), Bi'(x)
.SH SYNOPSIS
.nf
.B #include """cwp.h"""
.PP
.B "float airya (float x)"
.PP
.B "float airyap (float x)"
.PP
.B "float airyb (float x)"
.PP
.B "float airybp (float x)"
.fi

.SH DESCRIPTION
.I Airya
computes an approximation to the Airy function, Ai(x),
.PP
.I Airyap
computes an approximation to the derivative of the Airy function, Ai'(x)
.PP
.I Airyb
computes an approximation to the Airy function, Bi(x),
.PP
.I Airybp
computes an approximation to the derivative of the Airy function, Bi'(x)
.PP
The routines is contained in the  .../cwp/lib/airya.c, airyap.c, airyb.c, and airya.c.
.P
The
.I Airy
functions Ai(x) and Bi(x) are solutions to Airy's differential equation:
.na
.nf
u''(x) - x u(x) = 0, see Abromovitz and Stegun, p.446-452.
.fi
.ad

.SH PARAMETERS
.TP 8
.I x
are floats representing values on the real line.

.SH RETURN VALUE
The
.I airy
routines return a single float for each input float.

.SH USAGE EXAMPLE
.na
.nf
	float x,ya,yap,yb,ybp;
	
	ya = airya(x)
	yap = airyap(x)
	yb = airyb(x)
	ybp = airybp(x)

.fi
.ad

.SH REFERENCES
References:
Abromovitz, M. and Stegun, I. A., 1964, Handbook of Mathmatical Functions,
Dover, N. Y.

.SH AUTHOR
Dave Hale.
.SH REVISION LEVEL
1.1 (92/06/11)

