/*
CDOC
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 *** Function:	zgtmsg_(prmt,msg,prmtlen,msglen)		D. Trimmer
 
 *** Purpose:	Prints a prompt message on the standard output, and
		receives a reply on the standard intput.
 
 *** Inputs:	prmt	A pointer to a string containing the prompt.
			The end of prompt delimeter is a '$'.
		msg	A pointer to a string to receive the prompt.
		prmtlen A long containing the size of prmt (automatically
			generated by UNIX VAX F77)
		msglen  A long containing the size of msg (automatically
			generated by UNIX VAX F77)
 
 *** Returns:	message from standard input is returned in msg
 
 *** Notes:	This function is to be called by a FORTRAN routine.  The
		'_' is appended to the name for compatibility with FORTRAN.
 
		Arguments prmtlen and msglen are for generated by F77.
 
 *** Calls:	Function getline()
 
 *** History:	07/24/84   Copied from zgtmsg_()--D. Trimmer
		07/24/84   Tested--D. Trimmer
 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
CEND
*/
#include "config.h"
#include "stdu.h"
 
#ifndef READLINE
zgtmsg(prmt,prmtlen,msg,msglen)
char *prmt;		/* pointer to prompt message */
long prmtlen;		/* length of prmt array */
char *msg;		/* pointer to character array to receive input */
long msglen;		/* length of msg array */
 
{
 
	while (*prmt != '$')
		putchar (*(prmt++));	/* print prompt */
	putchar('\n');
 
	getline (stdin,msg,(short) msglen);
	return;
}
 
#else 

#include "../../inc/select.h"

static 
void process_line(char *p) { 
  select_loop_continue(SELECT_OFF);
  select_loop_message(p, SELECT_MSG_SET);
  return; 
}

zgtmsg(char *prmt, long prmtlen,char *msg, long msglen) {
  select_loop(prmt, prmtlen, msg, msglen, NULL, process_line);
}


#endif /* ! READLINE */
