##################################################################
##
#
# KEYWORDS:  $RCSfile: Makefile,v $
#            $Revision: 1.2 $
#            $Date: 2001/09/13 20:23:56 $
#            $Author: ahmilb $
#
#------------------------------------------------------------------
#
# HISTORY:
#
#
#
###################################################################

include ../../Makefile_template_part1

PROG = bhplibseq.a
RCSfiles.c = bhpioseq_lib.c interp_lib.c bhpio_lib.c
OBJS.c = obj/$(PLATFORMID)/bhpioseq_lib.o obj/$(PLATFORMID)/interp_lib.o obj/$(PLATFORMID)/bhpio_lib.o
PACK = ../../bin/$(PLATFORMID)/bhplibseq.a

include ../../Makefile_template_lib
