#!/bin/bash

#
# Prestack equivalent offset time migration demo
#
#John C. Bancroft, Hugh D. Geiger,and Gary F. Margrave,Geophysics 63, 2042 (1998)
#
#
# First shotgathers are created around a point diffractor embeded in a uniform 
# velocity medium. Uniform is used fro simplicity but it can be variable.
# The data is sorted to CDP gathers and then toCommon scatterpoint gathers.
# Finally the scatterpoint gathers are moveout corrected and stacked.
# This can be done by simple NMO - no phase correction and frequency shifting
# Stolt migration based MO - this gives correct results
# Kirchoff migration based MO - this also should give correct results ( more work needed in the code)

#
# This example suffers from inadequate sampling but shows the general idea
#


# receiver lines X direction
# Shot lines Y direction


# Scatter point location and medium velocity
x0=1000
y0=1000
z0=200
c=2000
# sampling
dt=0.001
nt=1000

# Definituion of folder names
sdir=shots
cdir=cdps

cspdir="csp_tables_1000m"
cspgdir="csp_gathers"
tf="list_of_csp_tables_1000m"

# Recording patch definition

# shot is always at the middle of the middle receiver line
rl_n=5		# five receiver lines; this has to be odd
rl_dx=100	# 100 m receiver line distance
r_dy=50		# 60 m receiver spacing
r_n=21		# 21 receiver per line; this has to be odd

# Shot lines definition
sx0=500		# First shot x
sy0=500		# First shot y

# Number of shot lines
Ns_l=11
# Shot line dx
Sl_dx=100

# Number of shots per line
Nspl=21
# Shot distance within line
S_sy=50


# Filter definitions
f="1,4,30,60"

Scount=0

function patch()
{
	# source locations
	xs=$1
	ys=$2
	zs=$3
	
	# location of the first geophone of every line
	for irl in `seq $rl_n`
	do
		
		yg=`bc -l << ENDYL
			scale=0
			(($rl_n-1)/2-$irl+1)*$rl_dx+$ys
ENDYL`
		xg=`bc -l << ENDXG
			scale=0
			-($r_n-1)/2*$r_dy+$xs
ENDXG`
		
		sudif3d nshot=1 nrec=$r_n    \
			c=$c dt=$dt nt=$nt   \
			x0=$x0 y0=$y0 z0=$z0 \
			sxmin=$xs symin=$ys  szmin=$zs \
			gxmin=$xg gymin=$yg dgx=$r_dy |
			sushw key=sx,sy a=$xs,$ys |
			suchw key1=swdep key2=gx |
			suchw key1=gwdep key2=gy |
			sushw key=ep a=$Scount   | 	# Shot number is a seq number
			# Receiver number rx*1000+ry			
			suchw key1=sdepth  key2=swdep key3=gwdep b=1000 c=1 | 	
			suoffazi off=1 |		
			su3dbin \
			dirx=1 diry=1 \
			dbx=50 dby=50 \
			xc=225 yc=385 |
			sufilter f=$f >> shots.su
			
			
	
	done
	let "Scount = Scount+1"
	
	
}


if [ -f shots.su ]
then
	rm shots.su
fi

#
echo " Creating shots records"
#

# For every shot line
for Sl in `seq $Ns_l`
	do
	
	# For every shot on shot line
	for S in `seq $Nspl`
		do
		#compute shot coordinate
		
		sx=`bc -l << ENDSX
			scale=0
			($Sl-1)*$Sl_dx+$sx0
ENDSX`
		sy=`bc -l << ENDSY
			scale=0
			$S_sy*($S-1)+$sy0
ENDSY`
		
		patch $sx $sy 0
		
		done
	
	done



echo "Sorting to shot gathers in $sdir"
#
	suputgthr_sort key=ep dir=$sdir < shots.su
	rm shots.su
	
#
echo "Sorting to cdp gathers in $cdir"
#
	sugetgthr dir=$sdir 	|
	suputgthr_sort key=cdp dir=$cdir

#
echo "Creating tables for scatter point gathers"
#
	
	# Create tables for scatter point gathers
	
if [ -d $cspdir ]
then 
	rm -fr $cspdir
fi

	mkdir $cspdir
	sucspg_prep xm=1000 \
	            xc=225 yc=385 dbx=50 dby=50 \
		    dirx=1 diry=1 nx=31 ny=25 \
		    dir=$cspdir

if [ -f $tf ]
then
	rm $tf
fi
	
for fn in `ls -1 $cspdir | sort -n`
do
	echo $cspdir'/'$fn >> $tf
done

	
if [ -d $cspgdir ]
then 
	rm -fr $cspgdir
fi
	mkdir $cspgdir

#
echo "Creating common scatter point gathers - this will take a while"
#

	sumcspg dh=20 v=2000 \
		hs=100 hm=1000 mts=-100 \
		ssx=sx ssy=sy sgx=swdep sgy=gwdep \
	igdir=$cdir ogdir=$cspgdir itbf=$tf


#
#
echo "Creating velocity file"
#
	sugetgthr dir=$cspgdir 	|
	sustack key=fldr        |
	suzero itmax=1000 value=1000 |
	suchw key1=cdp key2=fldr \
	> prestack_mig_vel.su
	
#
#
echo "Moveout correction and stacking of CSP gathers" 
echo "See NMO SNMO KNMO optionsin script"
#

	sugetgthr dir=$cspgdir 	|
	suchw key1=tracf key2=cdp |
	suchw key1=cdp key2=fldr |
	# Normal MO	
#	sufnmo f=prestack_mig_vel.su |
	# Stolt migration based MO
	susnmo3d f=prestack_mig_vel.su |
	# Kirchoff migration based MO - this needs some more work
#	suknmo3d f=prestack_mig_vel.su |
	sustack key=cdp 	     \
	> prestack_mig.su
	
	susort < prestack_mig.su ep |
	suwind key=ep min=13 max=13 |
	suximage blockinterp=1 title="Inline 13" &
	
	susort < prestack_mig.su tracf |
	suwind  \
	key=tracf min=16 max=16    |
	suximage blockinterp=1 title="Xnline 15" &
	
	suslice < prestack_mig.su \
	ts=0.22                   |
	ximage n1=25 n2=31 title="horizontal slice" blockinterp=1 &

