#! /bin/sh
replace "MUSTIGETPAR" "MUSTGETPARINT   " $*
replace "MUSTFGETPAR" "MUSTGETPARFLOAT " $*
replace "MUSTSGETPAR" "MUSTGETPARSTRING" $*
replace "sgetpar" "getparstring" $*
replace "fgetpar" "getparfloat " $*
replace "dgetpar" "getpardouble" $*
replace "igetpar" "getparint   " $*
replace "pgetpar" "getparuint  " $*
replace "hgetpar" "getparshort " $*
replace "ugetpar" "getparushort" $*
replace "lgetpar" "getparlong  " $*
replace "vgetpar" "getparulong " $*
replace "syserr" "err" $*
