
include ../../Makefile_template_part1

PROG = bhplibapi.a
RCSfiles.c = bhpio_api_lib.c
OBJS.c = obj/$(PLATFORMID)/bhpio_api_lib.o
PACK = ../../bin/$(PLATFORMID)/bhplibapi.a

include ../../Makefile_template_lib
