
include ../../Makefile_template_part1

PROG = bhplibvel.a
RCSfiles.c = bhp_vel_lib.c
OBJS.c = obj/$(PLATFORMID)/bhp_vel_lib.o
PACK = ../../bin/$(PLATFORMID)/bhplibvel.a

include ../../Makefile_template_lib
