#!/bin/sh

ARCH=`uname -srm | sed 's/.[0-9]*-[^ ]*//' | sed 's/ /_/g'`

if [ ! -f Config/Makefile.config.${ARCH} ]
   then

   echo "Config/Makefile.config.${ARCH} not found!"
   echo "Please create one using the examples in Config"

   exit

else

   mkdir ${SLTROOT}/${ARCH}
   mkdir ${SLTROOT}/${ARCH}/bin
   mkdir ${SLTROOT}/${ARCH}/lib
   echo "Found Config/Makefile.config.${ARCH}"
   echo "You should be ready to compile SLT/SU"


fi
