.TH CONV_FLOAT 3SU SU
.SH NAME
.B conv_float \-
convert between 32 bit IBM and IEEE floating numbers
.SH SYNOPSIS
.nf
void conv_float(from,to,len,type)
char *from, *to;
int len, type;
.SH DESCRIPTION
.I Conv_float
does the conversion between 32 bit IBM floating point numbers
(the SEG-Y standard)
and IEEE floating point numbers (used by Masscomp and many others).
Although this routine is intrinsically system dependent,
byte swapping branches (the identity map for the present case)
have been inserted to ease rewriting for other machines (eg. VAX).
.SH PARAMETERS
.TP 8
.I from
The input data vector.
.TP
.I to
The output data vector, can be same as input vector,
.TP
.I len
The number of floats in the data vectors.
.TP
.I type
The conversion direction.  The two valid values are 1 to convert
from IEEE to IBM and 2 to convert from IBM to IEEE.
.SH CAVEATS
Up to 3 bits are lost when converting IEEE to IBM.
.sp
When converting IBM to IEEE, the numbers may overflow or underflow.
This is taken care of by respectively substituting a large number or zero.
.SH SEE ALSO
segyread(1) segywrite(1)
.SH AUTHOR
 Brian
.SH SOURCE
su/lib/conv_float.c
.SH REVISION LEVEL
1.4
