.TH DOPBAL 3SU SU
.SH NAME
.B dopbal \-
power balance a data vector
.SH SYNOPSIS
.nf
void dopbal(dataptr, nfloat)
float *dataptr;
int nfloat;
.SH DESCRIPTION
.I Dopbal
scales ("balances") a data vector by the power of the the data vector.
In this context, the "power" of a vector is taken to be the root mean
square of the data vector (i.e., the square root is taken)
to preserve dimensionality.
.P
In the usual SU application, the data vector is created by concatenating
the data portions of a sequence of SEG-Y traces.
In this case, the "power" value is computed using the entire original data set.
If, instead, trace by trace power balancing is desired, then dopbal can be
called in a loop or (usually more convenient) the SEG-Y traces can be
filtered through sugain (1).
.P
This subroutine may be evoked in combination with other gain, scale or
balance parameters by calling it from gain(3SU).
.SH PARAMETERS
.TP 8
.I dataptr
Pointer to the data vector.
.TP
.I nfloat
The total data count (the number of samples per
trace times the number of traces in the original SEG-Y data set).
.SH SEE ALSO
sugain(1) suagc(1) quant(3SU) gain(3SU) dotpow(3SU) doepow(3SU)
dogpow(3SU) doagc(3SU)
dotrap(3SU) doclip(3SU) doqclip(3SU) doqbal(3SU) doscale(3SU)
.SH AUTHORS
Jon, Shuki, Jack
.SH SOURCE
su/lib/gainpkge.c
.SH REVISION LEVEL
1.8
