.TH DOTPR 3VEC SU
.SH NAME
.B dotpr \-
dot product of two vectors
.SH SYNOPSIS
.nf
subroutine dotpr(a, i, b, j, c, n)
integer i, j, n
real c
real a(1:n), b(1:n)
.SH DESCRIPTION
.I Dotpr
computes the dot product of two vectors and stores the result in a scalar.
Using the notation in the synopsis,
the vectors a and b are dotted and the sum is
stored in the scalar c.
.P
In the case of unit spacing in all indices, the operation can be written:
.sp
.nf
     c = sum (a(i) * b(i)), where i goes from 1 to n.
.fi
.sp
.P
The vectors need not be distinct.  The vector length is n and
the index increments for a and b are respectively i and j.
The most common case, i = j = 1, is optimized in the code.
.SH C USAGE
In general:
.nf
dotpr_(a, &i, b, &j, &c, &n);
.fi
.sp
For unit increments:
.nf
dotpr_(a, &_one, b, &_one, &c, &n);
.SH FORTRAN USAGE
.nf
call dotpr(a, i, b, j, c, n)
.SH CREDITS
Jack Dongarra, Floating Point Systems (see veclib(3vec)).
.SH AUTHOR
Jack
.SH SOURCE
general/Veclib/dotpr.f
.SH REVISION LEVEL
1.7
