.TH DOTPOW 3SU SU
.SH NAME
.B dotpow \-
gain data vector by power of time
.SH SYNOPSIS
.nf
void dotpow(dataptr, tpow, tmin, dt, nt, ntr)
float *dataptr;
float tpow, tmin, dt;
int nt, ntr;
.SH DESCRIPTION
.I Dotpow
multiplies the data by the "tpow" power of the "time."
The "time" value is constructed from the passed values of "tmin" and "dt."
In the usual SU application, the data vector is created by concatenating
the data portions of a sequence of SEG-Y traces.
However, because the "time" value is required, the data vector is treated
essentially as a sequence of data traces with consequent loss of efficiency.
.P
This subroutine may be evoked in combination with other gain, scale or
balance parameters by calling it from gain(3SU).
.SH PARAMETERS
.TP 8
.I dataptr
Pointer to the data vector.
.TP
.I tpow
The power of time to gain by.
.TP
.I tmin
The time corresponding to the first datum on each of the original
SEG-Y traces.
.TP
.I dt
The sampling rate of the original SEG-Y data.
.TP
.I nt
The number of samples on each of the original SEG-Y traces.
.TP
.I ntr
The number of traces in the original SEG-Y data set.
.SH SEE ALSO
sugain(1) suagc(1) gain(3SU) doepow(3SU) doagc(3SU) dogpow(3SU)
dotrap(3SU) doclip(3SU) doqclip(3SU) doqbal(3SU) dopbal(3SU) doscale(3SU)
.SH AUTHORS
Jon, Shuki, Jack
.SH SOURCE
su/lib/gainpkge.c
.SH REVISION LEVEL
1.8
