.TH GETHVAL 3SU SU
.SH NAME
.B gethval \-
get SEG-Y header values by index
.SH SYNOPSIS
.nf
#include "../include/cwp.h"
#include "../include/segy.h"
#include "../include/hdr.h"
void gethval(trace_ptr, index, val_ptr)
char *trace_ptr;
int index;
value *val_ptr;
.SH DESCRIPTION
Get the value of the key word given a pointer to the trace and
the index of the key word.  The key word index may be obtained by calling
getindex(3SU).
.I Gethval
supports all the simple C types and stores the value of the header word
in *val_ptr as the appropriate type.
.SH EXAMPLE
.na
.nf
       char *key;       /* header key word from segy.h    */
       char *type;      /* ... its type                   */
       int index;       /* ... its index in hdr.h         */
       value val;       /* ... its value                  */
       ...
       /* Default parameters;       User-defined overrides */
       key = "offset";              sgetpar("key", &key);

       type = hdtype(key);
       index = getindex(key);

       while (gettr(&tr)) {
              gethval(&tr, index, &val);
              /* Change the value */
              ...
              puthval(&tr, index, &val);
              puttr(&tr);
       }
       ...
.fi
.ad
.SH DIAGNOSTICS
.TP 8
.I "gethval: mysterious data type"
A defensive programming message indicating a bug in the routine.
.SH SEE ALSO
puthval(3SU) gethdval(3SU) puthdval(3SU) hdtype(3SU) getkey(3SU)
getindex(3SU)
.SH AUTHOR
Einar, Jack
.SH SOURCE
su/lib/hdpkge.c
.SH REVISION LEVEL
1.22
