.TH GETKEY 3SU SU
.SH NAME
.B getkey \-
get header word name in SEG-Y header from its index
.SH SYNOPSIS
.nf
#include "../include/cwp.h"
#include "../include/segy.h"
#include "../include/hdr.h"
char *getkey(index)
int index;
.SH DESCRIPTION
Get header (key) word name in SEG-Y header from its index (0 <= index < SY_NK).
.SH RETURN VALUE
.I Getkey
returns a pointer to a string containing the header word name or NULL (0)
if not found.
.SH CAVEAT
The SEP analog, "gkey", used a range shifted to the right by unity from
.I getkey's
range.
.SH SEE ALSO
gethval(3SU) puthval(3SU) gethdval(3SU) puthdval(3SU) getindex(3SU)
.SH AUTHOR
Einar, Jack
.SH SOURCE
su/lib/hdrpkge.c
.SH REVISION LEVEL
1.22
