.TH PUTHDVAL 3SU SU
.SH NAME
.B puthdval \-
get and put SEGY header value from header word name in segy.h
.SH SYNOPSIS
.nf
#include "../include/cwp.h"
#include "../include/segy.h"
#include "../include/hdr.h"
void puthdval(trace_ptr, key, val_ptr)
char *trace_ptr
char *key
value *val_ptr
.SH DESCRIPTION
Put the value of the key word given a pointer to the
trace and the header word field from segy.h.
Since it uses getindex(3SU) to get the offset of the header word
from hdr.h,
.I puthdval
should \fInot\fP used inside loops.  Instead, when the value must be obtained
within a loop for the same header word, the index should be computed once for
all, \fIoutside\fP the loop with a direct call to getindex(3SU) and
puthval(3SU), which uses the index instead of the header word name
should be used inside the loop.
.I Puthdval
supports all the simple C types and stores the value of the header word
in *val_ptr as the appropriate type.
.SH DIAGNOSTICS
.TP 8
.I "puthdval: key word not in segy.h: '...'"
The passed header word was not found by getindex(3SU) (probably due
to a typo).
.TP
.I "puthdval: mysterious data type"
A defensive programming message indicating a bug in the routine.
.SH SEE ALSO
gethdval(3SU) gethval(3SU) puthval(3SU) hdtype(3SU) getkey(3SU)
getindex(3SU)
.SH AUTHOR
Jack, with a credit to Einar for the earlier puthval(3) that had
the main ideas.
.SH SOURCE
su/lib/hdrpkge.c
.SH REVISION LEVEL
1.22
