.TH QUANT 3SU SU
.SH NAME
.B quant \-
return k/n th quantile of a vector
.SH SYNOPSIS
.nf
float quant(a, k, n)
float *a;
int k, n;
.SH DESCRIPTION
.I quant
returns the k/n quantile of a vector.
.I Quant
is called by doqclip(3SU) and doqbal(3SU).
(A quantile of a data set is a percentile divided by 100 and lies 
between 0 and 1; for example, the .95 quantile is the 95th percentile.)
.SH PARAMETERS
.TP 8
.I a
Pointer to the data vector.
.TP
.I k
The index of the quantile.
.TP
.I n
The number of data points.
.SH SEE ALSO
gain(3SU) doqclip(3SU) dopbal(3SU)
.SH AUTHORS
This is the famous Hoare algorithm as worked over by SEP (#10, p. 100)
and by Brian.
.SH SOURCE
su/lib/gainpkge.c
.SH REVISION LEVEL
1.8
