.TH SELFDOC 3SU SU
.SH NAME
.B selfdoc \-
print the self documentation of the calling application program
.SH SYNOPSIS
.nf
#include <stdio.h>
void selfdoc()
.SH DESCRIPTION
.I Selfdoc
prints the the self documentation string of the calling
program on the stderr and exits(1).  More(1) is used to paginate the output.
.SH EXAMPLE
.nf
	if ( xargc != 3 ) selfdoc();
.SH DIAGNOSTICS
Only from system call errors (fflush, popen, pclose).
.SH SEE ALSO
exit(1) more(1) err(3SU) syserr(3SU)
.SH AUTHOR
Einar
.SH SOURCE
su/lib/selfdoc.c
.SH REVISION LEVEL
1.23
