.TH STATPRINT 3SU SU
.SH NAME
.B statprint \-
print ascii string describing the type of the file (TTY, DISK, ...).
.SH SYNOPSIS
.nf
#include "../include/cwp.h"
char *statprint(fd);
int fd;
.SH DESCRIPTION
.I Statprint
returns the ascii name of the file type in capital letters.
.P
A test driver is contained in the statfil.c source code and the
makefile in the su/lib directory has a routine for compiling and
running the driver.
.SH RETURN VALUE
The appropriate ascii string from among:
BADFILETYPE, TTY, DISK, DIRECTORY, TAPE, PIPE.
.SH SEE ALSO
isatty(3), fstat(2), stat(2), statfil(3su).
.SH AUTHOR
Jack
.SH SOURCE
su/lib/statfil.c
.SH REVISION LEVEL
1.26
