.ds U \s-2\f(sRUNIX\fR\s0
.ds S \s-2\f(sRSU\fR\s0
.ds SY \s-2\f(sRSEG-Y\fR\s0
.TH SULIB 3SU SU
.SH NAME
.B sulib \-
Introduction to the C library for the
.I Seismic Unix
(\*S) processing line
.SH DESCRIPTION
The C library subroutines used by \*S programmers to write
.I
SU
application programs.  See the
.I
suintro(1)
manual page for an introduction to the application
programs themselves.
Below is a list of the functions with one line descriptions,
see the individual manual pages for complete descriptions.
.SH FUNCTIONS (5/31/88)
.sp .5v
.TP 12
.I askdoc
evoke self documentation string at user request
.TP
.I atohe
convert ascii to short with overflow check
.TP
.I atoie
convert ascii to int with overflow check
.TP
.I atole
convert ascii to long with overflow check
.TP
.I atope
convert ascii to unsigned int with overflow check
.TP
.I atoue
convert ascii to unsigned short with overflow check
.TP
.I atoval
cast ascii to value (*)
.TP
.I atove
convert ascii to unsigned long with overflow check
.TP
.I conv_float
convert between IBM and Masscomp floating point
.TP
.I die_
primitive debugging abort from Fortran subroutine (*)
.TP
.I dmatrix
allocate a double matrix with given row and column sizes
.TP
.I doagc
apply automatic gain control
.TP
.I doclip
clip outliers
.TP
.I doepow
multiply by exp(t*tpow)
.TP
.I dogpow
dynamic compression by power gpow
.TP
.I dopbal
power balance
.TP
.I doqbal
quantile balance
.TP
.I doqclip
clip values above given quantile
.TP
.I doscale
apply overall scale factor
.TP
.I dotpow
multiply by pow(t, tpow)
.TP
.I dotrap
zero outliers
.TP
.I dvector
allocate double vector with given length
.TP
.I efread
fread with error check (*)
.TP
.I efwrite
fwrite with error check (*)
.TP
.I eread
read with error check (*)
.TP
.I ewrite
write with error check (*)
.TP
.I err
print message on application program error and abort calling program
.TP
.I fftlib
mixed radix transform package (see fftlib(3su)) (*)
.TP
.I fftseplib
Stanford FFT package (see fftseplib(3su)) (*)
.TP
.I fgetpar
get float namelist parameter
.TP
.I fgettr
get a SEG-Y trace
.TP
.I fgettr1
get a char packed SEG-Y trace
.TP
.I fgettr2
get a short packed SEG-Y trace
.TP
.I fprintfval
fprintf a value variable (*)
.TP
.I fputtr
put a SEG-Y trace
.TP
.I fputtr1
put a char packed SEG-Y trace
.TP
.I fputtr2
put a short packed SEG-Y trace
.TP
.I free_matrix
free a float matrix allocated by matrix()
.TP
.I free_imatrix
free an int matrix allocated by imatrix()
.TP
.I free_dmatrix
free a double matrix allocated by dmatrix()
.TP
.I free_vector
free a float vector allocated by vector()
.TP
.I free_ivector
free an int vector allocated by ivector()
.TP
.I free_dvector
free a double vector allocated by dvector()
.TP
.I gain
calls the routines in gainpkge (dotpow, doepow, etc.)
.TP
.I gethdval
get an SEG-Y header word by name
.TP
.I gethval
get an SEG-Y header word by index
.TP
.I getindex
get the index of an SEG-Y header word from the name (*)
.TP
.I getkey
get the name of an SEG-Y header word from its index
.TP
.I getname
get file name from file descriptor (*)
.TP
.I gettr
get a SEG-Y trace from stdin
.TP
.I gettr1
get a char packed SEG-Y trace from stdin
.TP
.I gettr2
get a short packed SEG-Y trace from stdin
.TP
.I gettra
get disk trace by trace number (random access) (*)
.TP
.I hdtype
get the type of an SEG-Y header word by name (*)
.TP
.I hgetpar
get short namelist parameter
.TP
.I igetpar
get int namelist parameter
.TP
.I imatrix
allocate an int matrix with given row and column sizes
.TP
.I initgetpar
initialize getpar facility (*)
.TP
.I ivector
allocate an int vector with given length
.TP
.I lgetpar
get long namelist parameter
.TP
.I matrix
allocate a float matrix with given row and column sizes
.TP
.I maxgetpar
return the size of the longest getpar parameter vector
.TP
.I pgetpar
get unsigned int namelist parameter
.TP
.I pfread
fread on pipe with error check (*)
.TP
.I pread
read on pipe with error check (*)
.TP
.I printftype
printf the type of a header key word (*)
.TP
.I printfval
printf a value variable (*)
.TP
.I printheader
display non-null header field values (*)
.TP
.I puthdval
put an SEG-Y header word by name
.TP
.I puthval
put an SEG-Y header word by index
.TP
.I puttr
put a SEG-Y trace on stdout
.TP
.I puttr1
put a char packed SEG-Y trace on stdout
.TP
.I puttr2
put a short packed SEG-Y trace on stdout
.TP
.I quant
get quantile from data vector
.TP
.I re_ivector
reallocate an int vector
.TP
.I re_dvector
reallocate a double vector
.TP
.I re_vector
reallocate a float vector
.TP
.I rew
rewind file (*)
.TP
.I scanfval
scanf a value variable (*)
.TP
.I selfdoc
print self documentation string
.TP
.I sgetpar
get string namelist parameter
.TP
.I statfil
determine type of file from file descriptor
.TP
.I statprint
print the file type as an ascii string
.TP
.I sulib
lint library (*)
.TP
.I syserr
print message on system call failure and abort calling program
.TP
.I syswarn
print warning on system call failure
.TP
.I tabplot
tab plot subroutine (*)
.TP
.I ugetpar
get unsigned short namelist parameter
.TP
.I valcmp
compare value variables (*)
.TP
.I veclib
library of vector arithmetic routines (see veclib(3su))
.TP
.I vector
allocate a float vector with given length
.TP
.I vertwig
plot wiggle traces vertically (*)
.TP
.I vgetpar
get unsigned long namelist parameter
.TP
.I vtof
cast value variable to a float (*)
.TP
.I vtoi
cast value variable to an int (*)
.TP
.I vtol
cast value variable to a long (*)
.TP
.I vtoz
cast value variable to a double (*)
.TP
.I warn
print warning on application program error
.TP
.I wrtflt_
primitive debugging write of a float from a Fortran subroutine (*)
.TP
.I wrtint_
primitive debugging write of an int from a Fortran subroutine (*)
.TP
.I wrtstr_
primitive debugging write of a string from a Fortran subroutine (*)
.TP
.I zgetpar
get double namelist parameter
.P
The symbol (*) is used above to indicate subroutines whose
manual pages have not been written.  The header comments
in the source code provide partial documentation.
.SH BUGS
Send reports to:
.ne 6
.sp
.nf
Jack K. Cohen
Center for Wave Phenomena
Colorado School of Mines
Golden, CO 80401
.fi
.SH FILES
At the Center for Wave Phenomena,
the directory for source code is /src and our directory for
compiled code is /usr.  These prefixes are omitted below
since they may not apply to other sites.
.sp .5v
.TP 24
.I su/src/lib/*.c
C subroutine source
.TP
.I local/lib/libsu.a
C compiled subroutine archive
.TP
.I su/src/man/*
manual page source
.SH SEE ALSO
suintro(1) veclib(3SU) fftlib(3SU)
.SH AUTHORS
Einar, Shuki, Jack and others (see suintro(1) and the individual
subroutine manual pages).
.SH REVISION DATE
03/02/89
