.TH WARN 3SU SU
.SH NAME
.B warn \-
routine for reporting application error
.SH SYNOPSIS
.nf
#include "../include/cwp.h"
#include <varargs.h>
.sp 0.5v
void warn(va_alist)
va_dcl
.fi
.P
Here, "va_alist" and "va_dcl" are defined in varargs.h.  For common use,
the syntax may be thought of as
.sp
.nf
void warn(format, args)
.fi
.sp
where "format" represents a printf format string (except that a
trailing "\en" is supplied automatically) and "args" represents
the variables referenced in the format string.
.SH DESCRIPTION
.I Warn
provides a flexible method for reporting application program errors in
the style of printf(3S).  Unlike err(3SU), warn does not abort the
program.
This routine is more flexible
than perror(3C), since it allows an arbitrary number of arguments.
.P
For portability, this routine uses varargs and the "format"
and "args" are bundled as per vararg.h.
.P
A test driver is contained in the errpkge source code and the
makefile in the su/lib directory has a routine for compiling and
running the driver.
.SH EXAMPLE
.nf
	warn("fmax = %f exceeds half nyquist= %f", fmax, 0.25/dt);
.SH SEE ALSO
printf(3S) perror(3C) errpkge(3SU), err(3SU)
.SH AUTHOR
Jeff Thorson, Stew, Shuki, Jack.  Major ideas were taken from
Kernighan and Pike, "The UNIX Programming Environment", page 207,
and Rochkind, "Advanced UNIX Programming", page 13.
.SH SOURCE
su/lib/errpkge.c
.SH REVISION LEVEL
1.6
