# Makefile for ...su/graphics/x

include $(CWPROOT)/src/Makefile.config

#
# Dsu modifications
#
B = $(PVM_ROOT)/bin/$(PVM_ARCH)
D = ../../lib/libdsu.a $L/libcwp.a $L/libpar.a $L/libsu.a
DSUMAIN = $(CWPROOT)/src/su/graphics/xplot
CFLAGS= -I../../include -I$I $(OPTC) $(ENDIANFLAG) -I$(PVM_ROOT)/include
LDSU = -L../../lib -ldsu -L$(PVM_ROOT)/lib/$(PVM_ARCH) -lpvm3
LFLAGS= $(PRELFLAGS) $(LDSU) -L$L -lsu -lpar -lcwp -lm $(POSTLFLAGS)
CTARGET = $(DSUMAIN)/$$(@F).c
#CTARGET = $B/%: $(DSUMAIN)/%.c
#
# End Dsu modifications
#


PROGS  =        $B/suximage     \
                $B/suxwigb      \
                $B/suxgraph     \
                $B/suxmax       \
                $B/suxmovie


INSTALL	:	$(PROGS)
	touch $@


$(PROGS):	$(CTARGET) $D 
	@echo installing $(@F) in $B
	-$(CC) -DDO_GLOBALS $(CFLAGS) $(DSUMAIN)/$(@F).c $(LFLAGS) -o $@
	@chmod 755 $@
	@echo $(@F) installed in $B

remake	:
	-touch $(DSUMAIN)/*.c 
	-rm -f $(PROGS)
	$(MAKE) 
	
clean:
	rm -f a.out junk* JUNK* core
