#!/bin/sh

nargs=$#
if [ ${nargs} -eq 0 ]
then
  $0cube
  exit
fi

part0=`bhpfiletype $*`
lockfile=${part0}_LOCK.HDR

test -f ${lockfile} && type=NEW
test ! -f ${lockfile} && type=OLD

if [ ${type} = "OLD" ]
then
  $0seq $*
else
  $0cube $*
fi
