#! /bin/sh
# CSHOT NMO demo with CWP PostScript Graphics

SCRATCH=/scratch/jkcohen/Nmodata

VIEWER="rsh keller -l jkc images"
GRAPHER=psgraph
IMAGER=supsimage
WIGGER=supswigp

# x and z plot ranges for model/ray plotting
x1beg=0 x1end=5500 x2beg=-100 x2end=8500

# Plot just the layers
cp param1.1 param1
cshot1 |
cshotplot >plotfile  outpar=parfile
rm param1
$GRAPHER <plotfile par=parfile style=seismic \
	title="Reflectors for NMO demo" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end | $VIEWER
rm plotfile parfile


# Plot the rays
cp param1.2 param1
cp geometry.2 geometry
cshot1 |
cshotplot >plotfile  outpar=parfile
rm param1 geometry
$GRAPHER <plotfile par=parfile style=seismic \
	title="Rays for First Shot" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end | $VIEWER
rm plotfile parfile


# Make Data
echo "REMOVE comments from the Make Data paragraph if data not already made"
pause proceed or ctrl-C to abort
#cp param1.save param1
#cp geometry.save geometry
#cshot1 >/dev/null 2>&1
#cshot2
#mv traces $SCRATCH
#rm nmoshot  # ray info
#suaddhead <$SCRATCH/traces ns=501 ftn=1 |
#sushw key=dt a=4000 |
#sushw key=sx a=1400 c=-50 j=64 |
#sushw key=offset a=100 b=100 j=64 |
#suchw key1=gx key2=offset key3=sx b=1 c=1 |
#suchw key1=cdp key2=gx key3=sx b=1 c=1 d=2  |
#suaddnoise sn=50 f1=4.0 f2=8.0 f3=45.0 f4=50.0 >$SCRATCH/traces.su
#rm $SCRATCH/traces


# Plot some shot records
suwind <$SCRATCH/traces.su key=sx s=1400 j=500 |
sugain tpow=2 gpow=0.5 |
$IMAGER label1="Time" label2="Trace" \
	title="Every 10th Shot Record (display gained)" | $VIEWER

# Look at velocity scans -- in reality would make picks
# Plot the picks ordinarily made interactively
nv=100
dv=50.0
fv=4000.0
fold=64
nout=501 # ns
dxout=0.004
for cdp in 1500 2000 2500 3000
do
	suwind <$SCRATCH/traces.su key=cdp min=$cdp max=$cdp count=$fold |
	suvelan nv=$nv dv=$dv fv=$fv |
	$IMAGER bclip=0.5 wclip=0.0 f2=$fv d2=$dv \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Velocity Scan for CMP $cdp" \
		grid1=solid grid2=solid cmap=default | $VIEWER
	sed <par.$cdp '
		s/tnmo/xin/
		s/vnmo/yin/
	' >unisam.p
	unisam nout=$nout fxout=0.0 dxout=$dxout \
		par=unisam.p method=spline |
	$GRAPHER n=$nout nplot=1 d1=$dxout f1=0.0 \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Stacking Velocity Function: CMP $cdp" \
		grid1=solid grid2=solid \
		linecolor=2 style=seismic | $VIEWER
done


# Do NMO
sunmo <$SCRATCH/traces.su par=stkvel.par >$SCRATCH/sengbush.nmo

# Display NMO
suwind <$SCRATCH/sengbush.nmo key=sx s=1400 j=250 |
sugain tpow=2 gpow=0.5 |
$IMAGER label1="Time" title="Every 10th CDP after NMO" | $VIEWER

# Sort to CDP's and stack
susort <$SCRATCH/sengbush.nmo |
sustack normpow=1.0 >$SCRATCH/sengbush.stack

# Display Stack
sugain <$SCRATCH/sengbush.stack tpow=2 gpow=0.5 |
$IMAGER f2=300 d2=50 \
label1="Time" label2="CMP" title="Stack" | $VIEWER

rm $SCRATCH/sengbush.nmo $SCRATCH/sengbush.stack

exit
