#B	= /usr/local/
B	= /users/shuki/bin/

#L	= -lsu
L	= ../lsu/libsu.a ../lCC/libCC.a

#LP	= -lplot
LP	= ../lplot/libplot.a

#LV	= -lvec
LV	= ../lvec/libvec.a

CFLAGS= -g
FFLAGS= -g

X =	$Bsugain $Bsuplot $Bsupr $Bsumax $Bchart $Bplot	\
	$Bsusort $Bsunmo $Bsustack $Bsudmo $Bsuahed 	\
	$Bdotpow

ALLX =	$Bsuhis $Bsuedit $Bsugethw $Bsuinfo $Bsumute	\
	$Bsushw $Bsuchw $Bsuabshw $Bsustrip \
	$Bsuchart $Bsu3dchart $Bsupow $Bsuprhws $Bsuus	\
	$Bsuwind $Bsudelm $Bsuagc $Bcmgstrip $Bsubin $Bsurange	\
	$Bsuunglitch $Bsuswap $Bsucdpnum \
	$Bsubpus $Bsupack1 $Bsupack2 $Bsuunpack1	\
	$Bsuunpack2 $B3dchart $Bchart $Bsufft $Bsulog		\
	$Bsusyn3 $Bsup \
	$Bsueplot $Bsugray $Bsupr $Bsuprpl $Bsudiff $Bsusgn

PROBLEMS =	$Bsuxspec3 $Bsyread $Bsuxspec $Bspecpow

all	:$X
	@echo made

relink	:
	touch *.o
	make all

remake	:
	/bin/rm -f *.o
	make all
	
notyet:	$Bsctrbal $Bwes4read $Bsycube \
	$Bsyxfft \
	$Bsybp $Bsygbig $Bsyva $Bsymvs \
	$Bsyinmo stackopt syapply stsave $Bsypef

$Bsup sup	:sup.csh
	cp sup.csh $Bsup
	chmod 775 $Bsup

$Bsuhis suhis	:suhis.o $L
	cc -g suhis.o $L -lm -o $Bsuhis

$Bsumerge sumerge	:sumerge.o $L
	cc -g sumerge.o $L -lm -o $Bsumerge

$Bsudiff sudiff	:sudiff.o $L
	cc -g sudiff.o $L -lm -o $Bsudiff

$Bsusgn susgn	:susgn.o $L
	cc -g susgn.o $L -o $Bsusgn

$Bsuprpl suprpl	:suprpl.o $L
	cc -g suprpl.o $L -o $Bsuprpl

$Bsumax sumax: sutrseq.o max.o $L
	cc -g sutrseq.o max.o $L -lm -o $Bsumax

$Bsupr supr	:sutrseq.o pr.o $L
	cc -g sutrseq.o pr.o $L -o $Bsupr

$Bsusyn3 susyn3	:susyn3.o $L
	cc -g susyn3.o $L -lm -o $Bsusyn3

$Bspecpow specpow	: specpow.o $L
	cc -g specpow.o $L -lm -o $Bspecpow

$Bsuxspec suxspec	: suxspec.o $L
	cc -g suxspec.o $L -lm -o $Bsuxspec

$Bsupmovie supmovie	: supmovie.o $L
	cc -g supmovie.o $L -lm -lgp -o $Bsupmovie

$Bsuilog suilog	: suilog.o $L
	cc -g suilog.o $L -lm -o $Bsuilog

$Bsulog sulog	: sulog.o $L
	cc -g sulog.o $L -lm -o $Bsulog

$Bsucz1 sucz1	: sucz1.o tabfil.o $L
	cc -g sucz1.o tabfil.o $L -lF77 -lm -o $Bsucz1

$Bsufft sufft	: sufft.o $L
	cc -g sufft.o $L -lm -o $Bsufft

$Bplot plot	:plot.csh
	cp plot.csh $Bplot
	chmod 775 $Bplot

$Bchart chart	:chart.csh
	cp chart.csh $Bchart
	chmod 775 $Bchart

$B3dchart B3dchart	:	3dchart
	cp 3dchart $B
	chmod 775 $B3dchart

$Bsuinfo suinfo	: suinfo.o $L
	cc -g suinfo.o $L -o $Bsuinfo

$Bsupack1 supack1	: supack1.c $L
	cc -g supack1.c $L -lm -o $Bsupack1

$Bsupack2 supack2	: supack2.c $L
	cc -g supack2.c $L -lm -o $Bsupack2

$Bsuunpack1 suunpack1	: suunpack1.c $L
	cc -g suunpack1.c $L -lm -o $Bsuunpack1

$Bsuunpack2 suunpack2	: suunpack2.c $L
	cc -g suunpack2.c $L -lm -o $Bsuunpack2

$Bsuplot suplot:	sutrseq.o plot.o $(LP) $L
	cc -g sutrseq.o plot.o $(LP) $L -lm -o $Bsuplot

$Bsugray sugray:	sugray.o gain.o $L
	cc -g sugray.o gain.o $L -lm -o $Bsugray

$Bsueplot sueplot:	sueplot.o gain.o $L
	cc -g sueplot.o gain.o $L -lm -o $Bsueplot

$Bcmgstrip cmgstrip: cmgstrip.o $L
	cc -g cmgstrip.o $L  -lm -o $Bcmgstrip

stack.o: stack.r
	ratfor -6 -C <stack.r > stack.f
	f77 -g -c `pwd`/stack.f
	rm -f stack.f
$Boffsetabs offsetabs: offsetabs.o $L
	cc -g offsetabs.o $L   -o $Boffsetabs
#dlsqr_.o: dlsqr_.f
#	f77 -c -O2 `pwd`/dlsqr_.f
#$Bsctrbal sctrbal: sctrbal.c trbal.c dlsqr_.o $L
#	cc -g `pwd`/sctrbal.c `pwd`/trbal.c dlsqr_.o $L  -lblas \
#		-lF77 -lI77 -lU77 -lm
#	install -m 555 -g sep a.out $Bsctrbal
$Bsuedit suedit: suedit.o $L
	cc -g suedit.o $L   -o $Bsuedit
$Bstackopt stackopt:
	cd dstackopt; make
$Bsubin subin: subin.o $L
	cc -g subin.o $L  -lm -o $Bsubin
$Bsubp subp: subp.o apbf.o $L
	cc -g subp.o apbf.o $L -lm -o $Bsubp
#cc -g subp.o apbf_.o $(LA) $L  -lm -o $Bsubp
$Bsucube sucube: sucube.c $L
	cc -g `pwd`/sucube.c $L 
	install -m 555 -g sep a.out $Bsucube
esttr.o: esttr.r
	ratfor -6 -C esttr.r > esttr.f
	f77 -c -O2 `pwd`/esttr.f
	rm -f esttr.f
#$BsuEst suEst: suEst.c esttr.o scdecon/vectpow.o $L
#	cc -g suEst.c esttr.o scdecon/vectpow.o $L -lvec $(LA)  -lF77 -lI77 -lU77
	install -m 555 -g sep a.out $BsuEst

$Bsunmo sunmo: sutrseq.o nmo.o nmosubs.o $L
	cc -g sutrseq.o nmo.o nmosubs.o $L -lm -o $Bsunmo
#cc -g sunmo.o nmosubs.o $L -lF77 -lI77 -lU77 -lm -o $Bsunmo
nmosubs.o:	nmosubs.f
	f77 -c -g nmosubs.f


$Bsutpow sutpow: sutrseq.o tpow.o $L
	cc -g sutrseq.o tpow.o $L -lm -o $Bsutpow

$Bsugain sugain: sutrseq.o gain.o $L
	cc -g sutrseq.o gain.o $L -lm -o $Bsugain

$Bsugbig sugbig: sugbig.o apbf_.o $L
	cc -g sugbig.o apbf_.o $(LA) $L  -lm -o $Bsugbig
$Bsugethw sugethw: sugethw.o $L
	cc -g sugethw.o $L   -o $Bsugethw
$Bsumute sumute: sumute.o $L
	cc -g sumute.o $L   -o $Bsumute
$Bsupef supef: supef.o pefsubs.o $L
	cc -g supef.o pefsubs.o $L -lm  -o $Bsupef
$Bsuprhws suprhws: suprhws.o $L
	cc -g suprhws.o $L   -o $Bsuprhws
$Bsurange surange: surange.o $L
	cc -g surange.o $L  -o $Bsurange
$Bsyread syread: syread.o $L
	cc -g syread.o $L  -o $Bsyread
$Bsucdpnum sucdpnum: sucdpnum.o $L
	cc -g sucdpnum.o $L  -o $Bsucdpnum
$Bsurec surec: surec.o $L
	cc -g surec.o $L -lblas  -o $Bsurec
$Bsutrunk sutrunk: sutrunk.o $L
	cc -g sutrunk.o $L   -o $Bsutrunk
$Bsuus suus: suus.o $L
	cc -g suus.o $L  -o $Bsuus
$Bsuwind suwind: suwind.o $L
	cc -g suwind.o $L  -o $Bsuwind
$Bsudelm sudelm: sudelm.o $L
	cc -g sudelm.o $L   -o $Bsudelm

$Bsudmo sudmo: sudmo.o $L
	cc sudmo.o $L $(LV) -lF77 -lm -o $Bsudmo

$Bsuva suva: suva.o apva1_.o apva2_.o $L
	cc -g suva.o apva1_.o apva2_.o $(LA) $L  -lU77 -lm -o $Bsuva
$Bsumvs sumvs: sumvs.o apmvs_.o $L
	cc -g sumvs.o apmvs_.o $(LA) $L  -lF77 -lU77 -lm -o $Bsumvs
$Bsywrite sywrite: sywrite.o $L
	cc -g sywrite.o $L  -o $Bsywrite
$Bsushw sushw: sushw.o $L
	cc -g sushw.o $L   -lm -o $Bsushw
$Bsuabshw suabshw: suabshw.o $L
	cc -g suabshw.o $L   -lm -o $Bsuabshw
$Bsustrip sustrip: sustrip.o $L
	cc -g sustrip.o $L   -o $Bsustrip

$Bsustack sustack: sustack.o $L $(LV)
	cc -g sustack.o $L $(LV) -lm -o $Bsustack

$Bsusort susort: susort.o $L
	cc -g susort.o $L -o $Bsusort

$Bsuunglitch suunglitch: suunglitch.o unglitch.o $L
	cc -g suunglitch.o unglitch.o $L  -o $Bsuunglitch
$Bsuchw suchw: suchw.o $L
	cc -g suchw.o $L   -o $Bsuchw
$Bsuagc suagc: suagc.o $L
	cc -g suagc.o $L   -o $Bsuagc
$Bsu3dchart su3dchart: su3dchart.o $L
	cc -g su3dchart.o $L  -o $Bsu3dchart
$Bsuchart suchart: suchart.o $L
	cc -g suchart.o $L  -o $Bsuchart

$Bsuahed suahed: suahed.o $L
	cc -g suahed.o $L -o $Bsuahed

$Bsubpus subpus: subpus.o bpus.o $L
	cc -g subpus.o bpus.o $L  -o $Bsubpus
#$Btget tget: tget.o $L
#	cc -g tget.o $L  -o $Btget
$Bsupow supow: supow.o $L
	cc -g supow.o $L -lm -o $Bsupow
$Bwes4read wes4read: wes4read.o $L
	cc -g wes4read.o $(LA) $L  -lm -o $Bwes4read
$Bwes4tape :wes4tape
	&cp wes4tape $Bwes4tape
	&chmod 775 $Bwes4tape
$Bsuxspec3 suxspec3:suxspec3.o $L
	cc -g suxspec3.o $L -lm -o $Bsuxspec3
$Bsuxfft3 suxfft3:suxfft3.o $L
	cc -g suxfft3.o $L -lm -o $Bsuxfft3
$Bsuxfft suxfft:suxfft.o $L
	cc -g suxfft.o $L  -lF77 -lU77 -lI77 -lm -o $Bsuxfft
$Bsuswap suswap:suswap.o $L
	cc -g suswap.o $L  -lm -o $Bsuswap

suapply:
	(cd dstackopt; make $Bsuapply)
stsave:
	(cd dstackopt; make $Bstsave)

clean cleanup:
	-rm -f *.o


runnmo:	NMO
	/bin/echo ""
	/bin/ls -l $DDATA $DNMO
	/bin/echo "Starting cmp: silence is golden"
	/bin/cmp $DNMO $Dsydata.nmo

NMO:	$Bsunmo
	$Bsunmo <$DDATA >$DNMO par=nmofile

runpack:	PACK1 UNPACK1 PACK2 UNPACK2
	/bin/echo ""
	/bin/ls -l $DDATA $DPACK1 $DPACK2 $DUNPACK1 $DUNPACK2
	/bin/echo "Starting cmp's: silence is golden"
	/bin/echo "Testing sypack1:"
	/bin/cmp $DUNPACK1 $Dsydata1.pu
	/bin/echo "Testing sypack2:"
	/bin/cmp $DUNPACK2 $Dsydata2.pu

PACK1:	$Bsypack1
	$Bsypack1 <$DDATA >$DPACK1 2>>$DERRORLOG
UNPACK1: $Bsyunpack1
	$Bsyunpack1 <$DPACK1 >$DUNPACK1 2>>$DERRORLOG
PACK2:	$Bsypack2
	$Bsypack2 <$DDATA >$DPACK2 2>>$DERRORLOG
UNPACK2: $Bsyunpack2
	$Bsyunpack2 <$DPACK2 >$DUNPACK2 2>>$DERRORLOG
