#! /bin/sh
# Flip tester

suplane >data
supswigp <data title="Original Data" | images

#/usr/local/cwp/bin/suflip <data flip=1 verbose=1 >oldflipout
#./suflip <data flip=1 verbose=1 >newflipout
#supswigp<oldflipout title="flip 1, (old)" | images
#supswigp<newflipout title="flip 1, (new)" | images
#sudiff oldflipout newflipout | 
#supswigp title="diff" | images

#exit

suflip <data flip=1 verbose=1 |
supswigp title="flip 1, (90 c)" | images

suflip <data flip=-1 verbose=1 |
supswigp title="flip -1, (90 cc)" | images

suflip <data flip=0 verbose=1 |
supswigp title="flip 0, (transpose)" | images

suflip <data flip=2 verbose=1 |
supswigp title="flip 2, (right-to-left)" | images

suflip <data flip=3 verbose=1 |
supswigp title="flip 3, (top-to-bottom)" | images
