# Makefile for ...su/lib

include $(CWPROOT)/src/Makefile.config

LFLAGS= -L$L -lpar -lcwp -lm
TFLAGS = -g -I$I

LIB = $L/libsu.a

ARCH =	$(LIB)(fgettr.o)	\
	$(LIB)(fputtr.o)	\
	$(LIB)(hdrpkge.o)	\
	$(LIB)(valpkge.o)	\
	$(LIB)(tabplot.o)


INSTALL:	$(LIB)
	@-rm -f INSTALL
	@touch $@

$(LIB)	:	$(ARCH)
	$(RANLIB) $(LIB)


remake	:
	@-rm -f $(LIB) INSTALL
	@$(MAKE)

list	:
	$(AR) tv $(LIB)


# Testing routines
tests: tgettr tputtr tarray

tgettr:	fgettr.c
	$(CC) $(TFLAGS) -DTEST -DGETTR fgettr.c $(LIB) $(LFLAGS) -o tgettr
	@echo tgettr ready--running benchmark
	suplane offset=-100 | sugethw offset
	@echo convert offset to absolute value
	suplane offset=-100 | tgettr | sugethw offset

tputtr:	fputtr.c
	$(CC) $(TFLAGS) -DTEST -DPUTTR fputtr.c $(LIB) $(LFLAGS) -o tputtr
	@echo tputtr ready--running benchmark
	suplane offset=-100 | sugethw offset
	@echo convert offset to absolute value
	suplane offset=-100 | tputtr | sugethw offset

tarray:	arraypkge.c
	$(CC) $(TFLAGS) -DTEST arraypkge.c $(LIB) $(LFLAGS) -o tarray
	@echo arraypkge ready--running benchmark
	-tarray

clean:
	rm -f ato err io tarray tgetname tgetpar tgettr tputtr tstatfil \
		junk* core a.out

.PRECIOUS: $(LIB)
