#! /bin/sh


TARLIST1="cxzco.tar.Z sumiggbzo.tar.Z suinvvxzco.tar.Z miggbzo3d.tar.Z"

j=1
jmax=2
while [ "$j" -ne "$jmax" ]
do
	echo "Disk set $j:"
	echo
	pause after putting the disk in drive

	echo "Making Disk #1:"
	echo
	/usr/bin/setfdprm /dev/fd0 1440/1440
	/usr/bin/fdformat /dev/fd0

	tar -cvf /dev/fd0 $TARLIST1

	j=`expr $j + 1`
done

