#! /bin/sh

TARLIST1="README_FIRST_PROP \
U-NUMBERS	\
rays.tar.Z	\
ccco.tar.Z	\
cz.tar.Z	\
cshot.tar.Z	\
cxz.tar.Z	\
elas.tar.Z	\
triso.tar.Z	\
bdmo.tar.Z	\
cxzcs.tar.Z	\
extrap.tar.Z	\
cxzco.tar.Z	\
cwell.tar.Z	\
sumiggbzo.tar.Z	\
sudipdivcor.tar.Z	\
dmovz.tar.Z	\
suinvvxzco.tar.Z"

TARLIST2="sudmofkcw.tar.Z	\
dmolevan.tar.Z	\
miggbzo3d.tar.Z	\
dmoir3d.tar.Z	\
susynlvfti.tar.Z	\
gbmod.tar.Z	\
fct.tar.Z	\
miggbzoan.tar.Z	\
extrapvti.tar.Z	\
sudgast.tar.Z	\
sumigpsti.tar.Z	\
sudmotivz.tar.Z	\
tifowler.tar.Z	\
tihaledmo.tar.Z	\
fctanis.tar.Z	\
extminti.tar.Z	\
suinvvxzcs.tar.Z	\
suinvvxz_m.tar.Z	\
tricxzco.tar.Z	\
mrafxzwt.tar.Z \
trielas.tar.Z \
refaniso.tar.Z \
suvel2df.tar.Z \
suwfrayt3d.tar.Z \
sutetraray.tar.Z"

j=1
jmax=2
while [ "$j" -ne "$jmax" ]
do
	echo "Disk set $j:"
	echo
	echo
	pause after putting the disk in drive

	echo "Making Disk #1:"
	echo
	pause after putting the disk in drive
	/usr/bin/setfdprm /dev/fd0 1440/1440
	/usr/bin/fdformat /dev/fd0

	tar -cvf /dev/fd0 $TARLIST1

	pause after replacing the disk that is in the drive with a new one
	echo
	echo
	echo
	echo

	echo "Making Disk #2:"
	echo
	echo
	echo
	echo
	/usr/bin/setfdprm /dev/fd0 1440/1440
	/usr/bin/fdformat /dev/fd0

	tar -cvf /dev/fd0 $TARLIST2

	j=`expr $j + 1`
done

exit 0
U38: SUINVVXZ_M: Zhenyue Liu's Kirchhoff-WKBJ common offset Inversion
	with extra amplitudes for determining traveltime derivatives with
	respect to specific parameters of a velocity function. This
	code is used as part of Dr. Liu's velocity analysis method.
U-39: TRICXZCO: Boyi Ou's Kirchhoff-WKBJ Common Offset Inversion 
        for TRIangulated C(X,Z) background sloth models. 
U-40: MRAFXZWT, Zhaobo Meng's Multi-Resolution Analysis of a function
                F(X,Z) by Wavelet Transform.
