#
# makefile for the su/lvec directory
#

CFLAGS = -g
FFLAGS = -g

L     =	./libvec.a
#LDIR	= /usr/local/lib/
#L = $(LDIR)libvec.a

O =	$L(libvec.o)							\
	$L(cefft.o) $L(cvfft.o) $L(refft.o) $L(rvfft.o) $L(convv.o) $L(rowcc.o)	\
	$L(dotpow.o) $L(doagc.o) $L(doclip.o) $L(doepow.o) $L(dogpow.o) \
	$L(doqbal.o) $L(dopbal.o) $L(doscale.o) $L(dotrap.o) \
	$L(quant.o) $L(balclip.o) $L(copyabs.o) $L(bfill.o)		\
	$L(operhan.o)

#.SUFFIXES: .c .r .f .o
#.c.o:	;cc $(CFLAGS) -c $*.c;
#.f.o:	;f77 $(FFLAGS) -c $*.f;
#.r.f:	;ratfor $*.r > $*.f

$L lvec : $O
	ranlib $L

list	:
	ar tv $L

remake	:
	rm -f $L
	make $L

operhan.o	:operhan.f
	f77 -c $(CFLAGS) operhan.f
rowcc.o	:rowcc.f
	f77 -c $(CFLAGS) rowcc.f
convv.o	:convv.f
	f77 -c $(CFLAGS) convv.f

clean	:
	-/bin/rm -f *.o
	-/bin/rm -f *.a
