#! /bin/sh
# autodemo - some movie displays
# Usage : autodemo
#
# $Author: jkc $
# $Source: /data/Cwpdemo/RCS/autodemo,v $
# $Revision: 1.3 $ ; $Date: 88/10/13 23:34:00 $

case $TERM in
falco)
	fill=0
	sz="sizet=6 sizex=4.5"
;;
*)
	fill=1
	sz="sizet=9 sizex=6.5"
;;
esac

while :
do

cleargp
echo
echo "  "
echo "              *******************************************************"
echo "              *                                                     *"
echo "              *                                                     *"
echo "              *              CWP RESEARCH  VIGNETTES                *"
echo "              *                                                     *"
echo "              *                                                     *"
echo "              *                 Chris Liner                         *"
echo "              *                 Sebastien Geoltrain                 *"
echo "              *                 Jack K. Cohen                       *"
echo "              *                                                     *"
echo "              *                                                     *"
echo "              *            THE CENTER FOR WAVE PHENOMENA            *"
echo "              *                 DEPT OF MATHEMATICS                 *"
echo "              *               COLORADO SCHOOL OF MINES              *"
echo "              *               GOLDEN, COLORADO 80401                *"
echo "              *                                                     *"
echo "              *                                                     *"
echo "              *******************************************************"
echo
sleep 10
clear
echo
echo
echo
echo "		***************************"
echo "		* ANISOTROPIC RAY TRACING *"
echo "		***************************"
cd Trisodemo
sleep 3
echo
echo
echo
echo
cd ..
clear
echo
echo
echo
echo "		**************************************"
echo "		* COMMON SHOT INVERSION AND STACKING *"
echo "		**************************************"
cd Shotdemo
sleep 3
echo
echo
echo
echo
echo "			THE MODEL"
echo
echo
echo
echo "		THE MODEL WAS SIMULATED BY A SIMPLE C PROGRAM AND IS"
echo
echo "		DISPLAYED HERE AS WIGGLE TRACES:"
echo
echo
echo
echo "% sutwig <model title=\"Model\" label1=Depth dt=20 tmin=1000 \\"
echo "label2=Range dx=100 xmin=0 fill=$fill $sz | tube"
echo
sleep 10
cleargp
clear
sutwig <model title="Model" label1=Depth dt=20 tmin=1000 \
label2=Range dx=100 xmin=0 fill=$fill $sz | tube
clear
echo
echo
echo
echo "		THE MODEL"
sleep 10
cleargp
clear
echo
echo
echo
echo "			THE SHOT PROFILES"
echo
echo
echo
echo "		THE SHOT PROFILES WERE PRODUCED BY PAUL DOCHERTY'S \"CSHOT\" PROGRAM"
echo
echo "		(CWP-050, CWP-U08)."
echo
echo
echo "		THIS PROGRAM COMPUTES A SPLINE THROUGH THE USER-SUPPLIED KNOTS AND"
echo
echo "		THEN USES AN EFFICIENT RAY TRACING SCHEME TO GENERATE SHOT RECORDS"
echo
echo
echo
echo "		IN THIS CASE WE MADE 17 SPLIT-SPREAD SHOT PROFILES."
echo
echo "		THE SHOT SPACING WAS 500 FEET, FIRST SHOT AT 2500."
echo
echo "		FOR EACH SHOT, THERE WERE 25 RECEIVERS ON EACH SIDE AT 100 FOOT SPACING."
echo
echo
echo
echo "		HERE IS A DISPLAY OF EVERY SECOND SHOT RECORD:"
echo
echo
echo
echo "display <shots.su"
echo
sleep 10
cleargp
clear
display <shots.su
clear
echo
echo
echo
echo "		EVERY SECOND SHOT RECORD"
sleep 10
cleargp
clear
echo
echo
echo
echo "			THE INDIVIDUAL INVERSIONS"
echo
echo
echo
echo "		THE INVERSIONS WERE PRODUCED BY A VARIANT OF MICHAEL SULLIVAN'S \"CCCO\" PROGRAM"
echo
echo "		(CWP-054, CWP-U05)."
echo
echo
echo "		CCCO INVERTS COMMON SHOT SECTIONS, THIS VARIANT (RESEARCH LEVEL CODE ONLY),"
echo
echo "		CALLED \"CCCS\", INVERTS SHOT PROFILES."
echo
echo
echo
echo "		EACH OF THE 17 INVERSIONS SHOWS ONLY A PORTION OF THE REFLECTOR."
echo
echo
echo
echo "		HERE IS A DISPLAY OF EVERY SECOND INVERSION:"
echo
echo
echo "% display <invers.su"
echo
sleep 10
cleargp
clear
display <invers.su
clear
echo
echo
echo
echo "		EVERY SECOND SHOT INVERSION"
sleep 10
cleargp
clear
echo
echo "			THE PARTIAL STACKS"
echo
echo
echo
echo "		WE ADD UP THE INDIVIDUAL INVERSIONS ONE AT A TIME STARTING FROM THE LEFT."
echo
echo
echo
echo "		HERE IS A DISPLAY OF EVERY SECOND PARTIAL STACK:"
echo
echo
echo
echo "% display <stacks.su"
echo
sleep 10
cleargp
clear
display <stacks.su
sleep 10
clear
echo
echo
echo
echo "		EVERY SECOND PARTIAL STACK"
echo
sleep 10
cleargp
clear
echo
echo
echo
echo "			ROBUSTNESS"
echo
echo
echo
echo "		LET'S EXAMINE THE FINAL STACKS OBTAINED WHEN THE INVERSION REFERENCE VELOCITY IS VARIED."
echo
echo "		THE PANELS ARE RESPECTIVELY: 20% LOW, 10% LOW, CORRECT, 10% HIGH, 20% HIGH, 40% HIGH."
echo
echo
echo
echo "% display <sums"
echo
sleep 10
cleargp
clear
display <sums
clear
echo
echo
echo
echo "SHOT STACKS WITH VELOCITY: 20% LOW, 10% LOW, CORRECT, 10% HIGH, 20% HIGH"
sleep 10
cleargp
clear
cd ..
echo
echo
echo
echo "		*************"
echo "		* DMO STUDY *"
echo "		*************"
cd Dmodemo
sleep 3
echo
echo
echo
echo
cd ..
clear
echo
echo
echo
echo "		****************************************"
echo "		* REAL DATA POST-STACK INVERSION STUDY *"
echo "          *                                      *"
echo "          * DATA COURTESY OF GOLDEN GEOPHYSICAL  *"
echo "		****************************************"
sleep 3
cd Czdemo
echo
echo
echo
echo
echo "		EIGHT SHOT PROFILES FROM THE GOLDEN GEOPHYSICAL DATA SET"
echo
echo "		960 TRACES AND 700 TIME SAMPLES"
echo
echo "		GAIN HAS BEEN APPLIED, BUT NO NMO."
echo 
echo
echo
echo "display <golden"
echo
sleep 10
cleargp
clear
display <golden
clear
echo
echo
echo
echo "		EIGHT SHOT PROFILES FROM THE GOLDEN DATA SET"
echo " "
sleep 10
cleargp
clear
echo
echo
echo
echo "		BRIAN SUMNER'S INVERSION PROGRAM, \"CZ\", USES A STRATIFIED VELOCITY MODEL"
echo
echo "		(CWP-021, CWP-U03, CWP-U06)."
echo
echo "		HERE IS A DISPLAY OF THE STACKED SECTION:"
echo
echo
echo
echo "% display <gold.stack"
echo
sleep 10
cleargp
clear
display <gold.stack
clear
echo
echo
echo
echo "		NMO STACK BY GOLDEN GEOPHYSICAL"
sleep 10
cleargp
clear
echo
echo
echo
echo " 		CONSTANT VELOCITY INVERSION BY CZ:"
echo
echo
echo
echo "% display <IMAGE.1"
cd ..
cd Cxzdemo
echo
echo
echo
echo
cd ..


# Here we go again
done
