#! /bin/sh
# graphicsdemo - CWP data displays
# Usage : graphicsdemo
#
# $Author: jkc $
# $Source: /src/su/demos/RCS/graphicsdemo,v $
# $Revision: 1.14 $ ; $Date: 88/11/21 13:51:03 $


trap "echo Gc; trap '' 0; exit 1" 0 1 2 3 15


echo "Gac"

cd Graphicsdemo

file=DATA

case $TERM in
*)
	f=0
	s="f"
;;
masscomp)
	f=1
	s=""
;;
esac


clg
echo
echo "  "
echo "              *******************************************************"
echo "              *                                                     *"
echo "              *        THIS SCRIPT GIVES AN INTRODUCTION TO         *"
echo "              *                                                     *"
echo "              *          GRAPHIC DISPLAYS IN USE AT CWP             *"
echo "              *                                                     *"
echo "              *                                                     *"
echo "              *             Chris Liner and Jack K. Cohen           *"
echo "              *                                                     *"
echo "              *                                                     *"
echo "              *            THE CENTER FOR WAVE PHENOMENA            *"
echo "              *                 DEPT OF MATHEMATICS                 *"
echo "              *               COLORADO SCHOOL OF MINES              *"
echo "              *               GOLDEN, COLORADO 80401                *"
echo "              *                                                     *"
echo "              *                                                     *"
echo "              *******************************************************"
echo
sleep 8
echo ; echo ; echo ; echo ; echo

echo "		Wiggle plots are the standard language of seismic display."
echo
echo "		Our no-frills wiggle plotter is SUWIG."
echo
echo "		Here is a run with the default parameter settings:"
echo ; echo ; echo

echo "% suwig <$file | tube"
echo ; echo
sleep 8
clg
suwig <$file | tube
echo ; echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		Let's change from the vanilla defaults:"
echo ; echo ; echo

echo "% suwig <$file sizet=10 sizex=13.8 fill=1 | tube"
echo ; echo
sleep 6
clg
suwig <$file par=${s}sizes fill=$f | tube
echo ; echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		SUWIG has a few more options, but for specialized wiggle plots,"
echo
echo "		the right tool is SUTWIG:"
echo ; echo ; echo

echo "% sutwig <$file sizet=10 sizex=13.8 | tube"
echo ; echo
sleep 6
clg
sutwig <$file par=${s}sizes fill=$f | tube
echo ; echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		Now let's get title, label and various sizes to suit."
echo
echo "		Instead of retyping them each time, let's keep the sizes in a parameter file:"
echo
echo "% cat sizes"
echo ; echo ; echo

cat sizes
echo ; echo
echo "% sutwig <$file par=sizes 	\\"
echo "title=\"Synthetic Shots\"		\\"
echo "label1=Depth tmin=1000 dt=20	\\"
echo "label2=Range xmin=0    dx=100  |"
echo "tube"
echo ; echo
sleep 6
clg
sutwig <$file par=${s}sizes 	\
title="Synthetic Shots"		\
label1=Depth tmin=1000 dt=20	\
label2=Range xmin=0    dx=100   \
fill=$f | tube
echo ; echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		How about a detail box?"
echo ; echo ; echo

echo "% sutwig <$file par=sizes db=1	\\"
echo "title=\"Synthetic Shots\"		\\"
echo "label1=Depth tmin=1000 dt=20	\\"
echo "label2=Range xmin=0    dx=100     |"
echo "tube"
echo ; echo
sleep 6
clg
sutwig <$file par=${s}sizes db=1	\
title="Synthetic Shots"			\
label1=Depth tmin=1000 dt=20		\
label2=Range xmin=0    dx=100  		\
fill=$f | tube
echo ; echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		SUTWIG2 plots side by side:"
echo ; echo ; echo

echo "suwind <$file key=tracl count=48 >TMP1"
echo "suwind <$file key=tracl min=49 >TMP2"
echo "% sutwig2 TMP1 TMP2 par=sizes2	\\"
echo "title1=\"Shots 1-4\"		\\"
echo "title2=\"Shots 5-9\"		\\"
echo "label1=Depth tmin=1000 dt=20	\\"
echo "label2=Range xmin=0    dx=100	|"
echo "tube"
echo ; echo
sleep 6
clg
suwind <$file key=tracl count=48 >TMP1
suwind <$file key=tracl min=49 >TMP2
sutwig2 TMP1 TMP2 par=${s}sizes2 	\
title1="Shots 1-4"			\
title2="Shots 5-8"			\
label1=Depth tmin=1000 dt=20		\
label2=Range xmin=0    dx=100  		\
fill=$f | tube
tube
echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		SUTWIG2V plots above and below:"
echo ; echo ; echo

echo "% sutwig2v TMP1 TMP2 par=sizes2v	\\"
echo "title1=\"Shots 1-4\"		\\"
echo "title2=\"Shots 5-8\"		\\"
echo "label1=Depth tmin=1000 dt=20	\\"
echo "label2=Range xmin=0    dx=100	|"
echo "tube"
echo ; echo
sleep 6
clg
sutwig2v TMP1 TMP2 par=${s}sizes2v	\
title1="Shots 1-4"			\
title2="Shots 5-8"			\
label1=Depth tmin=1000 dt=20		\
label2=Range xmin=0    dx=100  		\
fill=$f | tube
echo ; echo
sleep 6
clg
rm -f TMP1 TMP2
echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		And SUTWIG4 ... (you guessed it!)"
echo ; echo ; echo

echo " suwind <$file key=tracl count=24 >TMP1"
echo " suwind <$file key=tracl min=25 count=24 >TMP2"
echo " suwind <$file key=tracl min=49 count=24 >TMP3"
echo " suwind <$file key=tracl min=73 >TMP4"
echo "% sutwig4 TMP1 TMP2 TMP3 TMP4 par=sizes4 \\"
echo "title1=\"Shots 1-2\"		\\"
echo "title2=\"Shots 3-4\"		\\"
echo "title3=\"Shots 5-6\"		\\"
echo "title4=\"Shots 7-8\"		\\"
echo "label1=Depth tmin=1000 dt=20	\\"
echo "label2=Range xmin=0    dx=100	|"
echo "tube"
echo ; echo
sleep 6
clg
suwind <$file key=tracl count=24 >TMP1
suwind <$file key=tracl min=25 count=24 >TMP2
suwind <$file key=tracl min=49 count=24 >TMP3
suwind <$file key=tracl min=73 >TMP4
sutwig4 TMP1 TMP2 TMP3 TMP4 par=${s}sizes4	\
title1="Shots 1-2"				\
title2="Shots 3-4"				\
title3="Shots 5-6"				\
title4="Shots 7-8"				\
label1=Depth tmin=1000 dt=20			\
label2=Range xmin=0    dx=100  			\
fill=$f | tube
echo ; echo
sleep 6
clg
rm TMP1 TMP2 TMP3 TMP4
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		SUPWIG gives perspective plots:"
echo ; echo ; echo

echo "% supwig <$file sz=3 	\\"
echo "title=\"Synthetic Shots\" | tube"
echo ; echo
sleep 6
clg
supwig <$file fill=1 sz=3 \
title="Synthetic Shots" fill=$f | tube
echo ; echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		SUGRAPH plots amplitudes:"
echo
echo
echo
echo "% sugraph <$file			\\"
echo "title=\"Synthetic Shots\"		\\"
echo "label1=Amplitude 			\\"
echo "label2=Depth tmin=1000 dt=20	\\"
echo "tube"
echo ; echo
sleep 6
clg
sugraph <$file 			\
title="Synthetic Shots"		\
label1=Depth tmin=1000 dt=20	\
label2=Range xmin=0    dx=100  |
tube
echo
echo
sleep 6
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

#echo "		And then there's SUWIGNMAX:"
#echo
#echo ; echo
#echo "% suwignmax <$file title="Synthetic Shots" | tube "
#echo ; echo
#sleep 6
#clg
#suwignmax <$file title="Synthetic Shots" | tube
#echo ; echo
#pause
#clg
#echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		SUCONTOUR:"
echo ; echo ; echo
echo "% sucontour <$file dx=0 dy=0 	\\"
echo "title=\"Synthetic Shots\"		\\"
echo "label1=Depth tmin=1000 dt=20	\\"
echo "label2=Range xmin=0    dx=100	\\"
echo "tube"
echo ; echo
sleep 6
clg
sucontour <$file dx=0 dy=0 	\
title="Synthetic Shots"		\
label1=Depth tmin=1000 dt=20	\
label2=Range xmin=0    dx=100  |
tube
echo ; echo
sleep 6
clear
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		OOP'S ... UPSIDE DOWN AND TOO SMALL!"
echo ; echo ; echo

echo "% suflip <$file flip=3   |"
echo "sucontour dx=0 dy=0 par=sizes 	\\"
echo "title=\"Synthetic Shots\"		\\"
echo "label1=Depth tmin=1000 dt=20	\\"
echo "label2=Range xmin=0    dx=100 | tube"
echo ; echo
sleep 6
clg
suflip <$file flip=3   |
sucontour dx=0 dy=0 par=${s}sizes	\
title="Synthetic Shots"			\
label1=Depth tmin=1000 dt=20		\
label2=Range xmin=0    dx=100  | tube
echo ; echo
sleep 6
clg
clg
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		All the above displays are designed for conventional graphics devices."
echo
echo "		On a workstation, grayscale plots are faster."
echo ; echo ; echo

case $TERM in
masscomp)
	echo "% display <$file"
	echo ; echo
	sleep 3
	clg
	display <$file
;;
*)
	# Do nothing
;;
esac

clear
echo ; echo ; echo ; echo ; echo ; echo ; echo

echo "		DISPLAYS, as well as MOVIES, are used in other CWP demos."
echo ; echo
sleep 6

clg
clear
echo "Gc"

exit 0
