#!/bin/bash

# Demo of 3D modelling,
# Stacking, NM0 and Migration
#  First shotgathers are created around a point diffractor embeded in a uniform 
# velocity medium. Uniform is used for simplicity but it can be variable.
# The data is sorted to CDP gathers and then NMo corrected and stacked.
 



# receiver lines X direction
# Shot lines Y direction


# Scatter point location and medium velocity
x0=1000
y0=1000
z0=200
c=2000
# sampling
dt=0.001
nt=1000

# Definituion of folder names
sdir=shots
cdir=cdps

cspdir="csp_tables_1000m"
cspgdir="csp_gathers"
tf="list_of_csp_tables_1000m"

# Recording patch definition

# shot is always at the middle of the middle receiver line
rl_n=5		# five receiver lines; this has to be odd
rl_dx=100	# 100 m receiver line distance
r_dy=50		# 60 m receiver spacing
r_n=21		# 21 receiver per line; this has to be odd

# Shot lines definition
sx0=500		# First shot x
sy0=500		# First shot y

# Number of shot lines
Ns_l=11
# Shot line dx
Sl_dx=100

# Number of shots per line
Nspl=21
# Shot distance within line
S_sy=50


# Filter definitions
f="1,4,30,60"

Scount=0

function patch()
{
	# source locations
	xs=$1
	ys=$2
	zs=$3
	
	# location of the first geophone of every line
	for irl in `seq $rl_n`
	do
		
		yg=`bc -l << ENDYL
			scale=0
			(($rl_n-1)/2-$irl+1)*$rl_dx+$ys
ENDYL`
		xg=`bc -l << ENDXG
			scale=0
			-($r_n-1)/2*$r_dy+$xs
ENDXG`
		
		sudif3d nshot=1 nrec=$r_n    \
			c=$c dt=$dt nt=$nt   \
			x0=$x0 y0=$y0 z0=$z0 \
			sxmin=$xs symin=$ys  szmin=$zs \
			gxmin=$xg gymin=$yg dgx=$r_dy |
			sushw key=sx,sy a=$xs,$ys |
			suchw key1=swdep key2=gx |
			suchw key1=gwdep key2=gy |
			sushw key=ep a=$Scount   | 	# Shot number is a seq number
			# Receiver number rx*1000+ry			
			suchw key1=sdepth  key2=swdep key3=gwdep b=1000 c=1 | 	
			suoffazi off=1 |		
			su3dbin \
			dirx=1 diry=1 \
			dbx=50 dby=50 \
			xc=225 yc=385 |
			sufilter f=$f >> shots.su
			
			
	
	done
	let "Scount = Scount+1"
	
	
}


if [ -f shots.su ]
then
	rm shots.su
fi

#
echo " Creating shots records"
#

# For every shot line
for Sl in `seq $Ns_l`
	do
	
	# For every shot on shot line
	for S in `seq $Nspl`
		do
		#compute shot coordinate
		
		sx=`bc -l << ENDSX
			scale=0
			($Sl-1)*$Sl_dx+$sx0
ENDSX`
		sy=`bc -l << ENDSY
			scale=0
			$S_sy*($S-1)+$sy0
ENDSY`
		
		patch $sx $sy 0
		
		done
	
	done



echo "Sorting to shot gathers in $sdir"
#
	suputgthr_sort key=ep dir=$sdir < shots.su
	rm shots.su
	
#
echo "Sorting to cdp gathers in $cdir"
#
	sugetgthr dir=$sdir 	|
	suputgthr_sort key=cdp dir=$cdir
#
#
echo "Creating velocity file "
#
	sugetgthr dir=$cdir 	|
	suvwgstak_smp \
	            xc=225 yc=385 dbx=50 dby=50 \
		    dirx=1 diry=1 nx=31 ny=25 \
		    cc=0 tmpdir=.  bin_sm=0 w=0 |
	suzero itmax=1000 value=$c |
	suchw key1=tracf key2=cdp  |
	suchw key1=cdp key2=cdpt \
	> NMO_vel.su

#
echo " NMO and Creating stack"
#

	sugetgthr dir=$cdir 	|
	sufnmo f=NMO_vel.su |
	suvwgstak_smp \
	            xc=225 yc=385 dbx=50 dby=50 \
		    dirx=1 diry=1 nx=31 ny=25 \
		    cc=0 tmpdir=.  bin_sm=2 w=0 \
	> stack.su
	
#
echo " Migration"
#
	su3dkmig fs=stack.su fv=NMO_vel.su \
                 n2=25 n3=31 d2=50 d3=50 apr=75 \
                 facs=1.0 face=1.00 sphr=1 verbose=1 itp=0 dm=35 \
	> kmig.su

	susort < kmig.su ep |
	suwind key=ep min=13 max=13 |
	suximage blockinterp=1 title="Inline 13" &
	
	susort < kmig.su cdp |
	suwind  key=cdp min=16 max=16    |
	suximage blockinterp=1 title="Xnline 16" &
	
	suslice < kmig.su \
	ts=0.22                   |
	ximage n1=25 n2=31 title="horizontal slice" blockinterp=1 &
